### ISSUE TITLE
Support logging feature for the EKS control plane logs to cloudwatch

### ISSUE THREAD

**Issue by naineel** [pulumi/pulumi-eks#100]
https://aws.amazon.com/about-aws/whats-new/2019/04/amazon-eks-now-delivers-kubernetes-control-plane-logs-to-amazon-/

https://docs.aws.amazon.com/eks/latest/userguide/control-plane-logs.html

**Comment by naineel** [comment]
@metral Can we get this into the create cluster logic ?

**Comment by lukehoban** [comment]
This is blocked on https://github.com/pulumi/pulumi-aws/issues/538, but should be easy to enable once that is merged.
