### ISSUE TITLE
npm install @pulumi/newrelic returns a 404

### ISSUE THREAD

**Issue by HansMoleman** [pulumi/pulumi-eks#103]
According to this doc the new relic package should be available for download via npm but it returns a 404: https://pypi.org/project/pulumi-newrelic/

pip install works just fine

**Comment by ellismg** [comment]
Hi @HansMoleman,

The package was still marked as private on npm, so that is what was causing the 404.  I have fixed this, so you should be able to install it now via npm or yarn.  Let me know if you are still having problems.

**Comment by HansMoleman** [comment]
works now. thank you!
