### ISSUE TITLE
CoreDNS stuck on scheduling when creating a Fargate only cluster

### ISSUE THREAD

**Issue by rquitales** [pulumi/pulumi-eks#1030]
### What happened?

Create a Fargate only EKS cluster. You can use the examples in our repo for this. Once the cluster is created, observe that all CoreDNS pods are stuck being created. This can also be seen when we re-enable our Fargate tests with extra validation - all tests fails.

It's quite likely there is an issue with node affinities, though the EKS documentation does not specify other steps to upgrade the CoreDNS deployment object. When running `kubectl describe` on the unschedulable pods, the last event indicates that there are no nodes available to schedule the pod on.

### Example

- Example Pulumi program: https://github.com/pulumi/pulumi-eks/blob/62b0c2c788ec60715e6e139d85c570988e4b2ee2/examples/fargate/index.ts
- Test Failure: https://github.com/pulumi/pulumi-eks/actions/runs/7675788043/job/20925890489?pr=1026

### Additional context

EKS guide on CoreDNS with Fargate: https://docs.aws.amazon.com/eks/latest/userguide/fargate-getting-started.html#fargate-gs-coredns

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment]
The issue after further investigation is due to the CoreDNS pods being created before the Fargate Profile. Due to this, the pods will not be schedulable on Fargate only clusters. We needed to recreate the pods, by redeploying the CoreDNS deployment so that `fargate-scheduler` can take over scheduling these pods.

**Comment by arobson** [comment]
@rquitales - I have pulled in the latest version `2.2.1` but I still see this behavior. I can't tell if the roll is happening before the profile completes or not. I have even tried blocking on the fargate profile being ready, then rolling the coredns deployment, and then blocking any further activity in the stack on a `kubectl wait` command. In your tests, did you happen to deploy things that would rely on coredns being up and working for you?
