### ISSUE TITLE
Changes to CNI yaml file not deployed when upgrading `pulumi-eks` library version

### ISSUE THREAD

**Issue by ringods** [pulumi/pulumi-eks#1057]
### What happened?

The `eks.VpcCni` resource deploys a Kubernetes YAML file with CNI components. This yaml file is changed between version 2.1.0 and 2.2.0:

* https://github.com/pulumi/pulumi-eks/blob/v2.1.0/nodejs/eks/cni/aws-k8s-cni.yaml (CNI 1.11)
* https://github.com/pulumi/pulumi-eks/blob/v2.2.0/nodejs/eks/cni/aws-k8s-cni.yaml (CNI 1.16)

If you first deploy the setup from the program below with `@pulumi/eks` v2.1.0, your cluster gets the CNI v1.11 components deployed. If you upgrade this to `@pulumi/eks` v2.2.0 or higher, the expectation is that the CNI v1.16 components are deployed, but they aren't.

Related: #924 

### Example

```ts
import * as awsx from "@pulumi/awsx";
import * as eks from "@pulumi/eks";
import * as k8s from "@pulumi/kubernetes";

const vpc = new awsx.ec2.Vpc('eks-network')

// Create an EKS cluster in the VPC
const cluster = new eks.Cluster("eks-cluster", {
    vpcId: vpc.vpcId, // Use the VPC created earlier
    publicSubnetIds: vpc.publicSubnetIds, // Use the VPC public subnets for the EKS cluster
    privateSubnetIds: vpc.privateSubnetIds, // Use the VPC private subnets for the EKS cluster
    instanceType: "t2.medium", // Specify the instance type for worker nodes
    desiredCapacity: 2, // Set the desired number of worker nodes
    minSize: 1, // Set the minimum number of worker nodes
    maxSize: 3, // Set the maximum number of worker nodes
});

// Create a new NodeGroupV2 using the existing EKS cluster
const nodeGroup = new eks.NodeGroupV2("my-node-group", {
    cluster: cluster, // reference to the EKS cluster object
    version: cluster.eksCluster.version, // specify the Kubernetes version for the nodes
    instanceType: "t3.medium", // specify the instance type
    desiredCapacity: 2, // specify the desired number of nodes
    minSize: 1, // specify the minimum number of nodes
    maxSize: 3, // specify the maximum number of nodes
    amiType: "amazon-linux-2", // specify the AMI type for the nodes
});

const provider = new k8s.Provider('clusterProvider', {
    kubeconfig: cluster.kubeconfigJson
});

const vpcCni = new eks.VpcCni("cni", cluster.kubeconfigJson, {})

// Export the cluster's kubeconfig
export const kubeconfig = cluster.kubeconfig;

// Export the VPC ID and subnets
export const vpcId = vpc.vpcId;
export const publicSubnetIds = vpc.publicSubnetIds;
export const privateSubnetIds = vpc.privateSubnetIds;
```

### Output of `pulumi about`

```
pulumi about
CLI          
Version      3.107.0
Go Version   go1.22.0
Go Compiler  gc

Plugins
NAME        VERSION
aws         6.24.0
awsx        2.5.0
docker      4.5.1
docker      3.6.1
eks         2.2.1
kubernetes  4.8.1
nodejs      unknown

Host     
OS       darwin
Version  14.2.1
Arch     arm64

This project is written in nodejs: executable='/Users/ringods/.volta/bin/node' version='v18.15.0'

Current Stack: team-ce/4715/ringo

<cut out list of resources>

Found no pending operations associated with team-ce/ringo

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/v-ringo-pulumi-corp
User           v-ringo-pulumi-corp
Organizations  v-ringo-pulumi-corp, team-ce
Token type     personal

Dependencies:
NAME                VERSION
@pulumi/awsx        2.5.0
@pulumi/eks         2.2.1
@pulumi/kubernetes  4.8.1
@pulumi/pulumi      3.107.0
@types/node         18.19.19

Pulumi locates its logs in /var/folders/yq/10j1hf8s1ks9f23yxrdbbbb40000gn/T/ by default
```

### Additional context

The `check` function only resolves on the resource's inputs, not on underlying implementation details. I'm assuming no change is detected which results in the changed CNI file not being deployed.

https://github.com/pulumi/pulumi-eks/blob/1cf34825ba0327f3e366eb4dace579d1081eb5ce/nodejs/eks/cmd/provider/cni.ts#L256-L268

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by ringods** [comment]
Workaround in the meantime: force an update on the `eks.VpcCni` resource by changing the `logLevel` to a different value.

**Comment by bothra90** [comment]
FWIW, we are seeing this happen even if the first deployment happens with `@pulumi/eks: 2.2.1`. Is that expected?

**Comment by rquitales** [comment]
> FWIW, we are seeing this happen even if the first deployment happens with `@pulumi/eks: 2.2.1`. Is that expected?

Thanks for reporting this. This isn't expected and is covered by our integration tests here: https://github.com/pulumi/pulumi-eks/blob/990aa235eb2b2fd9001449b2032b940c8c5968d8/examples/examples_nodejs_test.go#L82-L84

Are you able to provide more details about what is happening here? Did you already have an existing stack using an older provider version, which you then upgraded and tried to create these resources?

**Comment by bothra90** [comment]
@rquitales: No, this was a brand-new stack created at `2.2.1`. Happy to provide any other details.

**Comment by rquitales** [comment]
@bothra90 Could you create a new GH issue, with some code examples and env details. That would be appreciated. Thanks!

**Comment by bothra90** [comment]
@rquitales: Created https://github.com/pulumi/pulumi-eks/issues/1087.
