### ISSUE TITLE
aws-node pods are crashlooping

### ISSUE THREAD

**Issue by ba1ajinaidu** [pulumi/pulumi-eks#1077]
### What happened?

aws-node pods are crashlooping (aws-eks-nodeagent container logs attached below) in a new eks cluster

```
E0307 19:47:48.587114       1 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.4/tools/cache/reflector.go:229: Failed to watch *v1alpha1.PolicyEndpoint: failed to list *v1alpha1.PolicyEndpoint: policyendpoints.networking.k8s.aws is forbidden: User "system:serviceaccount:kube-system:aws-node" cannot list resource "policyendpoints" in API group "networking.k8s.aws" at the cluster scope
```

seems like vpc-cni is being installed by pulumi and this is not a issue from vpc-cni itself 
https://github.com/aws/amazon-vpc-cni-k8s/issues/2796

### Example

```
const cluster = new eks.Cluster('eks-cluster', {
        vpcId: <vpc-id>,
        endpointPrivateAccess: true,
        endpointPublicAccess: false,
        version: "1.29",
       skipDefaultNodeGroup: true,
       nodeAssociatePublicIpAddress: false,
       createOidcProvider: true,
},{awsprovider});
```

### Output of `pulumi about`

```
$ pulumi about
CLI
Version      3.101.1
Go Version   go1.21.6
Go Compiler  gc

Plugins
NAME        VERSION
aws         6.25.0
cloudflare  5.19.0
command     0.5.2
docker      4.5.1
eks         2.2.1
kafka       3.6.0
kubernetes  4.7.1
nodejs      unknown
postgresql  3.10.1
random      4.15.1
tls         4.11.1

Host
OS       darwin
Version  14.3.1
Arch     arm64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
@ba1ajinaidu Thanks. pulumi-aws (`@pulumi/aws`) doesn't contain logic to configure the cluster, so my guess is that the crashlooping due to how pulumi-eks configures the cluster.

**Comment by bradyburke** [comment]
Seeing this same behavior. Its related to https://github.com/pulumi/pulumi-eks/issues/1057 .  The updated permissions for the service account seen [here](https://github.com/pulumi/pulumi-eks/blob/990aa235eb2b2fd9001449b2032b940c8c5968d8/nodejs/eks/cni/aws-k8s-cni.yaml#L325-L332) do not get applied. Which results in this error and the crash loop.

**Comment by bradyburke** [comment]
Also related: https://github.com/pulumi/pulumi-eks/issues/924

**Comment by ba1ajinaidu** [comment]
@bradyburke do you know any workaround for this? Other than manually patching the rbac?

**Comment by skdltmxn** [comment]
@ba1ajinaidu you can add following lines in `aws-node` cluster role

```
- apiGroups:
  - networking.k8s.aws
  resources:
  - policyendpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.aws
  resources:
  - policyendpoints/status
  verbs:
  - get
```

**Comment by ba1ajinaidu** [comment]
Yeah I know that fixes it, but I don't want to do that manually to all my clusters

**Comment by mjeffryes** [comment]
Thanks for the bug report @ba1ajinaidu and for the additional debugging context @bradyburke. We're working on a fix for #1057 right now, so hopefully we'll have a solution for you soon!

**Comment by rquitales** [comment]
@ba1ajinaidu v2.3.0 of the provider was just released. Could you check and see if this resolves this issue? Thanks!

**Comment by bothra90** [comment]
@rquitales: I work with @ba1ajinaidu. I updated one of our clusters using the new provider, but still seeing the same crashloop.

**Comment by rquitales** [comment]
@bothra90 sorry to hear that. Can you confirm if there were any updates to the config map and VpcCni resources when running `pulumi up` with the new EKS provider? If you have any log outputs when running `pulumi up`, that would also be much appreciated. Thanks!

**Comment by bothra90** [comment]
@rquitales: I don't see the errors anymore, so please feel free to close this. Thanks!

**Comment by avinassh** [comment]
Is this bug fixed for go client as well? I am running into the exact same issue and here is my system info:

```
CLI
Version      3.131.0
Go Version   go1.23.0
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  aws         6.7.0
resource  awsx        2.1.1
resource  docker      4.4.3
resource  eks         2.0.0
language  go          unknown
resource  kubernetes  4.4.0

Host
OS       darwin
Version  14.5
Arch     x86_64

This project is written in go: executable='/usr/local/bin/go' version='go version go1.22.3 darwin/amd64'

Dependencies:
NAME                                        VERSION
github.com/pulumi/pulumi-aws/sdk/v6         v6.7.0
github.com/pulumi/pulumi-awsx/sdk/v2        v2.1.1
github.com/pulumi/pulumi-eks/sdk/v2         v2.0.0
github.com/pulumi/pulumi-kubernetes/sdk/v4  v4.4.0
github.com/pulumi/pulumi/sdk/v3             v3.91.1
```
