### ISSUE TITLE
Incorrect anchor link in docs

### ISSUE THREAD

**Issue by kennethlynne** [pulumi/pulumi-eks#1090]
File: [themes/default/content/registry/packages/aws/api-docs/eks/_index.md](https://www.pulumi.com/registry/packages/aws/api-docs/eks/)

The documentation for createOidcProvider in eks.Cluster from import * as eks from '@pulumi/eks' leads users to a dead-end:
https://www.pulumi.com/registry/packages/aws/api-docs/eks/#enabling-iam-roles-for-service-accounts (note the hashtag) has no relevant information

**Comment by mjeffryes** [comment]
hi @kennethlynne; I'm sorry could you elaborate a little bit on the problem and what link landed in an unhelpful place? both links you included in your description seem to point to https://www.pulumi.com/registry/packages/aws/api-docs/eks/, but that page doesn't refer to  `createOidcProvider`

**Comment by kennethlynne** [comment]
There are several links in the documentation that refer to this exact link, but it has no more information about OIDC setup https://github.com/search?q=org%3Apulumi+enabling-iam-roles-for-service-accounts+&type=code
