### ISSUE TITLE
New clusters are failing to create due to nodes booting up with an arm64 AMI on x86_64 arch

### ISSUE THREAD

**Issue by metral** [pulumi/pulumi-eks#110]
The nodegroup AMI filter is returning an arm64 AMI for a node instance on x86_64 architecture:

```
error: Plan apply failed: 1 error occurred:

* creating urn:pulumi:dev5::kx-eks-cluster::eks:index:Cluster$aws:cloudformation/stack:Stack::kx-eks-cluster-nodes: ROLLBACK_COMPLETE: ["The following resource(s) failed to create: [NodeGroup]. . Rollback requested by user." "The requeste
d instance type's architecture (x86_64) does not match the architecture in the manifest for ami-0ef72f9111fdc5f97 (arm64). Launching EC2 instance failed."]
```

This results in a cluster that is unable of being created due to the arch mismatch, and the CloudFormation stack being put into a `ROLLBACK_COMPLETE` state.

**Comment by d-nishi** [comment]
@metral what instanceType did you use in your stack?

afaik only A1 instances support ARM64 neoverse cores and silicon from AWS. EKS recently added support for this.

I have been facing failures the whole day but with a different error:
   aws:cloudformation:Stack (eks-cluster-nodes):
    error: Plan apply failed: 1 error occurred:
    * creating urn:pulumi:dev::eks-final::eks:index:Cluster$aws:cloudformation/stack:Stack::eks-cluster-nodes: ROLLBACK_COMPLETE: ["The following resource(s) failed to create: [NodeGroup]. . Rollback requested by user." "The requested configuration is currently not supported. Please check the documentation for supported configurations. Launching EC2 instance failed."]
