### ISSUE TITLE
Upgrade provider snapshots to v2.4.0 of provider when released

### ISSUE THREAD

**Issue by rquitales** [pulumi/pulumi-eks#1145]
### What happened?

#1136 updated the kubeconfig args to ensure that the awscli always outputs in JSON format. We'll need to update our baseline provider snapshots to account for this as our snapshot tests will always fail.

The next minor release will also contain a few other diffs related to addons, so we'll batch these updates into a single minor release to minimize state updates for the user.

In the longterm, we'd want to ignore update diffs, but error on replace diffs for scenarios like this.

### Example

-

### Output of `pulumi about`

-

### Additional context

-

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
Self-tagging @t0yv0
