### ISSUE TITLE
ManagedNodeGroup should be able to specify an AMI ID override

### ISSUE THREAD

**Issue by rquitales** [pulumi/pulumi-eks#1167]
## Issue details

Currently, the ManagedNodeGroup resource only allows an `amiType` to be defined. We should also expose `amiId` to allow users to specify specific AMIs they would like to use, and allow them to decide when they update an AMI.

### Affected area/feature

Surfaced in: #https://github.com/pulumi/pulumi-eks/pull/1166#discussion_r1613659041

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/home/issues/3558

**Comment by flostadler** [comment]
This was implemented as part of https://github.com/pulumi/pulumi-eks/pull/1339 and will land in EKS v3

**Comment by flostadler** [comment]
This is now released in the newest major version: https://github.com/pulumi/pulumi-eks/releases/tag/v3.0.0
