### ISSUE TITLE
`instanceRole` still created when `skipDefaultNodeGroup` is enabled.

### ISSUE THREAD

**Issue by ringods** [pulumi/pulumi-eks#1176]
### What happened?

Customer reports he doesn't pass an `instanceRole` or `instanceRoles` because he enabled `skipDefaultNodeGroup` (actually the `skip_default_node_group` in the Python SDK). They don't want our code to still create an instance role.

### Example

Role created:

https://github.com/pulumi/pulumi-eks/blob/161e7af6803b58fea43ffdc3c6f9ee85cf658134/nodejs/eks/cluster.ts#L782-L802

Profile skipped due to `skipDefaultNodeGroup`:

https://github.com/pulumi/pulumi-eks/blob/161e7af6803b58fea43ffdc3c6f9ee85cf658134/nodejs/eks/cluster.ts#L822-L830

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by flostadler** [comment]
One workaround is setting the `instance_roles` parameter to an empty array:
```
from pulumi_aws import s3
import pulumi_eks as eks

cluster2 = eks.Cluster('eks-cluster', instance_roles=[])
```

I'd argue that this is not really intuitive, but removing that role now when `skipDefaultNodeGroup` is true would be a breaking change because some users might use the role through the `instanceRoles` output.

**Comment by flostadler** [comment]
We could add an additional flag `skipInstanceRole`, but this would add clutter to the API surface of the cluster. I'd rather take this small enhancement with the next major release

**Comment by flostadler** [comment]
We've addressed this as part of https://github.com/pulumi/pulumi-eks/pull/1411. This will be released with EKS v3

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/home/issues/3558

**Comment by flostadler** [comment]
This is fixed in the latest major release https://github.com/pulumi/pulumi-eks/releases/tag/v3.0.0
