### ISSUE TITLE
Generate Node SDK using the standard codegen tooling

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-eks#1184]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently this provider is special in that TypeScript/node users access it directly in-process as opposed to going through the multi-language component process boundary; one consequence here is that node users are not interacting with the SDK generated by a standard node Codegen.

TO reduce maintenance and errors in the Node SDK for maintainers it will be very helpful to bring Node to parity with other languages and use standard tooling. As things stand this is probably going to result in a few breaking changes which we need to catalog.

**Comment by rquitales** [comment]
+1 this would be nice for maintainers, and users to have parity across all languages. I believe that this wasn't implemented when we schematized this Provider as there were some critical user journeys within the ts/js package that would break for existing users if we had schamatized them too.

**Comment by t0yv0** [comment]
Looks like this issue duplicates https://github.com/pulumi/pulumi-eks/issues/603
