### ISSUE TITLE
Error installing EKS Provider

### ISSUE THREAD

**Issue by mchristen** [pulumi/pulumi-eks#1189]
### What happened?

I tried to run pulumi up using this action and I get an error preventing it from working.

```
 error: could not load plugin for eks provider 'urn:pulumi:Cinder-Dev::cinder_app::pulumi:providers:eks::default': Could not automatically download and install resource plugin 'pulumi-resource-eks', install the plugin using `pulumi plugin install resource eks`.
  Underlying error: 403 HTTP error fetching plugin from https://api.github.com/repos/pulumi/pulumi-eks/releases/latest
```

This worked before and stopped working this morning.

### Expected Behavior

It to work.

### Steps to reproduce

1. Use EKS provider
2. Deploy via Github Actions

### Output of `pulumi about`

```
pulumi about
CLI          
Version      3.53.1
Go Version   go1.19.5
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.26.0
aws         5.16.2
aws-native  0.46.0
awsx        1.0.1
cloudflare  4.15.0
command     0.7.0
docker      3.6.1
eks         1.0.1
kubernetes  3.23.1
nodejs      unknown
random      4.8.2
tls         4.6.1

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

<removed for privacy>

Dependencies:
NAME                    VERSION
@pulumi/cloudflare      4.15.0
@pulumi/command         0.7.0
@pulumi/tls             4.6.1
ava                     5.1.1
@pulumi/aws-native      0.46.0
@types/node             17.0.45
@pulumi/eks             1.0.1
@pulumi/pulumi          3.51.0
@pulumi/aws             5.26.0
@pulumi/awsx            1.0.1
@pulumi/kubernetes      3.23.1
@pulumi/random          4.8.2
@tsconfig/recommended   1.0.1
subnet-cidr-calculator  1.0.12
typescript              4.9.4
@aws-sdk/client-ec2     3.245.0

Pulumi locates its logs in /tmp by default
```

**Comment by justinvp** [comment]
In https://github.com/pulumi/pulumi-eks/issues/1125, Fraser [mentions](https://github.com/pulumi/pulumi-eks/issues/1125#issuecomment-2057008747):

> 2. The typescript SDK for eks isn't setting the provider version when it should be.

[And](https://github.com/pulumi/pulumi-eks/issues/1125#issuecomment-2057437883):

> Nope the issue looks to be that the SDK isn't sending a version at runtime. Thus why the user is seeing a diff for `pulumi:providers:eks (default)` rather than something like `pulumi:providers:eks (default_1_0_4)`.
> 
> Something in the SDK is trying to do a custom resource or remote component resource registration and not setting `ResourceOptions.Version` in that request. The engine is then falling back to its standard logic of "no version given, go look up the latest version and use that".

That's almost definitely what's going on.

The `@pulumi/eks` NPM package is an unusual package. Originally, we shipped `@pulumi/eks` for Node.js only. The implementation is written in TypeScript and it was just a set of regular components that could be used from other Node.js Pulumi projects.

Then we schematized it and made it available as a component package, exposing the functionality to the other languages, using the same TypeScript implementation as the implementation of the MLCs in the component package.

The `@pulumi/eks` npm package isn't actually exposing those MLCs that the other language SDKs expose. It remains the same SDK as it always has been, a pure TypeScript library that isn't generated from the schema.

But it does now depend on the `pulumi-resource-eks` plugin for a couple CustomResources that are implemented in the plugin. (These were originally dynamic provider resources, but those did not work with the MLCs, so they were converted into regular CustomResources provided by the plugin containing the MLCs. This was done in https://github.com/pulumi/pulumi-eks/pull/458). The custom resources are:

- https://github.com/pulumi/pulumi-eks/blob/master/nodejs/eks/cni.ts
- https://github.com/pulumi/pulumi-eks/blob/master/nodejs/eks/randomSuffix.ts

And indeed, we are not specifying the version for these, which would explain `pulumi:providers:eks (default)`

The fix will be to pass along the version for these like we do in generated SDKs, e.g.:

https://github.com/pulumi/pulumi-random/blob/ecd3b79bb8642b4aad5ec80b5b88be14f6cf8f26/sdk/nodejs/randomPet.ts#L102

```typescript
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(RandomPet.__pulumiType, name, resourceInputs, opts);
```

https://github.com/pulumi/pulumi-random/blob/ecd3b79bb8642b4aad5ec80b5b88be14f6cf8f26/sdk/nodejs/utilities.ts#L44-L57

```typescript
function getVersion(): string {
    let version = require('./package.json').version;
    // Node allows for the version to be prefixed by a "v", while semver doesn't.
    // If there is a v, strip it off.
    if (version.indexOf('v') === 0) {
        version = version.slice(1);
    }
    return version;
}

/** @internal */
export function resourceOptsDefaults(): any {
    return { version: getVersion() };
}
```
