### ISSUE TITLE
Implement tags for the roles: eksClusterRole and instanceRole

### ISSUE THREAD

**Issue by metral** [pulumi/pulumi-eks#119]
In previews, adding tags to roles is triggering a replace of an existing cluster and LaunchConfig since the respective role `.arns` used by each on updates is perceived to change, when it practice it does not.

Marking the `.arns` as a `stable` property ([#2688](https://github.com/pulumi/pulumi/issues/2688)) is required to tag the roles, such that existing clusters could be tagged without replacing the cluster and LaunchConfig.

**Comment by metral** [comment]
Closed with #122

**Comment by flostadler** [comment]
Closing out - the way this works has changed since this was opened, and this ask has also not come up again in the last 2+ years.
