### ISSUE TITLE
Node unable to be created with empty tag value

### ISSUE THREAD

**Issue by RagunathAnbarasu** [pulumi/pulumi-eks#1204]
### What happened?

I am deploying eks cluster with pulumi python.

Module versions:
- arpeggio-2.0.2 
- attrs-23.2.0 
- boto3-1.34.129 
- botocore-1.34.129 
- certifi-2024.6.2 
- charset-normalizer-3.3.2 
- dill-0.3.8 
- grpcio-1.60.1 
- idna-3.7 
- jmespath-1.0.1 
- parver-0.5 
- protobuf-4.25.3 
- pulumi-3.120.0 
- pulumi-docker-4.5.4 
- pulumi-kubernetes-4.13.1 
- pulumi_aws-6.41.0 
- pulumi_awsx-2.12.1 
- pulumi_eks-2.7.1 
- python-dateutil-2.9.0.post0 
- pyyaml-6.0.1 
- requests-2.32.3 
- ruamel.yaml.clib-0.2.8 
- ruamel_yaml-0.18.6 
- s3transfer-0.10.1 
- semver-2.13.0 
- six-1.16.0 
- typing-extensions-4.12.2

I am attaching tags to the resources, and one tag has empty string("") value.
Pulumi python is unable to create the EKS Node wth empty string("") as tag value.

### Example

    cluster = eks.Cluster("example_cluster_name",
        vpc_id = example_vpc_id,
        name = example_eks_cluster_name,
        tags = {"tag1" : "value1","tag2" : "value2","tag3" : "value3","tag4" : ""},
        public_subnet_ids=example_public_subnets,
        private_subnet_ids=example_private_subnets,
        create_oidc_provider=True,
        node_associate_public_ip_address = False)

### Output of `pulumi about`

+  aws:cloudformation:Stack example-nodes creating (0s)
@ updating.....
 +  aws:cloudformation:Stack example-nodes creating (1s) error: 1 error occurred:
 +  aws:cloudformation:Stack example-nodes **creating failed** error: 1 error occurred:
 +  pulumi:pulumi:Stack example-cluster creating (734s) error: update failed
 +  eks:index:Cluster example created
 +  pulumi:pulumi:Stack example-cluster **creating failed (734s)** 1 error; 12 messages
Diagnostics:
  aws:cloudformation:Stack (example-nodes):
    error: 1 error occurred:
    	* creating CloudFormation Stack (example-cluster): operation error CloudFormation: CreateStack, https response error StatusCode: 400, RequestID: 87350b-252140dedc74, api error ValidationError: 1 validation error detected: Value '' at 'tags.8.member.value' failed to satisfy constraint: Member must have length greater than or equal to 1
  pulumi:pulumi:Stack (example-cluster):
    Downloading provider: awsx
    Downloading provider: aws
    Downloading provider: aws
    Downloading provider: eks
    Downloading provider: kubernetes
    error: update failed

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment]
Hi @RagunathAnbarasu the issue you are reporting comes from AWS. They are validating to ensure tag values cannot be empty. Since this is expected behaviour of AWS, I don't think there is anything we can do on our side to address this - you'll need to update your tag values to not be empty. Please let me know if I'm overlooking something.
