### ISSUE TITLE
Create the default `VpcCni` after configuring cluster access

### ISSUE THREAD

**Issue by ringods** [pulumi/pulumi-eks#1216]
### What happened?

Customer creates an `eks.Cluster` using the `authentication_mode = eks.AuthenticationMode.API` (Python), which maps to using the new AWS access entries method which AWS advocates. The customer reports that they need 2 `pulumi up` runs before everything is succesfully deployed.

Our code has the creation of the default `VpcCni` component before any access is configured:

`VpcCni` creation lines 767-776:
https://github.com/pulumi/pulumi-eks/blob/0fa2f99c42e1c740c6d59f0bf266e9af2905d4cf/nodejs/eks/cluster.ts#L767-L776

`CONFIG_MAP` or `API` based cluster access configuration lines 778-902:
https://github.com/pulumi/pulumi-eks/blob/0fa2f99c42e1c740c6d59f0bf266e9af2905d4cf/nodejs/eks/cluster.ts#L778-L902

The order of these should be reversed and the proper `dependsOn` should be added so the access resources are fully deployed before the `VpcCni` is deployed.

### Example

Work in progress. Will update later.

### Output of `pulumi about`

```
pulumi about
CLI          
Version      3.121.0
Go Version   go1.22.4
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  aws         6.41.0
resource  awsx        2.12.3
resource  docker      4.5.4
resource  eks         2.7.1
resource  kubernetes  4.13.1
language  python      unknown

Host     
OS       darwin
Version  14.5
Arch     arm64

This project is written in python: executable='/Users/ringods/Projects/pulumi-customers/customer-engineering/customer-support/5423/.venv/bin/python' version='3.12.4'

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/v-ringo-pulumi-corp
User           v-ringo-pulumi-corp
Organizations  v-ringo-pulumi-corp, team-ce
Token type     personal

Dependencies:
NAME         VERSION
pip          24.0
pulumi_awsx  2.12.3
pulumi_eks   2.7.1
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by flostadler** [comment]
Yikes, sorry that they're running into this.
I'm trying to understand this better, the IAM principal creating the cluster should get admin permissions by default, are they by any chance setting `providerCredentialOpts` to a different ARN?

But I agree, we'll need to fixer the ordering here nevertheless.

As a workaround they could try using the VPC CNI addon instead. That one doesn't depend on having cluster access and is installed using AWS APIs.

**Comment by flostadler** [comment]
@ringods did you get some more information or a reproduction for this?
