### ISSUE TITLE
Cannot specify Managed Node Group DiskSize when a launch template is created

### ISSUE THREAD

**Issue by JustASquid** [pulumi/pulumi-eks#1228]
### What happened?

If you invoke any of the `ManagedNodeGroup` options that result in a custom launch template being created, disk size cannot be set, as AWS expects the disk size to be set on the launch template, not the original request.

### Example

See relevant PR

### Output of `pulumi about`

Latest

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by flostadler** [comment]
Sorry you're running into this @JustASquid. I saw you already started working on a PR, thanks a lot for that!
Let me know if you have any questions or need help getting it over the finish line

**Comment by flostadler** [comment]
@justasquid thanks again for your contribution! This is now released in [v2.7.9](https://github.com/pulumi/pulumi-eks/releases/tag/v2.7.9)
