### ISSUE TITLE
nodeSecurityGroupTags is not being applied when provided in a NodeGroup

### ISSUE THREAD

**Issue by metral** [pulumi/pulumi-eks#125]
Due to the assumed (but forgotten) dep on #121, which is turning out to not be a good path forward due to its disruptiveness, PR #122 intro'd the shift over to specifying the `nodeSecurityGroupTags` in the `NodeGroup` class only, instead of also the `Cluster` class for ease-of-use, and compartmentalization of code & config.

Given that #122 required the `nodeSecurityTags` be provided in the `NodeGroup` class, in practice the security group is being created in the `Cluster` class before the `NodeGroup` class, therefore any tags the user provides in `NodeGroup` aren't even being considered.

The fix should be that `nodeSecurityTags` is an option in only the `Cluster` class and not in the `NodeGroup` class, where if the `Cluster` has `nodeSecurityGroupTags` provided, it will apply this to the `nodeSecurityGroup` it creates, and then passes along to the `NodeGroup` class.

If a user wants to set tags for the `nodeSecurityGroup` they're providing in the `NodeGroup`, they must do so at creation time of the secgroup, and before being used in the `NodeGroup` creation.

**Comment by lukehoban** [comment]
> If a user wants to set tags for the nodeSecurityGroup they're providing in the NodeGroup, they must do so at creation time of the secgroup, and before being used in the NodeGroup creation.

Note that users can also pass an explicit SecurityGroup argument into the NodeGroup constructor, and can apply any tags to that manually.  So I believe technically there is a workaround for any scenario users might want to achieve here.  Is that right?

**Comment by metral** [comment]
@lukehoban your mentioned work around is correct, and the intent of the statement quoted albeit I may have not gotten that across completely: any user passing in their own external nodeSecurityGroup into the NodeGroup constructor can manually tag the nodeSecurityGroup at its creation time, before its used in the NodeGroup - so you can tag it from this angle if needed too.
