### ISSUE TITLE
Add support for Security Groups for Pods and Network Policies

### ISSUE THREAD

**Issue by flostadler** [pulumi/pulumi-eks#1256]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently, the EKS provider maintains a fork of the VPC CNI manifest (v1.16.0). Internally we're shelling out to kubectl in order to configure vpc-cni on clusters. This is necessary because those resources are already existent on the clusters but need modifications to their config to achieve things like:
- Running a fully serverless cluster
- Configuring parameters of the VPC CNI

The VPC CNI component does not support configuring Security Groups for Pods and Network Policies. It's missing configuration parameters like:
- `POD_SECURITY_GROUP_ENFORCING_MODE`
- `NETWORK_POLICY_ENFORCING_MODE`

### Affected area/feature
- EKS networking

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/home/issues/3558

**Comment by flostadler** [comment]
This will be release in EKS v3
