### ISSUE TITLE
Use EKS Addon to manage kube-proxy and coredns

### ISSUE THREAD

**Issue by flostadler** [pulumi/pulumi-eks#1261]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Right now kube-proxy and coredns are self-managed. This has the drawback that you cannot keep those cluster components updated via pulumi.

Additionally, this requires us to do a complex process of shelling out to kubectl to patch the coredns deployment. This is required so coredns can run on fargate:
https://github.com/pulumi/pulumi-eks/blob/986c528a058381be989c382d38a2e74238c9502b/nodejs/eks/cluster.ts#L967-L1024

Instead of doing that, we can manage those components as EKS addons and configure them with the pulumi resource `aws.eks.Addon`.

E.g. for enabling coredns to run on Fargate we should set:
```
const example = new aws.eks.Addon("example", {
    clusterName: "mycluster",
    addonName: "coredns",
    ...
    configurationValues: JSON.stringify({
        computeType: "Fargate"
    })
};
```

**Comment by flostadler** [comment]
This will also solve https://github.com/pulumi/pulumi-eks/issues/1294

**Comment by corymhall** [comment]
merged into release branch
