### ISSUE TITLE
Defaulting the secgroups in-line rules to null creates empty secgroups on a cluster replacement

### ISSUE THREAD

**Issue by metral** [pulumi/pulumi-eks#127]
When repro'ing https://github.com/pulumi/pulumi-eks/issues/69#issuecomment-485060221 and successfully completing cluster replacement after adding more subnets, destroying the cluster results in the same errors as #69 for **all** of the rules belonging to and including the `nodeSecurityGroup`.

The cause is tied to defaulting the ingress and egress rules to `[]` during the update that replaces the cluster, which never ends up recreating the secgroup rules. Then on the destroy, when the stand-alone secgroup rules resources are attempted to be deleted, because the rules were already removed / null'd out from the secgroup, we're returned the `rule does not exist in the security group` errors.

The null default for ingress & egress was intro'd in #109 as a requirement to be able to successfully update the cluster from using in-line secgroup rules to standalone rules.

**Comment by naineel** [comment]
Just hit this myself..The security groups are left empty with ingress and egress rules removed
