### ISSUE TITLE
Allow all arguments in NodeGroupV2 to be `pulumi.Input`

### ISSUE THREAD

**Issue by Makeshift** [pulumi/pulumi-eks#1274]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I ran into an issue today when trying to create a NodeGroup whose labels and taints were not known initially and were therefore `pulumi.Output`'s. Unfortunately, the `labels` and `taints` args (and a few more) in the `NodeGroupV2` component are treated and typed as plain values, so it isn't possible to use potentially-unresolved values when creating them.

Please add support for `labels` and `taints` to be resolved from `pulumi.Output`.

### Affected area/feature

This component.

**Comment by t0yv0** [comment]
Thank you for trying to send a PR here! Unfortunately it's a little more involved. Our team will have a look at this when planning the next major release, possibly combined with  https://github.com/pulumi/pulumi-eks/issues/603

**Comment by t0yv0** [comment]
CC @flostadler

**Comment by flostadler** [comment]
We've addressed this as part of https://github.com/pulumi/pulumi-eks/pull/1415. This will be released with EKS v3

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/home/issues/3558
