### ISSUE TITLE
Timeout during `kubectl apply` while setting up CNI when creating an EKS cluster

### ISSUE THREAD

**Issue by ellismg** [pulumi/pulumi-eks#132]
Trying to deploy the very simple program in `README.md` to create a new EKS cluster failed for me initially, in our custom provider:

```
Diagnostics:
  pulumi:pulumi:Stack (kube-hackathon-dev):
    error: update failed
 
    Unable to connect to the server: dial tcp 52.10.93.28:443: i/o timeout
 
  pulumi-nodejs:dynamic:Resource (cluster-vpc-cni):
    error: Plan apply failed: Command failed: kubectl apply -f /tmp/tmp-21388dZIk0ROCSdl5.tmp
    Unable to connect to the server: dial tcp 52.10.93.28:443: i/o timeout
 
Resources:
    + 20 created
```

Running `pulumi up` again caused everything to work.   I do wonder if we should try to sniff the output from shelling out to kubectl in `applyVpcCniYaml` and if we see i/o timeout wait a tick and retry again?  I'm not really sure what level of retries kubectl itself is doing.

Low priority for sure, but might provide a nicer little bit of UX.

**Comment by lukehoban** [comment]
Dupe of https://github.com/pulumi/pulumi-eks/issues/65?

**Comment by ellismg** [comment]
Indeed!
