### ISSUE TITLE
eks.NodeGroupV2 does not randomize the suffix of the underlying Auto Scaling group

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-eks#1335]
### What happened?

Creating an eks.NodeGroupV2 does not randomize the suffix of the underlying Auto Scaling group. This makes tests harder because one test failure that fails to clean up leads to subsequent test failures conflicting on the actual Auto Scaling group name.  I wonder if this is also something of value to end users outside of test scenarios, as by default Pulumi works hard to avoid name conflicts. 

The example is taken from our tests (examples/tags/index.ts). 

```
const ng2 = new eks.NodeGroupV2("example-ng-tags-ng2", {
    cluster: cluster2,
    instanceType: "t3.medium",
    desiredCapacity: 1,
    minSize: 1,
    maxSize: 2,
    instanceProfile: instanceProfile0,
    labels: {"preemptible": "true"},
    taints: {
        "special": {
            value: "true",
            effect: "NoSchedule",
        },
    },
    autoScalingGroupTags: cluster2.core.cluster.name.apply(clusterName => ({
        "myAutoScalingGroupTag3": "true",
        "k8s.io/cluster-autoscaler/enabled": "true",
        [`k8s.io/cluster-autoscaler/${clusterName}`]: "true",
    }))
})
```

### Example

The relevant code is this I think:

```
    const asGroup = new aws.autoscaling.Group(
        name,
        {
            name: name,
```

https://github.com/pulumi/pulumi-eks/blob/master/nodejs/eks/nodegroup.ts#L1302

I think specifying name: name opts out of the AWS auto-naming feature which would otherwise kick in. 

### Output of `pulumi about`

N/A

### Additional context

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by flostadler** [comment]
Good find @t0yv0! Removing an explicit name should still re-use the name from state for existing resources, right?

**Comment by t0yv0** [comment]
Yes just checked this. Removing the explicit name enables auto-naming. However it does not rename existing resources. The provider upgrade is still a no-op.
