### ISSUE TITLE
Bump aws-k8s-cni to v1.5.0 when available

### ISSUE THREAD

**Issue by metral** [pulumi/pulumi-eks#135]
A [fix](https://github.com/aws/amazon-vpc-cni-k8s/pull/461) that aims to improve ENI Pod IP + CNI management, and failure + retry logic is slated for v1.5.0. Both seem like welcomed additions when up against general service timeouts.

**Comment by naveensrinivasan** [comment]
We would be interested in this. When is it likely to go in. Thanks

**Comment by metral** [comment]
We're currently waiting for it to be released: https://github.com/aws/amazon-vpc-cni-k8s/releases

**Comment by ellismg** [comment]
The 1.5.0 release happened earlier today.
