### ISSUE TITLE
Publish the configmap migration guide

### ISSUE THREAD

**Issue by flostadler** [pulumi/pulumi-eks#1350]
We created a guide for migrating away from the aws-auth ConfigMap. This guide should be published in the Pulumi docs: https://github.com/pulumi/pulumi-eks/blob/master/docs/authentication-mode-migration.md

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/home/issues/3558

**Comment by flostadler** [comment]
Done: https://www.pulumi.com/registry/packages/eks/how-to-guides/access-entries-migration/
