### ISSUE TITLE
Clean up after addons were introduced

### ISSUE THREAD

**Issue by flostadler** [pulumi/pulumi-eks#1369]
Once the addons for vpc-cni, coredns and kube-proxy are added we need to do some cleanup.

This involves:
- adding the enums introduced in https://github.com/pulumi/pulumi-eks/pull/1357 to the VPC CNI
- exposing `configurationValues` for coredns and kube-proxy
- removing kubectl from the provider

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/home/issues/3558
