### ISSUE TITLE
Creating two EKS clusters in the same program fails with duplicate URN issues

### ISSUE THREAD

**Issue by ellismg** [pulumi/pulumi-eks#137]
I tried to deploy the following program:

```
import * as eks from "@pulumi/eks";

const cluster1 = new eks.Cluster("cluster1");
const cluster2 = new eks.Cluster("cluster2");
```

Running `pulumi up` yields the following error:

```
Diagnostics:
  kubernetes:rbac.authorization.k8s.io:RoleBinding (kube-system/kubernetes-dashboard-minimal):
    error: Duplicate resource URN 'urn:pulumi:dev::eks-107::eks:index:Cluster$kubernetes:yaml:ConfigGroup$kubernetes:rbac.authorization.k8s.io/v1:RoleBinding::kube-system/kubernetes-dashboard-minimal'; try giving it a unique name
```

**Comment by lukehoban** [comment]
This is the same as https://github.com/pulumi/pulumi-kubernetes/issues/520, right?

**Comment by ggilmore** [comment]
I ran into this with `@pulumi/eks: 0.18.5`. Are there any updates / workarounds?

**Comment by lukehoban** [comment]
@ggilmore Which specific error are you getting?  If it's the same error related to `kubernetes-dashboard-minimal` then you can avoid this by turning off the dashboard in one or more of the clusters (and potentially deploying it separately from the Helm chart yourself if you do really need it).

```ts
    deployDashboard: false
```

**Comment by metral** [comment]
Assigning @lblackstone since this is an issue being tracked in https://github.com/pulumi/pulumi-kubernetes/issues/520

**Comment by lblackstone** [comment]
I'm going to close this out as it seems to be related to the add-on dashboard specifically. We're likely to deprecate the dashboard (#177) anyway, and it's possible to workaround this issue as Luke [pointed out](https://github.com/pulumi/pulumi-eks/issues/137#issuecomment-500062816).
