### ISSUE TITLE
EKS cluster creation does not handle assumed roles

### ISSUE THREAD

**Issue by igorshapiro** [pulumi/pulumi-eks#140]
Hi, trying to create an EKS cluster using a VPC (awsx) from the same stack. Here's the code:

```js
module.exports = function(vpc) {
  const allSubnetIds = pulumi.all([vpc.getSubnetIds('private'), vpc.getSubnetIds('public')])
    .apply(([private, public]) => private.concat(public))
  return new eks.Cluster('eks_cluster', {
    deployDashboard: true,
    desiredCapacity: 1,
    instanceType: aws.ec2.M5InstanceLarge,
    maxSize: 2,
    nodeRootVolumeSize: 100,
    subnetIds: allSubnetIds,
    vpcId: vpc.vpc.id
  })
}
```

Getting the following errors:

```
     Type                                  Name                 Status                  Info
     pulumi:pulumi:Stack                   account-dev          **failed**              2 errors; 16 messages
     └─ eks:index:Cluster                  eks_cluster                                  
 +      └─ pulumi-nodejs:dynamic:Resource  eks_cluster-vpc-cni  **creating failed**     1 error
 
Diagnostics:
  pulumi:pulumi:Stack (account-dev):
    Method handler checkConfig for /pulumirpc.ResourceProvider/CheckConfig expected but not provided
    Method handler diffConfig for /pulumirpc.ResourceProvider/DiffConfig expected but not provided
    unable to recognize "/var/folders/28/z072xy4d5970vkd6l3vb_r780000gn/T/tmp-32396RlquTqkLiKdX.tmp": Unauthorized
    unable to recognize "/var/folders/28/z072xy4d5970vkd6l3vb_r780000gn/T/tmp-32396RlquTqkLiKdX.tmp": Unauthorized
    unable to recognize "/var/folders/28/z072xy4d5970vkd6l3vb_r780000gn/T/tmp-32396RlquTqkLiKdX.tmp": Unauthorized
    unable to recognize "/var/folders/28/z072xy4d5970vkd6l3vb_r780000gn/T/tmp-32396RlquTqkLiKdX.tmp": Unauthorized
    unable to recognize "/var/folders/28/z072xy4d5970vkd6l3vb_r780000gn/T/tmp-32396RlquTqkLiKdX.tmp": Unauthorized
 
    (node:32400) ExperimentalWarning: queueMicrotask() is experimental.
    Error: invocation of aws:ec2/getSubnet:getSubnet returned an error: grpc: the client connection is closing
     ...

 
    Method handler checkConfig for /pulumirpc.ResourceProvider/CheckConfig expected but not provided
    Method handler diffConfig for /pulumirpc.ResourceProvider/DiffConfig expected but not provided
 
    error: Running program '/Users/igor/work/bootstrap/infra/pulumi/account' failed with an unhandled exception:
    error: Error: invocation of aws:ec2/getSubnet:getSubnet returned an error: grpc: the client connection is closing
        at monitor.invoke ...
 
  pulumi-nodejs:dynamic:Resource (eks_cluster-vpc-cni):
    error: Plan apply failed: Command failed: kubectl apply -f /var/folders/28/z072xy4d5970vkd6l3vb_r780000gn/T/tmp-32396RlquTqkLiKdX.tmp
    unable to recognize "/var/folders/28/z072xy4d5970vkd6l3vb_r780000gn/T/tmp-32396RlquTqkLiKdX.tmp": Unauthorized
    unable to recognize "/var/folders/28/z072xy4d5970vkd6l3vb_r780000gn/T/tmp-32396RlquTqkLiKdX.tmp": Unauthorized
    unable to recognize "/var/folders/28/z072xy4d5970vkd6l3vb_r780000gn/T/tmp-32396RlquTqkLiKdX.tmp": Unauthorized
    unable to recognize "/var/folders/28/z072xy4d5970vkd6l3vb_r780000gn/T/tmp-32396RlquTqkLiKdX.tmp": Unauthorized
    unable to recognize "/var/folders/28/z072xy4d5970vkd6l3vb_r780000gn/T/tmp-32396RlquTqkLiKdX.tmp": Unauthorized
```

EKS package version: 0.17.0
AWSX version: 0.17.0

**Comment by casey-robertson** [comment]
Ran into this too and spun a lot of cycles - mostly due to ignorance on AWS cli tooling.  The pulumi program would use the defined profile however at the point it was trying to apply the temp .yaml files it was failing and I discovered it was using the root AssumeRole account which maps to my AD user which has no permissions except to assume roles that DO have permissions.  Once I set my $AWS_PROFILE to the right context cluster creation proceeded without issue.

**Comment by casey-robertson** [comment]
@d-nishi @igorshapiro if you set that env var, does it work around the issue?

**Comment by d-nishi** [comment]
@casey-robertson and I worked on his environment and we realized that if the AWS CLI config is set correctly, then setting pulumi config may not be needed for now.

@igorshapiro will be great if you can test and report back so we can continue our cred set-up for this use case.

**Comment by mazamats** [comment]
From the EKS docs `When you create an Amazon EKS cluster, the IAM entity user or role, such as a federated user that creates the cluster, is automatically granted system:masters permissions in the cluster's RBAC configuration. To grant additional AWS users or roles the ability to interact with your cluster, you must edit the aws-auth ConfigMap within Kubernetes.`

So, only the AWS user that created the cluster is able to access it initially.

You can specify a role through `eks.Cluster.roleMappings`, but the kubeconfig has

If I create an EKS cluster within a Pulumi stack, my coworker with a different AWS account cannot refresh the resources that are deployed with the default `kubeconfig`. Additional arguments need to be added to ensure that other AWS entities can use the cluster provider.

**Comment by metral** [comment]
Added in https://github.com/pulumi/pulumi-eks/pull/205
