### ISSUE TITLE
java.lang.IllegalArgumentException: '@Import com.pulumi.aws.eks.ClusterArgs.roleArn' is required but was not given a value

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-eks#1402]
### What happened?

Getting this problem on pulumi up on the 3.x testing:

```
java.lang.IllegalArgumentException: '@Import com.pulumi.aws.eks.ClusterArgs.roleArn' is required but was not given a value 
```

With the latest alpha:

```
    <dependencies>
        <dependency>
            <groupId>com.pulumi</groupId>
            <artifactId>pulumi</artifactId>
            <version>(,1.0]</version>
        </dependency>
        <dependency>
            <groupId>com.pulumi</groupId>
            <artifactId>aws</artifactId>
            <version>(6.0.2,6.99]</version>
        </dependency>
        <dependency>
            <groupId>com.pulumi</groupId>
            <artifactId>eks</artifactId>
            <version>3.0.0-alpha.7</version>
        </dependency>
    </dependencies>
```

This is unexpected, ClusterArgs does not even have roleArn. Wondering if something in Java SDK generation is going awry here. 

### Example

```java

package myproject;

import com.pulumi.Pulumi;
import com.pulumi.core.Output;
import com.pulumi.aws.s3.Bucket;
import com.pulumi.aws.eks.Cluster;

public class App {
    public static void main(String[] args) {
        Pulumi.run(ctx -> {
            var c = new Cluster("my-cluster");
            ctx.export("cid", c.id());
        });
    }
}
```

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
javagen version is behind, v0.9.8 vs 0.16.1, we need to automate having this up-to-date, likely fixing the issue here.

**Comment by flostadler** [comment]
`rolearn` is required for the underlying `aws.eks.Cluster`. The error is about that. See: https://www.pulumi.com/registry/packages/aws/api-docs/eks/cluster/#rolearn_java

**Comment by flostadler** [comment]
Fixed it with [Fix output of default node group referring to autoscalingGroupName #1410](https://github.com/pulumi/pulumi-eks/pull/1410). Release is currently running
