### ISSUE TITLE
Default Configuration results in "Your current IAM principal doesn't have access to Kubernetes objects on this cluster."

### ISSUE THREAD

**Issue by chrisvander** [pulumi/pulumi-eks#1460]
### What happened?

Using a default configuration for EKS, like
```ts
const cluster = new eks.Cluster("cluster", {
  name: "cluster-dev",
  vpcId: vpc.vpcId,
  subnetIds: vpc.privateSubnetIds,
  createOidcProvider: true,
  authenticationMode: "API_AND_CONFIG_MAP",
  instanceType: "t3.large",
  desiredCapacity: 2,
  minSize: 1,
  maxSize: 4,
})
```

`pulumi-eks` is creating a cluster which does not have any default node groups configured (in the UI at least) and the error "Your current IAM principal doesn't have access to Kubernetes objects on this cluster" despite an AccessEntry resource being created.

### Example

Create a cluster like the above.

### Output of `pulumi about`

```
CLI
Version      3.137.0
Go Version   go1.23.2
Go Compiler  gc

Plugins
KIND      NAME         VERSION
resource  auth0        3.8.1
resource  aws          6.56.1
resource  awsx         2.16.1
resource  cloudflare   5.41.0
resource  eks          3.0.0
resource  kubernetes   4.18.2
language  nodejs       unknown
resource  onepassword  1.1.3
resource  random       4.16.7
resource  std          1.7.3

Host
OS       darwin
Version  15.0
Arch     arm64

This project is written in nodejs: executable='/Users/chrisvanderloo/.local/share/mise/installs/node/18/bin/node' version='v18.20.4'
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by chrisvander** [comment]
One thing I'll note: I am using SSO through Identity Center to log in. I'm noticing that the access entries (when generated by Terraform) are different than the `pulumi-eks` provider.

**Comment by chrisvander** [comment]
Ah, since I am creating it through the OIDC provider, I guess I can't see the nodes. That makes for a simpler issue. I manually created the role so I can see all of that - but how can I attach additional instance roles when using `aws.iam.getRoles`?

For example: ```ts
const reservedSSORoles = aws.iam.getRoles({
  nameRegex: "AWSReservedSSO_AdministratorAccess.*",
  pathPrefix: "/aws-reserved/sso.amazonaws.com/",
})
```
I can't use that directly with the `instanceRoles` parameter, as it's expecting an `aws.iam.Role` object.

**Comment by chrisvander** [comment]
Never mind, I got it, I just used `aws.eks.AccessEntry` for my SSO login.

```ts
const reservedSSORoles = aws.iam.getRoles({
  nameRegex: "AWSReservedSSO_AdministratorAccess.*",
  pathPrefix: "/aws-reserved/sso.amazonaws.com/",
})
reservedSSORoles.then((roles) =>
  roles.arns.map(
    (principalArn) =>
      new aws.eks.AccessEntry("bluefin-access-entry", {
        clusterName: cluster.eksCluster.name,
        principalArn,
      }),
  ),
)
```

Thanks, my misunderstanding.

**Comment by flostadler** [comment]
Nice, happy to hear it's working!

You can also use the `accessEntries` parameter of the cluster component to create the access entries: https://www.pulumi.com/registry/packages/eks/api-docs/cluster/#accessentries_nodejs
