### ISSUE TITLE
InvalidParameterException: You cannot specify an AMI Type other than CUSTOM, when specifying an image id in your launch template

### ISSUE THREAD

**Issue by victoroloan** [pulumi/pulumi-eks#1463]
### What happened?

Encountered an error stating that an AMI Type other than CUSTOM cannot be specified when providing an image ID. However, no launch template has been set in the configuration.

Error message: ` InvalidParameterException: You cannot specify an AMI Type other than CUSTOM, when specifying an image id in your launch template` 

### Example

```
  const managedNodeGroup =  new eks.ManagedNodeGroup(
    "nodegroup-28102024",
    {
      cluster: cluster,
      nodeGroupName:  "managed-ng-28102024",
      amiType: "AL2023_ARM_64_STANDARD",
      instanceTypes: ["t3.large"],
      diskSize: 50,
      kubeletExtraArgs: "--max-pods=110", 
      scalingConfig: {
        desiredSize: 2,
        minSize: 1,
        maxSize: 3,
      },
    },
  );
```

### Output of `pulumi about`

```
CLI          
Version      3.137.0
Go Version   go1.23.2
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  aws         6.45.0
resource  awsx        2.13.0
resource  eks         3.0.0
resource  kubernetes  4.17.1
language  nodejs      unknown
resource  random      4.16.3

Host     
OS       darwin
Version  15.0.1
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/bin/node' version='v20.18.0'

Backend        
Name           myhostname
URL            s3://mys3bcuket
User           myuser
Organizations  
Token type     personal

```

### Additional context

I encountered [this issue - #1779](https://github.com/pulumi/pulumi-eks/issues/1179) when using pulumi/eks version 2.7.8. I attempted to update to version 3.0 to resolve it, but then encountered the issue described above

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by flostadler** [comment]
@victoroloan  The fix was just merged in. I'll kick off a release right away
