### ISSUE TITLE
'defaultNodeGroupInstanceRole' has a problem: Value for unconfigurable attribute. Can't configure a value for "type"

### ISSUE THREAD

**Issue by bencmbrook** [pulumi/pulumi-eks#1479]
### What happened?

```
Diagnostics:
  aws:eks:AccessEntry (example-cluster-defaultNodeGroupInstanceRole):
    error: aws:eks/accessEntry:AccessEntry resource 'example-cluster-defaultNodeGroupInstanceRole' has a problem: Value for unconfigurable attribute. Can't configure a value for "type": its value will be decided automatically based on the result of applying this configuration.. Examine values at 'example-cluster-defaultNodeGroupInstanceRole.type'.

```

### Example

```ts
import * as eks from '@pulumi/eks';

const cluster = new eks.Cluster(
  'example-cluster',
  {
    authenticationMode: eks.AuthenticationMode.Api, // same error with `ApiAndConfigMap`
  },
  { provider },
);
```

### Output of `pulumi about`

```
CLI          
Version      3.38.0
Go Version   go1.19
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       debian
Version  11.7
Arch     x86_64

This project is written in nodejs: executable='/usr/local/share/nvm/versions/node/v18.20.3/bin/node' version='v18.20.3'

Backend        
Name           fv-az1485-849
URL            s3://dev-pulumi-state
User           root
Organizations  
```

`pulumi about` didn't grab the plugins but here:

resource aws v6.18.2
resource eks v3.0.1
resource kubernetes v4.15.0

### Additional context

It seems like this is coming from here:

https://github.com/pulumi/pulumi-eks/blob/00353a9d5579be4e1b7c227af7753663b6b36a32/nodejs/eks/cluster.ts#L896-L899

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by flostadler** [comment]
Hey, I'm very sorry you're running into this!

I just tried reproducing this error on my end with the example you provided, but it's deploying fine.

These are the versions I'm using:
```
CLI
Version      3.136.1
Go Version   go1.23.2
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  aws         6.58.0
resource  awsx        2.17.0
resource  docker      4.5.7
resource  docker      3.6.1
resource  eks         3.0.1
resource  kubernetes  4.18.3
language  nodejs      3.136.1-dev.0

Dependencies:
NAME            VERSION
@pulumi/awsx    2.17.0
@pulumi/eks     3.0.1
@pulumi/pulumi  3.138.0
@types/node     18.19.64
typescript      5.6.3
```

I see that you're using an older version of pulumi. Could you try updating both the pulumi CLI as well as your `@pulumi/pulumi` node dependency?

**Comment by bencmbrook** [comment]
Thank you @flostadler - that's helpful to know this is not universal. It seems like this [class of errors](https://stackoverflow.com/a/71078463) tends to come from version mismatches, so you're probably correct. 

I'll see if we can upgrade, but it may take a few days since there's a large remote state, so I want to make sure we can safely upgrade across the board.

**Comment by flostadler** [comment]
Sounds good, let me know how it goes!
