### ISSUE TITLE
VpcCni state includes absolute path to YAML, leading to unnecessary brittleness and opaque changes

### ISSUE THREAD

**Issue by MerelyAPseudonym** [pulumi/pulumi-eks#149]
I can run `pulumi preview` on one machine and see that there will be no changes, but if I move the project to a different directory and run `pulumi preview` again, I see that Pulumi wants to update a `pulumi-nodejs:dynamic:Resource` but it can’t explain any more about that change. By inspecting the output of `pulumi preview --json`, I can see that the only changes are in the (serialized) content of `__provider`, and the only changes there are in the paths to the CNI YAML:

```diff
--- provider1.js	2019-06-06 16:22:34.771169181 -0400
+++ provider2.js	2019-06-06 16:22:32.715455152 -0400
@@ -80,7 +80,7 @@
 
 function __f3() {
     return (function() {
-        with({ applyVpcCniYaml: __applyVpcCniYaml, yamlPath: "/tmp/demo1/node_modules/@pulumi/eks/cni/aws-k8s-cni.yaml", crypto: require("crypto") }) {
+        with({ applyVpcCniYaml: __applyVpcCniYaml, yamlPath: "/tmp/demo2/node_modules/@pulumi/eks/cni/aws-k8s-cni.yaml", crypto: require("crypto") }) {
 
             return (inputs) => {
                 applyVpcCniYaml(yamlPath, inputs);
@@ -93,7 +93,7 @@
 
 function __f4() {
     return (function() {
-        with({ applyVpcCniYaml: __applyVpcCniYaml, yamlPath: "/tmp/demo1/node_modules/@pulumi/eks/cni/aws-k8s-cni.yaml" }) {
+        with({ applyVpcCniYaml: __applyVpcCniYaml, yamlPath: "/tmp/demo2/node_modules/@pulumi/eks/cni/aws-k8s-cni.yaml" }) {
 
             return (id, state, inputs) => {
                 applyVpcCniYaml(yamlPath, inputs);
```

Tying the Pulumi state to file paths on a deployment machine does not seem desirable or necessary.

**Comment by MerelyAPseudonym** [comment]
Also, note that the explanation from Pulumi is very sparse:

```sh-session
$ pulumi preview
```

I wouldn’t be surprised if it

**Comment by metral** [comment]
I believe I've run into something similar to this. I'll try to repro on my end.

> I wouldn’t be surprised if it’s difficult to be more informative with dynamic resources, though.

Right, there's definitely some aspects to dynamic providers, like the CNI, that make previewing lack info, compared to defined resources

**Comment by lukehoban** [comment]
@metral Note that if we fix https://github.com/pulumi/pulumi-eks/issues/160 we should be able to get rid of the dynamic provider here entirely - which will also fix this issue. I would be inclined to focus on #160 first if possible.
