### ISSUE TITLE
instanceRole is no longer automatically created when `skipDefaultNodeGroup: true`

### ISSUE THREAD

**Issue by bob-bins** [pulumi/pulumi-eks#1510]
### What happened?

After I upgraded to v3 of this package, `pulumi preview` looks to delete the instanceRole for my EKS clusters. This is a regression caused by the resolution of https://github.com/pulumi/pulumi-eks/issues/1176, in this PR https://github.com/pulumi/pulumi-eks/pull/1411.

My workaround is currently to set min/desired/max replicas for `nodeGroupOptions` to `0`, but since my org requires specific tags to exist for launch configs and ASGs, and since seeing the frequent AMI changes ruins one of our workflows, this regression is forcing me to add 33 lines of code that were not previously necessary.

Switching our cluster to use a new instanceRole managed outside this module requires a lot of work given that all node groups need to be completely recreated.

Can a boolean option like `createInstanceRole` be exposed so we can maintain backward-compatible behavior?

### Example

N/A

### Output of `pulumi about`

```
$ pulumi about
CLI          
Version      3.128.0
Go Version   go1.22.5
Go Compiler  gc

Plugins
KIND      NAME    VERSION
language  nodejs  unknown

Host     
OS       darwin
Version  14.5
Arch     arm64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by flostadler** [comment]
Hey @bob-bins, sorry this is causing you trouble!
As part of https://github.com/pulumi/pulumi-eks/issues/1176 we've took the decision to not create the default instance role if users disable the default node groups. Our assumption back then was that there's not a substantial need for this role when users opt out of the default node groups.

But given your inputs I can see this making an upgrade more painful than necessary! I'll track this as an enhancement and will try to get to it as soon as possible!

**Comment by flostadler** [comment]
@bob-bins I just merged the PR to introduce a flag for creating the instance role. The change will be released shortly
