### ISSUE TITLE
Is AMI  for OS: AL2023, GPU support: true, architecture: x86_64 missing?

### ISSUE THREAD

**Issue by shashiranjan84** [pulumi/pulumi-eks#1526]
### What happened?

I do not see any entry  for AL2023 GPU optimized AMI [here](https://github.com/pulumi/pulumi-eks/blob/master/nodejs/eks/ami.ts). But I do see AWS have optimized AMI for [Nvidia](https://docs.aws.amazon.com/eks/latest/userguide/retrieve-ami-id.html) 
 
![Image](https://github.com/user-attachments/assets/244148b7-dbcb-49ba-9234-e8a4ab86b7e2)

I am trying to update K8s version from 1.29 to 1.31 and also updated the Pulumi EKS from 2.2.1 to 3.4.0

### Example

```js
const cluster = new eks.Cluster(
      `${regionalNamespace}-cluster`,
      {
        name: `${regionalNamespace}`,
        version: '1.31',
        vpcId: ...,
        privateSubnetIds: ...
        publicSubnetIds: ...,
        enabledClusterLogTypes: ['api', 'audit', 'authenticator'],
        tags: projectTags,
        endpointPrivateAccess: true,
        endpointPublicAccess: true,
        nodeAssociatePublicIpAddress: false,
        providerCredentialOpts: {
          profileName: aws.config.profile,
        },
        roleMappings: [
          ...
        ],
        instanceType: 'g5.2xlarge',
        gpu: true,
        nodeRootVolumeSize: 200,
        ...,
      },
      { provider: ... },
    );
```
### Output of `pulumi about`
```sh
CLI          
Version      3.142.0
Go Version   go1.23.3
Go Compiler  gc

Host     
OS       debian
Version  11.7
Arch     x86_64

Backend        
Name           fv-az1490-728
URL            s3://staging-pulumi-state-io
User           root
Organizations  
Token type     personal
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by flostadler** [comment]
Hey @shashiranjan84, sorry you're running into this! AL2023 with GPU support was added to EKS after we've added AL2023 support to the provider.
I'll track this as an enhancement to add the missing AMI type. In the meantime you can provide the AMI ID to the node group component in order to use AL2023 with GPU support or alternatively use the Bottlerocket Operating System.

**Comment by shashiranjan84** [comment]
Thanks @flostadler . we deploy in multiple regions so was trying to avoid any hardcoding of AMI id.

**Comment by flostadler** [comment]
You do not have to hardcode the AMI id. You can retrieve the region specific AMI from SSM Parameter Store like this:
```
const ami = pulumi.interpolate`/aws/service/eks/optimized-ami/${cluster.eksCluster.version}/amazon-linux-2023/x86_64/nvidia/recommended/image_id`.apply(name =>
  aws.ssm.getParameter({ name }, { async: true })
).apply(result => result.value);
```

**Comment by flostadler** [comment]
AWS added two new gpu capable optimized AMIs for AL2023. One is for Nvidia based instances, the other is for Neuron based instances (`trn1`, `inf1`, etc.).

Adding support for the Nvidia based one is rather easy, but before adding Neuron support we'll need to extend the AMI selection to be instance type aware. So far it's only architecture aware.

**Comment by shashiranjan84** [comment]
> AWS added two new gpu capable optimized AMIs for AL2023. One is for Nvidia based instances, the other is for Neuron based instances (`trn1`, `inf1`, etc.).
> 
> Adding support for the Nvidia based one is rather easy, but before adding Neuron support we'll need to extend the AMI selection to be instance type aware. So far it's only architecture aware.

Makes sense

**Comment by shashiranjan84** [comment]
> You do not have to hardcode the AMI id. You can retrieve the region specific AMI from SSM Parameter Store like this:
> 
> ```
> const ami = pulumi.interpolate`/aws/service/eks/optimized-ami/${cluster.eksCluster.version}/amazon-linux-2023/x86_64/nvidia/recommended/image_id`.apply(name =>
>   aws.ssm.getParameter({ name }, { async: true })
> ).apply(result => result.value);
> ```

I was trying to switch to Al2300 GPU AMI but after updating I am not seeing any nodes. I was expecting it to be rolling update of the nodes but now I am seeing no nodes 

```js
const EKS_VERSION = '1.29';
const ami = pulumi.interpolate`/aws/service/eks/optimized-ami/${EKS_VERSION}/amazon-linux-2023/x86_64/nvidia/recommended/image_id`.apply((name) =>
      aws.ssm.getParameter({ name,  }, { async: true, provider: ... }),
    ).apply((result) => result.value);

const cluster = new eks.Cluster(
      `${regionalNamespace}-cluster`,
      {
        name: `${regionalNamespace}`,
        version: EKS_VERSION,
        vpcId: ...,
        privateSubnetIds: ...
        publicSubnetIds: ...,
        enabledClusterLogTypes: ['api', 'audit', 'authenticator'],
        tags: projectTags,
        endpointPrivateAccess: true,
        endpointPublicAccess: true,
        nodeAssociatePublicIpAddress: false,
        providerCredentialOpts: {
          profileName: aws.config.profile,
        },
        roleMappings: [
          ...
        ],
        instanceType: 'g5.2xlarge',
        // gpu: true,
       nodeAmiId: ami,
        nodeRootVolumeSize: 200,
        ...,
      },
      { provider: ... },
    );
```

![Image](https://github.com/user-attachments/assets/a5f083fa-2ff9-4ae9-9826-79566226c539)

**Comment by flostadler** [comment]
@shashiranjan84  the EKS provider 2.x.x does not support AL2023 and Bottlerocket. You'll need to upgrade to version 3 of the provider.

Self managed node groups (like the cluster default node group) require more careful handling to guarantee downtime-less updates generally. If possible, I'd recommend you to upgrade to either using managed node groups or EKS Auto Mode instead.

I'd recommend you to first upgrade to EKS provider version 3 following this guide: https://www.pulumi.com/registry/packages/eks/how-to-guides/v3-migration. It shouldn't replace your existing node groups if you set the `operatingSystem` to `AL2`.

**Comment by shashiranjan84** [comment]
After updating to EKS 3.5 and updating default node group(after setting AMI id), we seeing this error at end of deployment 

```
 Error: unknown resource type urn:pulumi:main.bob-infra.staging::bob-infra::eks:index:Cluster$eks:index:VpcCni::us-east-1-staging-bob-vpc-cni: Error: unknown resource type urn:pulumi:main.bob-infra.staging::bob-infra::eks:index:Cluster$eks:index:VpcCni::us-east-1-staging-bob-vpc-cni
```

**Comment by flostadler** [comment]
@shashiranjan84 can you please open a separate issue for this and include code and steps to reproduce this. Thanks a lot!

**Comment by shashiranjan84** [comment]
@flostadler I also notice when I create a managed node group with a amiID, worker node instance do not have same amiID. 

```
const EKS_VERSION = '1.30';
const ami = pulumi.interpolate`/aws/service/eks/optimized-ami/${EKS_VERSION}/amazon-linux-2023/x86_64/nvidia/recommended/image_id`.apply((name) =>
      aws.ssm.getParameter({ name,  }, { async: true, provider: ... }),
    ).apply((result) => result.value);

const cluster = new eks.Cluster(
      `${regionalNamespace}-cluster`,
      {
        name: `${regionalNamespace}`,
        version: EKS_VERSION,
        vpcId: ...,
        privateSubnetIds: ...
        publicSubnetIds: ...,
        enabledClusterLogTypes: ['api', 'audit', 'authenticator'],
        tags: projectTags,
        endpointPrivateAccess: true,
        endpointPublicAccess: true,
        nodeAssociatePublicIpAddress: false,
        providerCredentialOpts: {
          profileName: aws.config.profile,
        },
        roleMappings: [
          ...
        ],
        instanceType: 'g5.2xlarge',
        // gpu: true,
       nodeAmiId: ami,
        nodeRootVolumeSize: 200,
        ...,
      },
      { provider: ... },
    );

    new eks.ManagedNodeGroup(
      `${regionalNamespace}-ng`,
      {
        cluster,
        amiId:  ami,
        gpu: true,
        instanceTypes: ['g5.xlarge'],
        ignoreScalingChanges: true,
        scalingConfig: {
          minSize: 1,
          maxSize: 2,
          desiredSize: DESIRED_RESOURCE_COUNT[config.env].node.desiredCapacity,
        },
        diskSize: 200,
        nodeRole: cluster.instanceRoles[0],
        enableIMDSv2: true,
        labels: {
          'transcend.io/k8s_version': '1.31'
        },
        tags: {
          ...projectTags,
          'k8s.io/cluster-autoscaler/enabled': 'true',
          [`k8s.io/cluster-autoscaler/${regionalNamespace}`]: 'owned',
        },
      },
      { provider: MAIN_REGION_PROVIDERS[mainRegion] },
    );

```

Is that expected?

**Comment by flostadler** [comment]
@shashiranjan84 Only the nodes part of the managed node group will have that AMI ID. The nodes part of the default self-managed node group will have a different AMI ID.
If you see something different, please open another issue so we can dig into it. Thanks!

**Comment by shashiranjan84** [comment]
Here I am explicitly providing same node AMI ID for both self managed and managed node group assuming they will stack up with same GPU optimized AMI ID. Even when I hardcoded AMI id in managed node group, worked node in managed group was showing different AMI id, as if it completely ignoring AMI ID property

**Comment by flostadler** [comment]
FYI version [v3.6.0](https://github.com/pulumi/pulumi-eks/releases/tag/v3.6.0) was released with support for nvidia based GPUs for AL2023. I'm closing this issue for now and opened this one for adding Neuron support.

@shashiranjan84 I'll continue looking into the other issues you've opened, but you'll not have to need to use the AMI override anymore. The provider should now select the appropriate AMI for all instances with NVIDIA GPUs

**Comment by shashiranjan84** [comment]
Thanks a lot!

**Comment by shashiranjan84** [comment]
@flostadler this does not work for `us-east-region`

```
'us-east-1-staging-llmc-ng' has a problem: expected ami_type to be one of ["AL2_x86_64" "AL2_x86_64_GPU" "AL2_ARM_64" "CUSTOM" "BOTTLEROCKET_ARM_64" "BOTTLEROCKET_x86_64" "BOTTLEROCKET_ARM_64_NVIDIA" "BOTTLEROCKET_x86_64_NVIDIA" "WINDOWS_CORE_2019_x86_64" "WINDOWS_FULL_2019_x86_64" "WINDOWS_CORE_2022_x86_64" "WINDOWS_FULL_2022_x86_64"], got AL2023_x86_64_NVIDIA. Examine values at 'us-east-1-staging-llmc-ng.amiType'.
```
