### ISSUE TITLE
Heapster-dashboard integration broken out of the box

### ISSUE THREAD

**Issue by MerelyAPseudonym** [pulumi/pulumi-eks#155]
On a fresh EKS cluster with `deployDashboard: true` (as available [in this repo’s `heapster-broken` branch](https://github.com/MerelyAPseudonym/eks-pulumi-repro/tree/heapster-broken)) the “CPU usage” and “Memory usage” graphs are not visible.

I suspect the problem is related to <https://github.com/awslabs/amazon-eks-ami/issues/128>.

For what it’s worth, by following the advice in [one of the comments to the linked issue](https://github.com/awslabs/amazon-eks-ami/issues/128#issuecomment-450620004), I was able to get heapster working again in <https://github.com/MerelyAPseudonym/eks-pulumi-repro/commit/6effd13cef11a55ae6afd1a29fdaffeab01b4cdd>. (Security concerns might prevent that from being acceptable _default_ behavior, though.)

**Comment by lukehoban** [comment]
Interesting. It's not immediately clear that there is any robust solution to this on EKS.  Of the available "workarounds" none actually seems generally acceptable?
* https://github.com/awslabs/amazon-eks-ami/issues/128#issuecomment-450620004
* https://github.com/awslabs/amazon-eks-ami/issues/128#issuecomment-458928413
* https://github.com/awslabs/amazon-eks-ami/issues/128#issuecomment-463853081

Is there any clear answer on which (if any) workaround is generally acceptable here?

**Comment by metral** [comment]
You can about this in two ways:
- Re-enabling the port in the kubelet as suggested in https://github.com/awslabs/amazon-eks-ami/issues/128#issuecomment-46385308, or
- Target heapster as @MerelyAPseudonym points out in https://github.com/MerelyAPseudonym/eks-pulumi-repro/commit/6effd13cef11a55ae6afd1a29fdaffeab01b4cdd, to depend on the kubelet's port 10250

The difference in ports is:
* 10250 - the Kubelet HTTPS Server (requires auth, and one use to hit it: /metrics for prometheus)
* 10255 - read-only HTTP Server (w/ no auth) metadata API (one use case: /stats).

It makes sense from EKS' stand point to disable port 10255 to reduce leaking information without auth, and hitting 10250 from within the cluster with a ServiceAccount feels right; however, the use of 
`insecure=true` in `--source=kubernetes:https://kubernetes.default?useServiceAccount=true&kubeletHttps=true&kubeletPort=10250&insecure=true` should *not* be a default - this is only for testing purposes.

Instead something like this [setting](https://github.com/kubernetes-incubator/metrics-server/issues/131#issuecomment-418082375) in the metrics server should be the route used as I suspect using `InternalIP` gets around what I perceive are DNS + TLS cert SAN issues, which i believe is the main why `insecure=true` must be used in the first place.

Given how heapster is [deprecated](https://github.com/kubernetes/heapster), I don't have much of a good answer here seeing how the kube dashboard[ only works with heapster](https://docs.aws.amazon.com/eks/latest/userguide/dashboard-tutorial.html#deploy-dashboard) per EKS docs, and this [issue](https://github.com/kubernetes/dashboard/issues/2986) is open to move the kube dashboard to the metrics server.

@hausdorff @lblackstone thoughts?

**Comment by lukehoban** [comment]
Should we consider deprecating the `deployDahsboard` feature of the `@pulumi/eks` package?

It doesn't appear that Kubernetes or EKS takes supporting the Kubernetes Dashboard very seriously, and both generally recommend you do not use the dashboard.  It would still be possible for users to deploy it themselves via charts (assuming they could work through the problems above).

Thoughts?

**Comment by metral** [comment]
I'm in favor of deprecating the dashboard for the aforementioned reasons

**Comment by metral** [comment]
I'm closing this issue to track the separate tasks here:
- deprecate the kube-dashboard: https://github.com/pulumi/pulumi-eks/issues/177
- document an example of how to deploy the Helm chart: https://github.com/pulumi/pulumi-kubernetes/issues/600

Please let us know if you have any other questions or comments. Thanks!
