### ISSUE TITLE
I/O Timeout during creation

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi-eks#164]
I get `I/O timeouts` with moderate frequency when creating `eks.Cluster` from an empty stack when using https://github.com/pulumi/examples/tree/master/aws-ts-eks-hello-world.

Full `up` output - https://gist.github.com/clstokes/61f97bae09f02f1ec2e3b04c0ecaf915.

**Comment by lukehoban** [comment]
This is https://github.com/pulumi/pulumi-eks/issues/65 which will be fixed with https://github.com/pulumi/pulumi-eks/issues/160 (I assume we should dupe one of those to the other).
