### ISSUE TITLE
Adding in a missing role to a cluster, after its already up with a NodeGroup with the associated instanceProfile, does not properly update

### ISSUE THREAD

**Issue by metral** [pulumi/pulumi-eks#174]
Per @kennyjwilli: https://github.com/pulumi/pulumi-kubernetes/issues/578#issuecomment-503652497

Repro: https://gist.github.com/kennyjwilli/662ae731bd6cb102d1ca6310a36f93f6
- Run the repro by doing an update
- Edit the [cluster definition](https://gist.github.com/kennyjwilli/662ae731bd6cb102d1ca6310a36f93f6#file-index-ts-L34) to now include `instanceRole: role0`
- Run another update

**Comment by metral** [comment]
More info on repro from a fresh stack: https://github.com/pulumi/pulumi-kubernetes/issues/578#issuecomment-503712879

**Comment by metral** [comment]
I've tried to repro https://gist.github.com/kennyjwilli/662ae731bd6cb102d1ca6310a36f93f6 without the kube-dashboard code block to isolate things, and with no `role: instance0` set on the `eksCluster` for the initial update. The cluster comes up and no nodes exist, as expected.

Then I set `role:instance0` in the `eksCluster` and do another update and the nodes come up, are able to join, get ready, and the Pods are all running. By all accounts, inserting a role after the cluster is up does work, so I could not repro the missing role issue.

The errors linked in https://github.com/pulumi/pulumi-kubernetes/issues/578#issuecomment-503712879 were ultimately related to kube dashboard, not a missing role.

@kennyjwilli if you feel like this is still an on-going issue to add roles please let us know. If not, I'll close this out.

**Comment by lukehoban** [comment]
Closing this out for now - we can reopen if we get more details on a repro.
