### ISSUE TITLE
Deprecate the deployDashboard (kube-dashboard) from the Cluster class

### ISSUE THREAD

**Issue by metral** [pulumi/pulumi-eks#177]
See https://github.com/pulumi/pulumi-eks/issues/155#issuecomment-501932824

**Comment by metral** [comment]
Full output for a recent `pulumi/eks` CI run from today that hit this issue with Pulumi test debugging enabled: https://gist.github.com/metral/aa5ffa6dd07be202a0dd99eece2b71f2

**Comment by metral** [comment]
@lukehoban @ellismg 

For `feature/q3`, would deprecating the dashboard be defined as marking the option as `deprecated` to simply warn folks, or are we considering removing the option completely?

The former would create a window of time for users with the option enabled to move off of it. The latter would be in-line with our general consensus that we should remove this feature for its lack of community support and use. Do we want to do either or, or both?

**Comment by lukehoban** [comment]
Yes - we should have a (long) period of marking as deprecated. We don’t need to be in any rush to actually remove.
