### ISSUE TITLE
[proposal] Deprecate automated subnet assignment logic

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-eks#179]
See https://github.com/pulumi/pulumi-eks/pull/163#issuecomment-502838131

Rather than trying to infer subnet assignments from a possibly mixed bag of subnets, the proposal is to have users specify their intentions directly.

**Comment by metral** [comment]
@lblackstone Any updates to share on this one by chance?

**Comment by lblackstone** [comment]
No, haven't had a chance to circle back, and likely won't anytime soon.

**Comment by lukehoban** [comment]
I think we can probably leave this is as-is for now.   This has not be a source of any serious issues, and is to an extent well-aligned with how EKS itself documents it's interface.  If we see new issues related to this we can re-open the idea.
