### ISSUE TITLE
Create EFS filesystem which automatically mounts to pod in EKS cluster with no manual intervention required 

### ISSUE THREAD

**Issue by lee-baines** [pulumi/pulumi-eks#185]

**Comment by lee-baines** [comment]
Current issue is that when you deploy an EKS cluster and EFS filesystem, I have to manually create a file or directory on the filesystem for the pod to be able to mount it.  This requires mounting the EFS filesystem 1 of the worker nodes and adding an empty directory.

Opening this on request from d-nishi. He's been working on this and asked my to create this issue.  I can't assign the issue to him though.

**Comment by lukehoban** [comment]
@lee-baines Could you share a repro of what you wanted to do and what wasn’t working when you tried it?  I’m not exactly clear on the details of how you are trying to use EFS and EKS together here.

**Comment by d-nishi** [comment]
Original ask from @lee-baines 
==========================================================================
I've created EKS and EFS resources in AWS but now want to update the nodeUserData property of the EKS cluster as a separate action.  How do I do this?  Its a property of the ClusterOptions interface.  

If I add it into the cluster configuration after the cluster has been created, and re apply the stack, it applies the nodeUserData.  But obviously I want to automate it as a later step as it requires EFS to be set up first and that comes after EKS.

Can someone please assist me with this?

**Comment by d-nishi** [comment]
@lee-baines -- please try this [example](https://github.com/pulumi/docs/blob/master/content/blog/persisting-kubernetes-workloads-with-amazon-efscsi-volumes-using-pulumi-sdks/index.md) and let me know if this works for you.

**Comment by lee-baines** [comment]
Wow thats a lot of code :) @d-nishi. Thanks for spending the time on this,  it looks like its working fine.  I'll close this now but if I get any further issues with message you.

**Comment by lee-baines** [comment]
Issues resolved by implementing above example.

**Comment by d-nishi** [comment]
@lee-baines the CSI Node, Controller components don’t have helm charts yet that’s why there is a lot of code. Once the charts are available, the code will reduce to few lines. 

Glad it worked. :-)
