### ISSUE TITLE
Subnets are not tagged with Kubernetes key/value pairs.

### ISSUE THREAD

**Issue by timmyers** [pulumi/pulumi-eks#196]
According to the docs at https://www.pulumi.com/docs/reference/crosswalk/aws/eks/#configuring-your-eks-cluster-s-networking, this package will take care of tagging the subnets passed to it in accordance with https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html.

This does not seem to be occuring.

**Comment by lukehoban** [comment]
I believe the docs here are slightly misleading.  `pulumi-eks` does not do any subnet tagging, but EKS itself does some tagging on your behalf.  

There are additional tags that Kuberentes may use that are up to users to manually place on their Subnets if desired.  In particular `kubernetes.io/role/internal-elb` and `kubernetes.io/role/elb` as discussed at https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html are things that users must decide on and add themselves as part of the `Subnet` definition outside of `eks.Cluster`.

**Comment by timmyers** [comment]
Gotcha, I guess I run into a usability issue then where I want to tag the subnets with the name of the cluster that the pulumi module defines, but each depends on each other.  Chicken or the egg type problem.  Would be a separate issue.

**Comment by lukehoban** [comment]
Note that the only two tags from https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html that are not automatically applied by EKS do not require knowing the name of the cluster. So there should not be a chicken and egg problem for these.
