### ISSUE TITLE
creating error: Plan apply failed: error creating EKS Cluster: InvalidParameterException: Error in role params

### ISSUE THREAD

**Issue by metral** [pulumi/pulumi-eks#203]
```
aws:eks:Cluster test-replace-cluster-add-subnets-eksCluster creating error: Plan apply failed: error creating EKS Cluster
(test-replace-cluster-add-subnets-eksCluster-1480f64): InvalidParameterException: Error in role params
```

Every now and then we get IAM eventual consistency issues that seem to show up in different ways - this one is related to IAM roles erroring during creation.

Tracking this given that Travis CI hits this every now and then: [failed-tests.tar.gz](https://s3-us-west-2.amazonaws.com/eng.pulumi.com/travis-logs/pulumi/pulumi-eks/835.1/failed-tests.tar.gz).

Related:
- https://github.com/pulumi/pulumi-eks/issues/204

**Comment by metral** [comment]
Recently hit this today, and here are the command-output logs with pulumi test log level set to `-v=10`:

[command-output.tar.gz](https://github.com/pulumi/pulumi-eks/files/3478876/command-output.tar.gz)

**Comment by metral** [comment]
Potentially fixed https://github.com/pulumi/pulumi-aws/pull/817

**Comment by metral** [comment]
Reopening, as the fix in https://github.com/terraform-providers/terraform-provider-aws/pull/11127 is for the eks provider in TF, which is not used here for `pulumi/eks`

**Comment by lukehoban** [comment]
> for the eks provider in TF, which is not used here for pulumi/eks

I don’t quite follow - we do indeed use `aws.eks.Cluster` here which is the resource that was fixed.

**Comment by metral** [comment]
@lukehoban You're correct, disregard my comment - I thought it had resurfaced per Cyrus' thread, but I was crossing wires here. Closing this issue.
