### ISSUE TITLE
feat req: Delete all k8s namespaces on a cluster tear down to improve deletions

### ISSUE THREAD

**Issue by metral** [pulumi/pulumi-eks#215]
Currently, workloads created and deployed by Pulumi on a cluster will get torn down first before the cluster does during deletion. However, there still may be some AWS resources like secgroups, ENIs etc. that may take a bit to sync and remove from AWS. These resources can either be user-created (e.g. with LB-typed Services), or can be workloads that the user does not control like ENIs being managed in `kube-system` by EKS via `aws-cni` / `aws-node` .

Allowing for the proper deletion of resources would help cluster tear downs to not error as much due to leaked resources.

A possible pre-step to cluster deletion could be the use of a dynamic provider to delete all of the k8s namespaces: essentially exec'ing `$ kubectl delete --all namespaces`. This would allow for proper termination lifecycles to proceed for k8s resources and their related cloud resources, and could hopefully make cluster deletions cleaner.

**Comment by stack72** [comment]
I am going to close this out as this is an optimization around testing and hasn't had any traction from the community as a feature request
