### ISSUE TITLE
Support LaunchTemplates

### ISSUE THREAD

**Issue by frank-bee** [pulumi/pulumi-eks#218]
In order to work properly with spot instances Launch Template are required ( e.g to fall back on demand if price exceeds on-demand prize)
See also 
https://medium.com/@elngovind/cost-optimization-using-launch-template-in-aws-50a339fc155b
https://github.com/terraform-aws-modules/terraform-aws-eks

**Comment by tusharshahrs** [comment]
In order to add tags to ebs volumes via autoscaling as per [this](https://docs.aws.amazon.com/autoscaling/ec2/userguide/autoscaling-tagging.html).

```To add tags to Amazon EBS volumes, specify the tags in a launch template but use caution when configuring instance tags in your launch template.```

**Comment by flostadler** [comment]
You can use custom launch templates with a `ManagedNodeGroup`. Have a look at this example: https://github.com/pulumi/pulumi-eks/tree/master/examples/custom-managed-nodegroup
