### ISSUE TITLE
Support CoreDNS and KubeProxy updates

### ISSUE THREAD

**Issue by gitfool** [pulumi/pulumi-eks#253]
I'm very impressed with the amount of customization already in place for the [AWS VPC CNI](https://github.com/aws/amazon-vpc-cni-k8s). It's much appreciated.

Similarly, it would be nice to support updating [CoreDNS](https://github.com/coredns/coredns) and [kube-proxy](https://github.com/kubernetes/kube-proxy) as part of infra deploy, since Amazon does not update these automatically when updating an existing cluster.

References:
- https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html
> Amazon EKS does not modify any of your Kubernetes add-ons when you update a cluster. After updating your cluster, we recommend that you update your add-ons to the versions listed in the following table for the new Kubernetes version that you're updating to (steps to accomplish this are included in the update procedures).

(I've had to do this in the past when upgrading cluster versions in-place, so it really is needed.)

---

Depends on https://github.com/pulumi/pulumi-kubernetes/issues/264

**Comment by MatiasNMont** [comment]
HI! I need to do this, but I do not know how to do this. There are some solutions?

**Comment by stack72** [comment]
@roothorp can you think about how we can either expose a new option on EKS for managing add-ons OR if this is something that can be achieved using Kubernetes SSA as per https://www.pulumi.com/registry/packages/kubernetes/how-to-guides/managing-resources-with-server-side-apply/ and then we can write a guide on this?
