### ISSUE TITLE
Tests failing 

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-eks#267]
Four tests have been failing consistently in master builds over the last week.  All seem to be `*_withUpdate` tests, and all seem to fail due to:

```
error: an unhandled error occurred: rpc error: code = Unknown desc = invocation of aws:ec2/getRouteTable:getRouteTable returned an error: invoking aws:ec2/getRouteTable:getRouteTable: Your query returned no results. Please change your search criteria and try again.
```

For example: https://travis-ci.com/pulumi/pulumi-eks/builds/132752214

**Comment by metral** [comment]
cc @CyrusNajmabadi per https://github.com/pulumi/pulumi-eks/pull/264 

and possibly @stack72 per https://github.com/pulumi/pulumi-eks/pull/263

**Comment by metral** [comment]
Chatted offline with @CyrusNajmabadi - the thought is that a race in AWS could be a factor here, but also when we supply id's only for subnets and networks, we lose the dependency to the data source that's in a object, which can wait for all route tables to exist, and then be referenced. 

Trying out https://github.com/pulumi/pulumi-eks/pull/268 to see if we can wait around properly in the spot believed to be the cause.

**Comment by metral** [comment]
EKS CI is resurfacing this issue in the example/tags test. cc @CyrusNajmabadi this does not seem to be completely resolved

**Comment by lukehoban** [comment]
I don't think we are still seeing this issue - but we are definitely seeing Travis failures in master - I've opened https://github.com/pulumi/pulumi-eks/issues/300 to track current issues.  If this is one of them when we investigate - let's track there.
