### ISSUE TITLE
Cannot change logLevel of aws-k8s-cni

### ISSUE THREAD

**Issue by pereza27** [pulumi/pulumi-eks#273]
### Problem description

I am trying to change the log level of the component defined in
node_modules/@pulumi/eks/cni/aws-k8s-cni.yaml

The yaml has it as DEBUG and I need it to be WARN.  

Using code as in the attachment an error is returned instead of successful completion.

### Errors & Logs

The entire log is attached but the error is:
`for: "/tmp/tmp-34855o56eygRjgt5y.tmp": The order in patch list:
[map[name:AWS_VPC_K8S_CNI_LOGLEVEL value:WARN] map[name:AWS_VPC_K8S_CNI_LOGLEVEL value:DEBUG] map[name:AWS_VPC_K8S_CNI_LOG_FILE value:stdout]]                                                                                      ESC[0mESC[0m doesn't match $setElementOrder list:
[map[name:AWS_VPC_K8S_CNI_LOGLEVEL] map[name:AWS_VPC_K8S_CNI_LOG_FILE] map[name:MY_NODE_NAME] map[name:AWS_VPC_K8S_CNI_LOGLEVEL]]  `

[pulumi-log-error.log](https://github.com/pulumi/pulumi-eks/files/3814666/pulumi-log-error.log)

### Affected product version(s)
1.4

### Reproducing the issue
The script shows the code necessary to reproduce the error.

[index.txt](https://github.com/pulumi/pulumi-eks/files/3811336/index.txt)

**Comment by pereza27** [comment]
IDK is this is a consequence of: https://github.com/kubernetes/kubectl/issues/684

**Comment by metral** [comment]
`kubectl` is leveraged to apply the `aws-k8s-vni` manifest, and if you've tried consecutive updates to change the logLevel I can see how that issue you've linked fits here. Have you tried standing up a new stack with the logLevel set as expected ,rather than editing it after the fact?

**Comment by pereza27** [comment]
The example I provided was for a completely new stack (or was intended to be).

So, new project, new stack and the provided index.ts reproduces the failure.

**Comment by metral** [comment]
@pereza27 Thank you for your assistance. I was able to repro and pinpoint the issue you pointed out. I've gone ahead and opened a PR to fix it: https://github.com/pulumi/pulumi-eks/pull/274
