### ISSUE TITLE
Enhancement - Ability to attach multiple SecurityGroup to nodeSecurityGroup

### ISSUE THREAD

**Issue by rkomulwad** [pulumi/pulumi-eks#275]
NodeGroupBaseOption.nodeSecurityGroup should have the ability to accept multiple security groups.

https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/eks/#NodeGroupBaseOptions-nodeSecurityGroup

**Comment by protometa** [comment]
Would be nice to have an "additional" security groups option (like in kops) for adding special rules to nodes while keeping the main default SG automatic.

**Comment by naineel** [comment]
This is something we are looking for as well.

**Comment by Ahbrown41** [comment]
Any news on this one?

**Comment by metral** [comment]
We'll be picking this up in the current M36 milestone.

Thanks for your patience folks!
