### ISSUE TITLE
Set AWS EKS cluster name

### ISSUE THREAD

**Issue by gregbacchus** [pulumi/pulumi-eks#277]
When creating the `aws.eks.Cluster`, it would be great if the name property that is provided would passed in would be passed in. This way the AWS resource created will have a sensible name and will then be easily identifiable.

All that is required is to pass the `name` to the `aws.eks.Cluster` `opts` argument

https://github.com/pulumi/pulumi-eks/blob/79fb423207e0906de815f0d08857f37b85bb14e7/nodejs/eks/cluster.ts#L332-L334

```typescript
  const eksCluster = new aws.eks.Cluster(`${name}-eksCluster`, {
      name,
      roleArn: eksRole.apply(r => r.arn), 
      vpcConfig: { 
      ...
```

**Comment by pgavlin** [comment]
We generally leave autonaming on to lower the probability of the resources in two stacks ending up with conflicting names, but this does seem like a reasonable configuration point we could provide (i.e. we could optionally do what you're suggesting while still making autonaming the default behavior).

**Comment by gregbacchus** [comment]
Yes that would be ok. I just started using it with the auto name and it caused issues because in another script I needed to reference it, which I couldn't. So I had to take a copy of the while thing and add a one love change.. not ideal. The other option would be some other way to make it easier to override smaller bits of functionality

**Comment by gregbacchus** [comment]
One of the reasons that it is useful to have a known name for the EKS cluster, is that you need to add a tag to the subnets `kubernetes.io/cluster/${eksClusterName}: 'shared'`, and you need to create the subnets before you create the EKS cluster.

Without that tag on the subnets, AWS has problems auto-creating the load balancers required by the k8s services.

See
https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html

**Comment by icereed** [comment]
Hey @gregbacchus, fighting the same issue. Did you find a solution?
Otherwise I would also like to have the feature so we can preset the name.

**Comment by gregbacchus** [comment]
The only solution that I have found is to copy the class into my project
and make the required change (only a single line, if I remember correctly)

**Comment by advissor** [comment]
So, what is the solution for this ? 
I've tried to create a cluster today and it misses the required tags on subnets 
kubernetes.io/cluster/${eksClusterName}: 'shared'

So, the whole thing stalls until timeout for 30 mins.. And, there not gonna be any messages, until you fight for some hours deleting partially resources

**Comment by gregbacchus** [comment]
You can now specify the `name` in the options

```typescript
const cluster = new Cluster(name, {
    name,
    // ...
  }, {...});

```
