### ISSUE TITLE
Support Managed Node Groups

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-eks#278]
AWS released EKS Managed Node Groups today.  We should add support in this library.
https://aws.amazon.com/blogs/containers/eks-managed-node-groups/

**Comment by metral** [comment]
@lukehoban would we want to support managed node groups in addition to our existing, manual support? Or is it meant to replace it? 

If it's the former, would this be an option to configure? And if it's the latter, any thoughts on design to cleanly upgrade existing clusters to this new model?

**Comment by joeduffy** [comment]
Also to keep an eye on: https://twitter.com/nathankpeck/status/1197618371468124166

**Comment by joeduffy** [comment]
Also to keep an eye on: https://github.com/aws/containers-roadmap/issues/32#issuecomment-554634973

**Comment by lukehoban** [comment]
I expect we'd support both at least initially.  

How exactly we expose the option probably depends on details of how similar/different the API shape is.  We already have carved the Cluster and NodeGroup sides apart - so this would ideally just be an alternate way to define a NodeGroup (perhaps `.createManagedNodeGroup` to augment `.createNodeGroup`?)

Ideally upgrading to this would be similar to standard node group migration.
