### ISSUE TITLE
Expose names for created storage classes

### ISSUE THREAD

**Issue by pgavlin** [pulumi/pulumi-eks#28]
The EKS component has options to create Kubernetes storage classes, but the names of these storage classes are not exposed. This makes it difficult to use the created storage classes explicitly. We should expose these names.

**Comment by iagomelanias** [comment]
The same applies to the cluster itself.

**Comment by lukehoban** [comment]
I believe this was fixed with https://github.com/pulumi/pulumi-eks/pull/172.  cc @metral
