### ISSUE TITLE
Revisit how CNI is installed, taking into consideration Fargate

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-eks#286]
In #283 we are adding support for Fargate.  One issue we've seen with this is that the CNI daemonsets cannot run on all-Fargate clusters.  We need to revisit how we install CNI, and how we can ensure that it works as expected across both Fargate and EC2 compute.

**Comment by metral** [comment]
Also to consider: clusters that mix and match fargate with self-managed nodegroups and/or AWS managed node groups
