### ISSUE TITLE
get url for echo-server

### ISSUE THREAD

**Issue by nsisodiya** [pulumi/pulumi-eks#297]
My EKS cluster is running. I have applied the following command to run echo server.
```
helm upgrade -i echoserver echo-server/echo-server --force                       
```
Nodes
```
> KUBECONFIG=./kubeconfig.json kubectl get nodes

NAME                                   STATUS   ROLES    AGE    VERSION
fargate-ip-10-0-142-4.ec2.internal     Ready    <none>   44m    v1.14.8-eks
fargate-ip-10-0-155-107.ec2.internal   Ready    <none>   128m   v1.14.8-eks
fargate-ip-10-0-183-231.ec2.internal   Ready    <none>   128m   v1.14.8-eks
```
SVC
```
> KUBECONFIG=./kubeconfig.json kubectl get svc

NAME                     TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
echoserver-echo-server   ClusterIP   172.20.250.155   <none>        80/TCP    45m
kubernetes               ClusterIP   172.20.0.1       <none>        443/TCP   3h
```
But when i visit `172.20.250.155` on my brower, I am not getting anything.

This is the code I am running.

```js
const pulumi = require("@pulumi/pulumi");
const aws = require("@pulumi/aws");
const awsx = require("@pulumi/awsx");
const eks = require("@pulumi/eks");
const k8s = require("@pulumi/kubernetes");

const config = {
  vpcName: "syngenta-platform",
  clusterName: "syngenta-platform"
};
// Create a VPC for our cluster.
const vpc = new awsx.ec2.Vpc(config.vpcName);

// Create the EKS cluster itself with Fargate enabled.
const cluster = new eks.Cluster(config.clusterName, {
  fargate: true,
  vpcId: vpc.id,
  privateSubnetIds: vpc.privateSubnetIds
});
exports.kubeconfig = cluster.kubeconfig;
```
Please tell me what else is needed to view the first service.

My Goal.
I want to launch multiple containers with the following URLs.
https://api.syn-platform.com/echo ==> This url will get response from echo-server POD
https://api.syn-platform.com/users ==> This url will get response from users-node-app POD
users-node-app will be a docker image in ECR. it contains user micro-service.

so far, I got success in creating and lancing EKS and pods, but not getting how to get proper url.

log of pod.
```
kubectl logs echoserver-echo-server-74687f7c67-xkbmd
Listening on port 80.
1577654087396 | [GET] - http://10.0.142.4:80/ping
1577654097309 | [GET] - http://10.0.142.4:80/ping
1577654107392 | [GET] - http://10.0.142.4:80/ping
1577654117393 | [GET] - http://10.0.142.4:80/ping
1577654127393 | [GET] - http://10.0.142.4:80/ping
1577654137392 | [GET] - http://10.0.142.4:80/ping
```

**Comment by lukehoban** [comment]
> But when i visit 172.20.250.155 on my brower, I am not getting anything.

Those are `ClusterIP` services, so are not exposed to the internet. You will need `LoadBalancer` or `Ingress` or to port-forward the service port inside the cluster to your local machine.

**Comment by nsisodiya** [comment]
@lukehoban https://aws.amazon.com/blogs/aws/amazon-eks-on-aws-fargate-now-generally-available/ 
says - 
```
There are currently a few limitations that you should be aware of:
* The only load balancer you can use is an Application Load Balancer.
```
So, does int means, I need to use `ALB` to route traffic to fargate containers.
May you share some sample code of EKS with the following things.

* EKS with fargate true
* load echoserver with load balancer
* finally api -end point should be api.mydomain.com/echo

PS: I am new to Kubernetes and Pulumi. I am an expert and node/js so I liked Pulumi a lot.

**Comment by nsisodiya** [comment]
Update
1. kubectl port-forward echoserver-echo-server-74687f7c67-xkbmd 8080:80, gave me access to server using port forward. So it is working fine. now, only thing, I need to create ALB

2. I created ALB like this. Now I think, I need to connect ALB listener or target groups to this POD.
Please help me.

```js
// Create a VPC for our cluster.
const vpc = new awsx.ec2.Vpc(config.vpcName);

// Creates an ALB associated with our custom VPC.
const alb = new awsx.lb.ApplicationLoadBalancer(`sp-traffic`, { vpc });

// Listen to HTTP traffic on port 80.
const listener = alb.createListener(`sp-listener`, {
  port: config.albPort
});
// Create the EKS cluster itself with Fargate enabled.
const cluster = new eks.Cluster(config.clusterName, {
  fargate: true,
  vpcId: vpc.id,
  privateSubnetIds: vpc.privateSubnetIds
});
```

**Comment by nsisodiya** [comment]
https://github.com/weaveworks/eksctl/issues/1640

**Comment by metral** [comment]
@nsisodiya It appears you were able to resolve your OP. ALB's are recommended to be configured and managed using the official controller: https://github.com/kubernetes-sigs/aws-alb-ingress-controller.

Is it ok to close this issue?

**Comment by metral** [comment]
Closing issue
