### ISSUE TITLE
desiredSize in createManagedNodeGroup can conflict with Kubernetes cluster-autoscaler

### ISSUE THREAD

**Issue by casey-robertson** [pulumi/pulumi-eks#321]
### Problem description

The @pulumi/eks module includes a function, createManagedNodeGroup.  This is a function that is invoked to create underlying resources that make up a "node group" for EKS.  

There are 3 required scale-related values for a nodeGroup - (scalingConfig):

desiredSize: 3,
minSize: 3,
maxSize: 20

Per best-practice the cluster-autoscaler helm chart is installed into the EKS cluster to manage node (ASG) scaleup/down based on pod workloads.  

### Affected product version(s)

Current @pulumi/eks release  - 0.18.19

### Reproducing the issue

Create a cluster and node group using the above scaling configuration:
desiredSize: 3,
minSize: 3,
maxSize: 20

Deploy the cluster-autoscaler helm chart and associated IAM roles.  Use default scaling strategy (random).  
A cluster will be deployed with 3 nodes.  
Deploy a sample nginx app and scale it to 120 replicas.  Run `watch kubectl get nodes`
You will see new nodes come online to support the resource requests.
At this point the actual `desiredSize` in the ASG will not match config.
Run `pulumi refresh` - an update to the `scalingConfig` will take place.  
Let's assume the nodeGroup is sitting at 12 nodes.  

Modify the scaling configuration:
desiredSize: 6,
minSize: 3,
maxSize: 20

Run `pulumi up`.  The desiredSize will now be set to 6.  Run the same `watch kubectl get nodes`.  You will see nodes being destroyed and workloads will go into a NotReady state.  Eventually the cluster-autoscaler will step in and scale up the node count.

### Suggestions for a fix

Our work-around right now is to set a fairly high value, near or at the 'max' setting.  In practice, each time this stack runs, we may end up provisioning more nodes than we need.  In testing we end up with excess nodes for ~12 minutes.  The autoscaler then takes over and provisions new nodes.  This causes degradation for 10-15 minutes.  

What we'd like to be able to do is either 
a) have desiredSize be optional.  This is not a particularly useful setting when using EKS and the cluster-autoscaler
b) ignoreChanges on that attribute.

Due to `createManagedNodeGroup` being a function that creates Pulumi objects but is not itself a Pulumi resource, we can't effectively set that value for that attribute.

Example snippet of cluster creation
```
    // Grab the cluster name
    this.ClusterName = this.eksCluster.eksCluster.name;

    // Create managed node groups
    this.nodeGroups = clusterOpts.nodeGroups.map(ng => {
      return eks.createManagedNodeGroup(
        // Name
        ng.nodeGroupName.toString(),
        // ManagedNodeGroupOptions
        {
          nodeRoleArn: GetARN(ng.role),
          cluster: this.eksCluster,
          subnetIds: privateSubnetIds,
          ...ng
        },
        // Pulumi parent
        this.eksCluster
      );
    });
```

**Comment by metral** [comment]
Thanks for the detailed issue, much appreciated!

> What we'd like to be able to do is either:

---

> a) have desiredSize be optional. This is not a particularly useful setting when using EKS and the cluster-autoscaler

Both the nodegroup's `scalingConfig` and `desiredSize` are required args per the APIs below, so this won't be possible.

https://github.com/pulumi/pulumi-aws/blob/23de947dd89d01224804e4c8b665c0d441d36415/sdk/nodejs/eks/nodeGroup.ts#L253-L256

and

https://github.com/pulumi/pulumi-aws/blob/23de947dd89d01224804e4c8b665c0d441d36415/sdk/nodejs/types/input.ts#L6045-L6059

---

> b) ignoreChanges on that attribute.

> Due to createManagedNodeGroup being a function that creates Pulumi objects but is not itself a Pulumi resource, we can't effectively set that value for that attribute.

Have you considered creating the `aws.eks.NodeGroup` manually instead of relying on the `createManagedNodeGroup` function for this option?

The function is just a wrapper around the `NodeGroup` resource, and creating it yourself will allow you to set `ignoreChanges: ["scalingConfig"]` to achieve your goal.

See:

https://github.com/pulumi/pulumi-eks/blob/4b70178881cb0a93358d699e5ee6e7046032f969/nodejs/eks/nodegroup.ts#L703-L720

**Comment by nhinds** [comment]
I think the cluster-autoscaler only modifies the desired size. Does setting `ignoreChanges: ["scalingConfig"]` still allow you to apply changes to `scalingConfig.maxSize` and `scalingConfig.minSize` to adjust the valid range?

**Comment by casey-robertson** [comment]
Yes, max and min still work.  This makes it so that the reverse doesn't happen - when AWS / cluster auto-scaler changes the desired up and down, the Pulumi program ignores those changes.  Ignore is so that target state does not cause Pulumi to try to rectify state differences on that object.  Since the ASGs/K8s don't alter the min and max it works fine.

**Comment by metral** [comment]
@casey-robertson It appears that you were able to resolve this by defining your own managed nodegroup. Is this issue ok to close?

**Comment by casey-robertson** [comment]
Yep!  Good to go.

**Comment by munjalpatel** [comment]
Hey, @casey-robertson I am running into the same issue. 
Would you be able to share the code for the final solution you came up with?

**Comment by abatilo** [comment]
The Hashicorp `terraform-aws-eks` module automatically sets ignoring `desired_size`:
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/013afb0cc6ff6178d72ec8639827ee023e61753b/modules/node_groups/node_groups.tf#L102

Maybe we could take some inspiration and make this configurable somehow?

**Comment by michael-barker** [comment]
> ignore_changes=["scalingConfig.desiredSize"] works for ManagedNodeGroup. Note lower camel-case instead of snake case. https://www.pulumi.com/docs/intro/concepts/resources/#ignorechanges

I don't believe this works, see #709

**Comment by lobshunter** [comment]
I am with @michael-barker, I explicitly ignores `desiredCapacity` using pulumi-go, but it takes no effect, nodeGroup template is still updated.

```go
eks.NewNodeGroup(ctx, nodeGroup.Name, &eks.NodeGroupArgs{
			AutoScalingGroupTags: pulumi.ToStringMap(nodeGroup.AutoScalingGroupTags),
			AmiId:                pulumi.String(nodeGroup.AMIID),
			Cluster:              cluster.Core,
			InstanceType:         pulumi.StringPtr(nodeGroup.InstanceType),
			KeyName:              pulumi.StringPtr(nodeGroup.SSHKeyName),
			DesiredCapacity:      pulumi.IntPtr(nodeGroup.DesiredCapacity),
			MaxSize:              pulumi.IntPtr(nodeGroup.MaxSize),
			MinSize:              pulumi.IntPtr(nodeGroup.MinSize),
			NodeSubnetIds:        pulumi.ToStringArray(nodeGroup.NodeSubnetIds),
			InstanceProfile:      workerInstanceProfile,
			NodeRootVolumeSize:   pulumi.IntPtr(100),
			KubeletExtraArgs:     pulumi.StringRef(nodeGroup.KubeletExtraArgs),
			Taints:               taints,
			Labels:               nodeGroup.Labels,
		}, pulumi.IgnoreChanges([]string{"desiredCapacity"}))
```
