### ISSUE TITLE
Removal of js-yaml and YAML invoke changes in pulumi/k8s breaks withUpdate tests, and tests that load YAML

### ISSUE THREAD

**Issue by metral** [pulumi/pulumi-eks#325]
### Problem description

withUpdate tests, and examples that load yaml (e.g. `examples/clusters` and `examples/tests/replace-secgroup` which deploy the YAML dashboard) are failing.

The withUpdate tests can't find the `js-yaml` module using the latest `pulumi/eks` release (0.18.19), as the latest release of `pulumi/k8s` (1.5.1) no longer vendors it, and `pulumi/eks` did not specifically vendor it:

```
Error: Cannot find module 'js-yaml'
```

The examples that load YAML through the dashboard hit the following error possibly due to changes in `yamlLoadAll` in the commit ref below:

```
[ xamples/tests/replace-secgroup ]     TypeError: Cannot read property 'map' of undefined
[ xamples/tests/replace-secgroup ]         at config.objs.then.configObjs (/opt/pulumi/node_modules/@pulumi/eks/node_modules/@pulumi/kubernetes/yaml/yaml.js:180:14
```

### Errors & Logs

[Travis CI Run Logs](https://travis-ci.com/pulumi/pulumi-eks/builds/147993117)

Ref: pulumi/k8s [commit](https://github.com/pulumi/pulumi-kubernetes/commit/4b1bc4ff90ff22c030eebed86b4b7cd02db5c4da#diff-c6beee34c53489be29806bf23383af5aL17-L18) where js-yaml was removed, and in the same commit where invoke [yamlLoadAll](https://github.com/pulumi/pulumi-kubernetes/commit/4b1bc4ff90ff22c030eebed86b4b7cd02db5c4da#diff-e796470dbaaefe7239d307d5d9777483R124-R136) changed.

**Comment by lblackstone** [comment]
I expect this to be fixed by https://github.com/pulumi/pulumi-kubernetes/pull/987

**Comment by metral** [comment]
- `Error: Cannot find module 'js-yaml'` is being fixed by https://github.com/pulumi/pulumi-eks/pull/324
- `TypeError: Cannot read property 'map' of undefined` was fixed by https://github.com/pulumi/pulumi-kubernetes/pull/987
