### ISSUE TITLE
Tag EBS volumes when launching workers for EKS

### ISSUE THREAD

**Issue by naineel** [pulumi/pulumi-eks#332]
Currently EBS volumes attached to the EC2 worker nodes are not tagged, It would be really helpful if we could tag them.

**Comment by metral** [comment]
This is an issue in the upstream terraform/aws provider, being tracked at
https://github.com/terraform-providers/terraform-provider-aws/issues/2891

**Comment by stack72** [comment]
Hi folks,

Thanks for opening the enhancement here, as this is not yet implemented in the upstream Terraform provider, this is not something we can yet support. When this is supported upstream, we will be able to get this in the provider

Paul
