### ISSUE TITLE
Occasional issue with `createOidcProvider: true`

### ISSUE THREAD

**Issue by timmyers** [pulumi/pulumi-eks#345]
### Problem description

I am using the new `createOidcProvider: true` option.  It is failing roughly 50% of the time with the error below.

This only happens running `pulumi preview/apply` some of the time.  After a failure, a subsequent run may have no issue at all.

### Errors & Logs
```
Diagnostics:
pulumi:pulumi:Stack (infrastructure-clusters):
  Method handler getSchema for /pulumirpc.ResourceProvider/GetSchema expected but not provided

  Method handler getSchema for /pulumirpc.ResourceProvider/GetSchema expected but not provided

  error: Running program '/home/jenkins/agent/workspace/INFURA_infrastructure_oidc' failed with an unhandled exception:
  TypeError: Cannot read property 'fingerprint' of undefined
      at TLSSocket.<anonymous> (/home/jenkins/agent/workspace/INFURA_infrastructure_oidc/node_modules/@pulumi/cert-thumprint.ts:77:82)
      at TLSSocket.emit (events.js:321:20)
      at TLSSocket.EventEmitter.emit (domain.js:485:12)
      at TLSSocket.onConnectSecure (_tls_wrap.js:1504:10)
      at TLSSocket.emit (events.js:321:20)
      at TLSSocket.EventEmitter.emit (domain.js:485:12)
      at TLSSocket._finishInit (_tls_wrap.js:918:8)
      at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:688:12)
```

### Affected product version(s)
`"@pulumi/eks": "^0.18.23"`

### Reproducing the issue

Occurs occasionally in stack with
```
const cluster = new eks.Cluster('test', {
    deployDashboard: false,
    createOidcProvider: true,
});
```

**Comment by metral** [comment]
@timmyers Thanks for opening this issue. We have not been able to repro this issue manually, and our [nightly cron runs](https://travis-ci.com/pulumi/pulumi-eks/builds) in CI have been passing consistently for a few days now as well.

Could you please provide more information on your set up to help diagnose what is going on?

Thanks

**Comment by timmyers** [comment]
Hmm, I can't imagine what would be the difference causing this.  I have 3 clusters in my stack all with `createOidcProvider: true`.

I'm running with node `v13.7.0` locally and `v13.8.0` in CI, and see the error happen occasionally  in both.

**Comment by timmyers** [comment]
I think I may have figured this out.  It seems there is a race condition with closing the TLSSocket before the certificate can be obtained from it.  I have a fix locally that seems to be working 100% of the time.  I will make a PR shortly.

**Comment by timmyers** [comment]
Okay I think I was wrong about the cause, it's very hard to tell when things work _sometimes_ and you just get lucky a bunch of times in row.  Now I believe it is due to cached HTTPS sessions being cached, and when they are, the certificate is not available.

**Comment by metral** [comment]
Interesting that you're hitting what sounds like network inconsistencies?
The nightly crons in Travis run in a new VM where cache is not a factor.
Reviewing https://github.com/pulumi/pulumi-eks/pull/346

**Comment by timmyers** [comment]
Based on the fix, it seems likely due to the fact that I had multiple clusters in the stack, and I'm guessing the current test does not.

**Comment by metral** [comment]
> Based on the fix, it seems likely due to the fact that I had multiple clusters in the stack, and I'm guessing the current test does not.

Ah, that makes sense.
