### ISSUE TITLE
Getting configmaps "aws-auth" already exists on new cluster creation

### ISSUE THREAD

**Issue by RichardWLaub** [pulumi/pulumi-eks#355]
### Problem description

I'm trying to create a brand new cluster which is failing because the `aws-auth` configmap already exists. It seems related to this concern https://github.com/pulumi/pulumi-eks/pull/280#issuecomment-560973011

### Errors & Logs

```
Diagnostics:
  pulumi:pulumi:Stack (example-cluster-richard-laub):
    error: update failed

  kubernetes:core:ConfigMap (example-cluster-nodeAccess):
    error: resource kube-system/aws-auth was not successfully created by the Kubernetes API server : configmaps "aws-auth" already exists
```

### Affected product version(s)

I'm using @pulumi/eks version 0.18.24 and pulumi cli v1.13.0

### Reproducing the issue

This is the line that is creating the cluster:
```
    this.eksCluster = new eks.Cluster(
      // Name
      clusterOpts.name,
      // ClusterArgs
      {
        subnetIds,
        vpcId,
        roleMappings: clusterRoleMappings,
        instanceRoles: nodeGroupRoles,
        ...clusterOpts.options
      },
      // Pulumi compontent options
      {
        parent: this
      }
    );
```

And here are all the other options we are passing:
```
    options: {
      deployDashboard: false,
      enabledClusterLogTypes: ['api', 'audit', 'authenticator', 'controllerManager', 'scheduler'],
      endpointPrivateAccess: true,
      endpointPublicAccess: true,
      nodeAssociatePublicIpAddress: false,
      skipDefaultNodeGroup: true,
      version: '1.14'
    },
```

### Suggestions for a fix

Can't think of any right now. If there is more information that would be useful to figure this one out let me know!

**Comment by metral** [comment]
Seems that this was a fluke, and is now resolved. Closing, but please re-open if it resurfaces.
