### ISSUE TITLE
Add 'clusterencryptionconfig' to pulumi/eks

### ISSUE THREAD

**Issue by ahilmathew** [pulumi/pulumi-eks#384]
### Problem description

https://www.pulumi.com/docs/reference/pkg/aws/eks/cluster/#clusterencryptionconfig -  This is only exposed by pulumi/aws.  Can this be added to pulumi/eks as 'clusterencryptionconfig' is not exposed by pulumi/eks currently?
This will help in using AWS KMS for encryption/decryption of secrets while creating a new EKS Cluster.

**Comment by ahilmathew** [comment]
Can we have an update on this?

**Comment by metral** [comment]
Thank you for your patience.

We're aiming to pick this up this milestone.

**Comment by ahilmathew** [comment]
> Thank you for your patience.
> 
> We're aiming to pick this up this milestone.

Thanks very much.

**Comment by metral** [comment]
@ahilmathew #389 has been merged to add this functionality to the cluster.

You can test it using a dev release of the package that's on NPM until we cut a new release: https://www.npmjs.com/package/@pulumi/eks/v/0.19.1-alpha.1589300657

An example of how to use the `encryptionProvider` can be found [here](https://github.com/pulumi/pulumi-eks/blob/master/nodejs/eks/examples/encryption-provider/index.ts).

If there are any bugs, please [open an issue](https://github.com/pulumi/pulumi-eks/issues/new).
