### ISSUE TITLE
nodeGroup rolling update goes too quickly and leads to downtime

### ISSUE THREAD

**Issue by spender0** [pulumi/pulumi-eks#385]
### Problem description

I use the lib https://github.com/pulumi/pulumi-eks/blob/v0.18.24/nodejs/eks/nodegroup.ts 
to create node groups

Every time I update user data, instance types or AMI the nodes are recreated one by one that is ok.
But they are replaced too quickly and it leads to downtime.

### Affected product version(s)

pulumi cli 1.14.1
pulumi-eks v0.18.24

### Reproducing the issue

Create EKS cluster. change ec2 instance type in NG -- see how quickly nodes replacing goes.   

### Suggestions for a fix

If I manually add CFN PauseTime: PT1M option at this line https://github.com/pulumi/pulumi-eks/blob/v0.18.24/nodejs/eks/nodegroup.ts#L524  -- the updates go more smoothly.  

You can find all AutoScalingRollingUpdate options in here https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatepolicy.html#cfn-attributes-updatepolicy-rollingupdate-pausetime

Could you add additional args to NodeGroupBaseOptions. e.g.  

autoScalingRollingUpdatePauseTime?: pulumi.Input<string>;

**Comment by leezen** [comment]
Since there's a set number of minimum instances in service per the template, could you please describe how you're experiencing downtime? I would expect there to always be some number of instances in service while other instances are being replaced.

**Comment by spender0** [comment]
Autoscaling groups don't wait for nodes "ready" status in k8s, AGs just simply know nothing about k8s node status. That is why PauseTime helps in this case. It takes about 1 minute to nodes to register in eks as workers. 

For instance if you have 3 nodes and want to update ec2 instance type you will end up with "kubectl get nodes" listing all the nodes in "not ready" status

**Comment by casey-robertson** [comment]
Are these part of the issue?  https://github.com/pulumi/pulumi-eks/blob/951a1da6a398788a95e0ec7c23428ea91c2b1bd0/nodejs/eks/nodegroup.ts#L487

https://github.com/pulumi/pulumi-eks/blob/951a1da6a398788a95e0ec7c23428ea91c2b1bd0/nodejs/eks/nodegroup.ts#L525

Or is it more of an issue that ingress via ELB sees the node as up and starts sending traffic before the node is `Ready` in EKS?

**Comment by spender0** [comment]
It is about the whole CFN template in general https://github.com/pulumi/pulumi-eks/blob/951a1da6a398788a95e0ec7c23428ea91c2b1bd0/nodejs/eks/nodegroup.ts#L513

For instance, fixing this like this helps a lot in my case (added PauseTime):
`
UpdatePolicy:
    AutoScalingRollingUpdate:
        PauseTime: PT1M
`
Regarding the other parameters like "minInstancesInService". It would be nice to have them configurable as well.

**Comment by casey-robertson** [comment]
Ok so in your use case, these are unmanaged nodeGroups, correct?

**Comment by spender0** [comment]
yes, correct

**Comment by casey-robertson** [comment]
I suppose that's why tools like this got written: https://github.com/hellofresh/eks-rolling-update.  Looks like it does actual Kubernetes-aware orchestration.  We use managed nodeGroups but have run into limitations on those too.  It too engages the RollingUpdate strategy (whether via console or Pulumi) but the details are pretty sparse:

```
Rolling update — This option respects pod disruption budgets for your cluster and the update fails if Amazon EKS is unable to gracefully drain the pods that are running on this node group due to a pod disruption budget issue.
```

But I'm not sure if "Managed" nodeGroups are any more aware of the node's readiness status in Kubernetes.  I need to read up on it more.

**Comment by metral** [comment]
Thanks for the insight @spender0 and @casey-robertson -- this helps to understand that node downtime is not directly tied to self-managed or managed node groups, but rather strengthens the point that EKS clusters and node groups are independent of one another.

> Autoscaling groups don't wait for nodes "ready" status in k8s, AGs just simply know nothing about k8s node status. That is why PauseTime helps in this case. It takes about 1 minute to nodes to register in eks as workers.

> But I'm not sure if "Managed" nodeGroups are any more aware of the node's readiness status in Kubernetes. I need to read up on it more.

Correct, ASG's have no context of k8s, and this applies to managed node groups as well.

For self-managed node groups, `pulumi/eks` [uses](https://github.com/pulumi/pulumi-eks/blob/3cc8cfa18108212a3ad06579280725fdf897a092/nodejs/eks/nodegroup.ts#L435-L437) the [eks-bootstrap.sh](https://github.com/awslabs/amazon-eks-ami/blob/master/files/bootstrap.sh) to bootstrap nodes and a CloudFormation signal to indicate the nodes are up. However as noted above, it typically takes 30-60 seconds on average for nodes to be in the `READY` state, and on occasions I've personally seen this be 2+ minutes, so adding a `PauseTime` of 1 minute may not always suffice.

This disconnect between cluster and nodes is part of the reason `pulumi/eks` [uses a smoke test](https://github.com/pulumi/pulumi-eks/blob/3cc8cfa18108212a3ad06579280725fdf897a092/utils/utils.go#L61-L70) for builds to verify changes allow all nodes and pods to be marked `READY` during cluster instantiation tests.

---

> I suppose that's why tools like this got written: https://github.com/hellofresh/eks-rolling-update. Looks like it does actual Kubernetes-aware orchestration. We use managed nodeGroups but have run into limitations on those too. It too engages the RollingUpdate strategy (whether via console or Pulumi) but the details are pretty sparse

I have not used `eks-rolling-update` but the steps outlined in the [intro](https://github.com/hellofresh/eks-rolling-update#intro) are analogous to the steps outlined in the Node Group Migration [tutorial](https://www.pulumi.com/docs/tutorials/kubernetes/eks-migrate-nodegroups/).

The migration tutorial highlights the use of scheduling and update predicates like [nodeAffinity](https://github.com/pulumi/examples/blob/master/aws-ts-eks-migrate-nodegroups/nginx.ts#L23), podAntiAffinity, and [PodDisruptionBudgets](https://github.com/pulumi/examples/blob/master/aws-ts-eks-migrate-nodegroups/nginx-ing-cntlr.ts#L275) to respectively target nodes, spread pods across nodes, and ensure a given disruption budget is adhered to for rolling updates of the apps.

The affinity settings help to create an explicit relationship between the app and a node group. During node upgrades, shifting apps around becomes as simple as updating the app's node selector terms. This approach helps guarantee all apps have moved off a node group, just before it is reconfigured, decommissioned, or deleted. IMO it is best to bake these settings into your apps to allow you to pivot apps away from one node group to another cleanly, before updating properties on a node group which as you've both experienced can create downtime.

What do each of your respective apps look like during these upgrades? Are they Service-based apps? Do they make use of the predicate settings above?

**Comment by stack72** [comment]
Hi all,

There has no response in this issue for over 2 years so as part of issue pruning, I am going to close this out. If this needs re-looked at, please let us know and we can spend more time investigating 

Paul
