### ISSUE TITLE
Configmaps "aws-auth" already exists on new cluster creation

### ISSUE THREAD

**Issue by andrewpurdin** [pulumi/pulumi-eks#387]
### Problem description

I'm trying to create a brand new cluster which is failing because the aws-auth configmap already exists. This is the same issue as #355. We are now experiencing it more frequently due to heavier use of this code/pipeline. It has happened to us twice across 9 deployments in the last two days. 

### Errors & Logs

Error output from pipeline:
```
 +  aws:eks:Cluster mbcore-staging-eksCluster created Waiting for cluster endpoint (1)
 +  pulumi:providers:kubernetes mbcore-staging-provider creating 
 +  pulumi:providers:kubernetes mbcore-staging-provider created 
 +  pulumi:providers:kubernetes mbcore-staging-eks-k8s creating 
 +  pulumi:providers:kubernetes mbcore-staging-eks-k8s created 
 +  pulumi-nodejs:dynamic:Resource mbcore-staging-vpc-cni creating 
 +  kubernetes:core:ConfigMap mbcore-staging-nodeAccess creating 
 +  pulumi-nodejs:dynamic:Resource mbcore-staging-vpc-cni created 
@ Updating....
 +  kubernetes:core:ConfigMap mbcore-staging-nodeAccess creating Retry #0; creation failed: configmaps "aws-auth" already exists
 +  kubernetes:core:ConfigMap mbcore-staging-nodeAccess creating error: resource kube-system/aws-auth was not successfully created by the Kubernetes API server : configmaps "aws-auth" already exists
 +  kubernetes:core:ConfigMap mbcore-staging-nodeAccess **creating failed** error: resource kube-system/aws-auth was not successfully created by the Kubernetes API server : configmaps "aws-auth" already exists
@ Updating.....
 +  aws:eks:NodeGroup default created 
@ Updating....
 +  aws:eks:NodeGroup monitoring created 
 +  pulumi:pulumi:Stack aws-mbcore-eks-staging creating error: update failed
 +  pulumi:pulumi:Stack aws-mbcore-eks-staging **creating failed** 1 error; 6 messages
 
Diagnostics:
  kubernetes:core:ConfigMap (mbcore-staging-nodeAccess):
    error: resource kube-system/aws-auth was not successfully created by the Kubernetes API server : configmaps "aws-auth" already exists
```

### Affected product version(s)

We are currently using `0.18.24` of pulumi-eks and `2.0.0` of the Pulumi CLI. 

### Reproducing the issue

This is the line that is creating the cluster:
```
    this.eksCluster = new eks.Cluster(
      // Name
      clusterOpts.name,
      // ClusterArgs
      {
        subnetIds,
        vpcId,
        roleMappings: clusterRoleMappings,
        instanceRoles: nodeGroupRoles,
        ...clusterOpts.options
      },
      // Pulumi component options
      {
        parent: this
      }
    );
```
And here are all the other options we are passing:
```
    options: {
      name: clusterName,
      version: '1.15',
      nodeAssociatePublicIpAddress: false,
      skipDefaultNodeGroup: true,
      deployDashboard: false,
      endpointPrivateAccess: true,
      endpointPublicAccess: true,
      enabledClusterLogTypes: ['api', 'audit', 'authenticator', 'controllerManager', 'scheduler']
    },
```
### Suggestions for a fix

None, sorry :(

**Comment by metral** [comment]
We were able to repro this in 1 out of 10 runs.

### Issue 

This seems to be related to the raw use of [aws.eks.NodeGroup](https://github.com/pulumi/pulumi-aws/blob/master/sdk/nodejs/eks/nodeGroup.ts#L15) in the example program for creating `ManagedNodeGroups` over the helper func [eks.createManagedNodeGroup()](https://github.com/pulumi/pulumi-eks/blob/v0.18.24/nodejs/eks/nodegroup.ts#L704).

Specifically, in the `p/eks` helper func `eks.createManagedNodeGroup()` (see snippet) we make the `ManagedNodeGroup` `dependsOn` the creation of the `aws-auth` configmap created by `p/eks`.

This ensures we are creating the configmap with the proper mapping of instance roles, roles, and users specified, over the default configmap AWS EKS will create if the nodes attempt to join before `p/eks` has had a chance to create the configmap.

The reason we don't see this conflict arise on most runs comes down to timing and chance w.r.t the `aws-auth` in `p/eks` being created before AWS EKS has had a chance to do so.

https://github.com/pulumi/pulumi-eks/blob/951a1da6a398788a95e0ec7c23428ea91c2b1bd0/nodejs/eks/nodegroup.ts#L766-L790

---

### Fix

Adding in a `dependsOn` opt to a manually created `aws.eks.NodeGroup` should fix the issue to ensure the node group specifically waits for `p/eks` to create the updated `aws-auth` configmap:

e.g.

```
return new aws.eks.NodeGroup(name,
...
},{parent: this.eksCluster, dependsOn: this.eksCluster.core.eksNodeAccess});
```

- If you have an existing cluster in a failed state, you'll also need to delete the existing `aws-auth` configmap first, before running a new update with the `dependsOn` change:
  `kubectl delete cm aws-auth -n kube-system`
- If this is a new cluster, you shouldn't have to take any additional steps after the `dependsOn` change.

**Comment by andrewpurdin** [comment]
That makes perfect sense, it seemed like some kind of race condition. Thank you so much for your help on this @metral!
