### ISSUE TITLE
No encrypted option for rootBlockDevice in node group

### ISSUE THREAD

**Issue by mbergal** [pulumi/pulumi-eks#388]
### Problem description

I need to create  encrypted rootBlockDevice, but currently there is not option for that in `createNodeGroup`

https://github.com/pulumi/pulumi-eks/blob/master/nodejs/eks/nodegroup.ts#L445

I am not sure how I can fix it now short of forking the whole pulimi-eks. Please advice.

**Comment by chicocvenancio** [comment]
Any news on this front? Our deployment is fully encrypted except for the worker node volume.

**Comment by EricLesch** [comment]
This is something we need as well in our internal deployment to satisfy data governance requirements.
