### ISSUE TITLE
Support worker node draining during ASG updates

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-eks#40]
When the ASG decides to kill instances, it would ideally drain them before killing the instance so that pods can cleanly come back up on a new node without downtime prior to removing/killing the existing pods.  

This library would ideally support something built-in to do this, along the lines of https://aws.amazon.com/blogs/compute/how-to-automate-container-instance-draining-in-amazon-ecs/, but interacting with `kubebtl drain` instead.

This would be similar to https://github.com/kubernetes/kops/blob/master/docs/cli/kops_rolling-update_cluster.md.

**Comment by lblackstone** [comment]
https://www.reactiveops.com/blog/how-we-learned-to-stop-worrying-and-love-cluster-upgrades

This can be a tricky scenario to get right. This blog post suggests temporarily doubling the number of workers during an upgrade so that existing workloads can migrate cleanly in one go rather than having to repeatedly shuffle between nodes.

**Comment by BrianChristie** [comment]
I think the best way to do this on AWS is using AutoScaling Group Lifecycle-Hooks (as mentioned in the article above): https://docs.aws.amazon.com/autoscaling/ec2/userguide/lifecycle-hooks.html . 

Unfortunately Lifecycle-Hooks requires the use of either CloudWatch firing a Lambda, or processing a message from SQS. So I think this module will need to create an SQS queue, configure the Lifecycle-Hooks with that queue, and have a Shutdown controller running on each Node. The  controller would do something like:
- Receive the shutdown event
- Drain the Pods from the Node
- Restart the ASG Lifecycle timeout period by recording a heartbeat
- Complete the lifecycle action when the Pods are drained, ignoring DaemonSets

There has also been some discussion around gracefully handling node shutdown elsewhere that may be relevant:

- https://github.com/kubernetes/kubernetes/issues/66393
- https://github.com/kubernetes-sigs/kubespray/issues/3300
- https://github.com/pusher/k8s-spot-termination-handler (Slightly different, for handling Spot Instance 2 minute termination notices)

**Comment by naveensrinivasan** [comment]
@lukehoban Is this feature planned for an upcoming release?

**Comment by lukehoban** [comment]
We do not yet have a complete design ready for this - so it will not likely be available in the very near term.

Until this is fully automated, a useful alternative is to do the following:
1. Add an additional NodePool, deploy
2. Manually mark the old NodePool to drain/cordon, wait until this has finished
3. Then do another deployment that removes the old NodePool

This has the downside of requiring a manual step in between the two deployments, but (1) and (3) can both safely be done in CI, and overall this provides a high-confidence path to doing node upgrades.

**Comment by naveensrinivasan** [comment]
@lukehoban How do we know when the Node is going to be scaled down by ASG
https://github.com/pulumi/pulumi-eks/issues/40#issuecomment-478524613?

Also is the mechanism for upgrading nodes across version upgrades.
>
    1. Add an additional NodePool, deploy
    2. Manually mark the old NodePool to drain/cordon, wait until this has finished
    3. Then do another deployment that removes the old NodePool

If the above is not the mechanism for upgrading nodes for version upgrades? Is there a doc/example for the node upgrades. That would be helpful in figuring out node upgrades process.

**Comment by lukehoban** [comment]
There are two ways to upgrade NodePools: (1)  update the AMI for the NodePool ASG in-place, causing a rolling update or (2) create a whole new NodePool, migrate work to it, then tear down the whole old NodePool.

These are the same two options discussed at https://docs.aws.amazon.com/eks/latest/userguide/update-workers.html.  

This issue is primarily discussing a way to automate (1).  My recommendation in https://github.com/pulumi/pulumi-eks/issues/40#issuecomment-496314426 is about instead doing (2).

**Comment by metral** [comment]
Example and tutorial PRs are in-flight that covers how to perform a migration of workloads across node groups, and how to update older node groups with new ones.

- Example PR: https://github.com/pulumi/examples/pull/348
- Tutorial PR: https://github.com/pulumi/docs/pull/1327
