### ISSUE TITLE
Users fail to authenticate with cluster when attempting to assume role

### ISSUE THREAD

**Issue by svrana** [pulumi/pulumi-eks#405]
### Problem description

I've created an eks cluster and followed the the rbac tutorial [here](https://www.pulumi.com/blog/simplify-kubernetes-rbac-in-amazon-eks-with-open-source-pulumi-packages). As the cluster creator, I'm able to authenticate with the cluster and perform all actions. However, if I configure my local aws tool to use another user via the config in ~/.aws/credentials (with the same aws permissions), I have problems performing some actions on the cluster. For example, attempting to deploy pods, I get this error message:

`configured Kubernetes cluster is unreachable: unable to load schema information from the API server: the server has asked for the client to provide credentials`

To assume the role when running kubectl commands, I have tried both with aws-iam-authenticator and aws eks get-token (and told each one to use the role I created as part of the tutorial) configured in my kubeconfigs. I can verify the role is being assumed by running a `kubectl get pods` command and then looking at the LastActivity timestamp for the role in the aws console and verifying that it reflects the time at which I ran the kubectl command. However, for some actions the actions fail or succeed depending on which user the aws cli is configured to use via its configuration file. My expectation is that the current aws user privileges will be checked to determine if it can assume the role; if allowed, the get-token command will complete successfully and a token will be provided and the kubectl actions will be allowed/denied based on the assumed role and aws-auth configmap and not have anything to do with the original aws cli user. Am I misunderstanding something?

Note that I have AWS_REGION set but no aws specific profile set so expecting that pulumi up is using the default aws credentials for access to aws.

### Likely related issues

[296](https://github.com/pulumi/pulumi-eks/issues/296) contains the same error message
[205](https://github.com/pulumi/pulumi-eks/pull/205)

### Versions

 pulumi/eks 0.19.2
 puluim/aws 2.11.10
 aws-cli/1.18.82

**Comment by metral** [comment]
Thanks for the detailed information, @svrana.

We have the following [EKS examples](https://github.com/pulumi/pulumi-eks/tree/master/nodejs/eks/examples) to work with various IAM approaches, which should help.

- [Using an AWS role for devs that gets mapped into the cluster's RBAC](https://github.com/pulumi/pulumi-eks/blob/master/nodejs/eks/examples/scoped-kubeconfigs/index.ts)
- [Using an AWS_PROFILE to create and manage the cluster](https://github.com/pulumi/pulumi-eks/blob/master/nodejs/eks/examples/scoped-kubeconfigs/index.ts)

Let us know if these examples help with your use case.

**Comment by svrana** [comment]
Thanks @metral for your quick response. I haven't had time to test yet, but the examples have shown me where my mental model has steered me wrong. Looks like I will need to create a new cluster provider using a kubeconfig generated from the role. I hadn't done this, so was using the default cluster.provider that was created when I first created the cluster. I'm a little surprised this worked at all, as other users were able to perform some actions in the cluster.

**Comment by svrana** [comment]
To make use of a particular role:
```
const roleKubeconfigOpts: eks.KubeconfigOptions = { roleArn: devsRole.arn };
const roleKubeconfig = cluster.getKubeconfig(roleKubeconfigOpts);
const roleProvider = new k8s.Provider("provider", {kubeconfig: roleKubeconfig});
```
Then use roleProvider.

Thanks again @metral.

**Comment by metral** [comment]
Glad you were able to resolve your use case @svrana 🎉
