### ISSUE TITLE
EKS fails to properly tag subnets

### ISSUE THREAD

**Issue by ninja-** [pulumi/pulumi-eks#415]
Using example code from examples for setting up EKS.

```
const vpc = new awsx.ec2.Vpc("vpc");
const cluster = new eks.Cluster("cluster", {
    vpcId: vpc.id,
    subnetIds: vpc.publicSubnetIds,
    vpcCniOptions: {
        warmIpTarget: 4
    }
});

// Declare the ALBIngressController in 1 step with the Helm Chart.
const albingresscntlr = new kubernetes.helm.v2.Chart(
    "alb",
    {
        chart:
            "http://storage.googleapis.com/kubernetes-charts-incubator/aws-alb-ingress-controller-1.0.2.tgz",
        values: {
            clusterName: clusterName,
            autoDiscoverAwsRegion: "true",
            awsVpcID: vpc.id
            // autoDiscoverAwsVpcID: "true"
        }
    },
    { provider: cluster.provider }
```

Results later on in:

```
E0728 17:08:16.069591       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to build LoadBalancer configuration due to failed to resolve 2 qualified subnet with at least 8 free IP Addresses for ALB. Subnets must contains these tags: 'kubernetes.io/cluster/xxxeksCluster-9fc3de5': ['shared' or 'owned'] and 'kubernetes.io/role/elb': ['' or '1']. See https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/controller/config/#subnet-auto-discovery for more details. Resolved qualified subnets: '[]'"  "controller"="alb-ingress-controller" "request"={"Namespace":"default","Name":"app-3nqwvmw5"}
```

Looks like pulumi fails to properly setup kubernetes.io/role/elb=1 annotation while it sets up kubernetes.io/cluster/xxx annotations just fine.
Setting up kubernetes.io/role/elb manually makes it work.

**Comment by metral** [comment]
Thanks for the input @ninja- 

Auto-tagging subnets would be a worthy value add, though there are nuances in how to go about this.

> Looks like pulumi fails to properly setup kubernetes.io/role/elb=1 annotation while it sets up kubernetes.io/cluster/xxx annotations just fine.

`pulumi/eks` does not tag the cluster with `kubernetes.io/cluster/xxx`, [AWS EKS tags it for you](https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html#vpc-tagging).

For the other LB tags, `pulumi/eks` has no input on which public or private subnets the user would want to sub-select and use for LBs specifically. From a related issue https://github.com/pulumi/pulumi-eks/issues/196#issuecomment-511462321:

> I believe the docs here are slightly misleading. pulumi-eks does not do any subnet tagging, but EKS itself does some tagging on your behalf.

> There are additional tags that Kuberentes may use that are up to users to manually place on their Subnets if desired. In particular kubernetes.io/role/internal-elb and kubernetes.io/role/elb as discussed at https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html are things that users must decide on and add themselves as part of the Subnet definition outside of eks.Cluster.

Given that subnets may be created in the same program as a cluster, independently from a cluster, or existing subnets outside of the context of pulumi may be used, `pulumi/eks` has no deterministic way of modifying the subnet object to add tags for all of these scenarios.

> It would be good to add it to examples because currently docs are asking to manually add these tags in iam console

Agreed, having an example here would've been helpful in your situation, and we'll look to add one to address this scenario!

**Comment by mike-chen-samsung** [comment]
> pulumi/eks does not tag the cluster with kubernetes.io/cluster/xxx, [AWS EKS tags it for you](https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html#vpc-tagging).

Looks like it doesn't anymore :(

> Amazon EKS does not add the tag to subnets passed in when creating 1.19 clusters

Is there a recommended way to handle this?
