### ISSUE TITLE
Implement a plugin that exposes an EKS remote component resource.

### ISSUE THREAD

**Issue by pgavlin** [pulumi/pulumi-eks#439]
See https://github.com/pulumi/pulumi/tree/master/tests/integration/construct_component/testcomponent for an example of a plugin that hosts a NodeJS component.

In the fullness of time, this will also require a schema for the component s.t. we can generate per-language SDKs.

- [ ] Python (https://github.com/pulumi/pulumi-eks/pull/448, https://github.com/pulumi/pulumi-eks/pull/475)
- [ ] .NET (https://github.com/pulumi/pulumi-eks/pull/448, https://github.com/pulumi/pulumi-eks/pull/475)
- [ ] Go (https://github.com/pulumi/pulumi-eks/pull/457)

**Comment by justinvp** [comment]
Surface area progress

## ./cluster

### Cluster (ComponentResource)
- [x] readonly kubeconfig: pulumi.Output<any>;
- [ ] readonly awsProvider: pulumi.ProviderResource;
- [ ] readonly provider: k8s.Provider;
- [ ] readonly clusterSecurityGroup: aws.ec2.SecurityGroup;
- [ ] readonly instanceRoles: pulumi.Output<aws.iam.Role[]>;
- [ ] readonly nodeSecurityGroup: aws.ec2.SecurityGroup;
- [ ] readonly eksClusterIngressRule: aws.ec2.SecurityGroupRule;
- [ ] readonly defaultNodeGroup: NodeGroupData | undefined;
- [ ] readonly eksCluster: aws.eks.Cluster;
- [ ] readonly core: CoreData;
- [x] constructor(name: string, args?: ClusterOptions, opts?: pulumi.ComponentResourceOptions);
- [ ] createNodeGroup(name: string, args: ClusterNodeGroupOptions): NodeGroup;
- [ ] getKubeconfig(args: KubeconfigOptions): pulumi.Output<string>;

### ClusterOptions
- [x] vpcId?: pulumi.Input<string>;
- [x] subnetIds?: pulumi.Input<pulumi.Input<string>[]>;
- [x] publicSubnetIds?: pulumi.Input<pulumi.Input<string>[]>;
- [x] privateSubnetIds?: pulumi.Input<pulumi.Input<string>[]>;
- [ ] nodeGroupOptions?: ClusterNodeGroupOptions;
- [x] nodeAssociatePublicIpAddress?: boolean;
- [x] roleMappings?: pulumi.Input<pulumi.Input<RoleMapping>[]>;
- [x] userMappings?: pulumi.Input<pulumi.Input<UserMapping>[]>;
- [x] vpcCniOptions?: VpcCniOptions;
- [ ] instanceType?: pulumi.Input<aws.ec2.InstanceType>;
- [ ] instanceRole?: pulumi.Input<aws.iam.Role>;
- [x] instanceProfileName?: pulumi.Input<string>;
- [ ] serviceRole?: pulumi.Input<aws.iam.Role>;
- [ ] creationRoleProvider?: CreationRoleProvider;
- [ ] instanceRoles?: pulumi.Input<pulumi.Input<aws.iam.Role>[]>;
- [x] customInstanceRolePolicy?: pulumi.Input<string>;
- [x] nodeAmiId?: pulumi.Input<string>;
- [x] gpu?: pulumi.Input<boolean>;
- [x] nodePublicKey?: pulumi.Input<string>;
- [x] nodeSubnetIds?: pulumi.Input<pulumi.Input<string>[]>;
- [ ] clusterSecurityGroup?: aws.ec2.SecurityGroup;
- [x] clusterSecurityGroupTags?: InputTags;
- [x] encryptRootBockDevice?: pulumi.Input<boolean>;
- [x] nodeSecurityGroupTags?: InputTags;
- [x] nodeRootVolumeSize?: pulumi.Input<number>;
- [x] nodeUserData?: pulumi.Input<string>;
- [x] desiredCapacity?: pulumi.Input<number>;
- [x] minSize?: pulumi.Input<number>;
- [x] maxSize?: pulumi.Input<number>;
- [ ] storageClasses?: { [name: string]: StorageClass } | EBSVolumeType;
- [x] skipDefaultNodeGroup?: boolean;
- [x] deployDashboard?: boolean;
- [x] tags?: InputTags;
- [x] version?: pulumi.Input<string>;
- [x] enabledClusterLogTypes?: pulumi.Input<pulumi.Input<string>[]>;
- [x] endpointPublicAccess?: pulumi.Input<boolean>;
- [x] endpointPrivateAccess?: pulumi.Input<boolean>;
- [x] publicAccessCidrs?: pulumi.Input<pulumi.Input<string>[]>;
- [x] fargate?: boolean | FargateProfile;
- [x] clusterTags?: InputTags;
- [x] createOidcProvider?: pulumi.Input<boolean>;
- [x] name?: pulumi.Input<string>;
- [x] proxy?: string;
- [x] providerCredentialOpts?: KubeconfigOptions;
- [x] encryptionConfigKeyArn?: pulumi.Input<string>;

### RoleMapping
- [x] roleArn: pulumi.Input<aws.ARN>;
- [x] username: pulumi.Input<string>;
- [x] groups: pulumi.Input<pulumi.Input<string>[]>;

### UserMapping
- [x] userArn: pulumi.Input<aws.ARN>;  (Note: currently typed as `string`)
- [x] username: pulumi.Input<string>;
- [x] groups: pulumi.Input<pulumi.Input<string>[]>;

### FargateProfile
- [x] podExecutionRoleArn?: pulumi.Input<string>;
- [x] subnetIds?: pulumi.Input<pulumi.Input<string>[]>;
- [x] selectors?: pulumi.Input<pulumi.Input<aws.types.input.eks.FargateProfileSelector>[]>;
    - (Note: currently emitting a copy in this library)

### FargateProfileSelector
(Note: this is a copy of aws.types.input.eks.FargateProfileSelector)
- [x] labels?: pulumi.Input<{ [key: string]: pulumi.Input<string> }>;
- [x] namespace: pulumi.Input<string>;

### interface ClusterNodeGroupOptions extends NodeGroupBaseOptions
(Note: no additional members beyond the base interface)
- [ ] TODO

### CreationRoleProvider
- [ ] role: aws.iam.Role;
- [ ] provider: pulumi.ProviderResource;

### KubeconfigOptions
- [x] roleArn?: pulumi.Input<aws.ARN>;
- [x] profileName?: pulumi.Input<string>;

### CoreData
- [ ] cluster: aws.eks.Cluster;
- [ ] vpcId: pulumi.Output<string>;
- [ ] subnetIds: pulumi.Output<string[]>;
- [ ] endpoint: pulumi.Output<string>;
- [ ] clusterSecurityGroup: aws.ec2.SecurityGroup;
- [ ] provider: k8s.Provider;
- [ ] instanceRoles: pulumi.Output<aws.iam.Role[]>;
- [ ] nodeGroupOptions: ClusterNodeGroupOptions;
- [ ] awsProvider?: pulumi.ProviderResource;
- [ ] publicSubnetIds?: pulumi.Output<string[]>;
- [ ] privateSubnetIds?: pulumi.Output<string[]>;
- [ ] eksNodeAccess?: k8s.core.v1.ConfigMap;
- [ ] storageClasses?: UserStorageClasses;
- [ ] kubeconfig?: pulumi.Output<any>;
- [ ] vpcCni?: VpcCni;
- [ ] tags?: InputTags;
- [ ] nodeSecurityGroupTags?: InputTags;
- [ ] fargateProfile?: aws.eks.FargateProfile;
- [ ] oidcProvider?: aws.iam.OpenIdConnectProvider;
- [ ] encryptionConfig?: pulumi.Output<aws.types.output.eks.ClusterEncryptionConfig>;

### FUNCTIONS
- [ ] function getRoleProvider(name: string, region?: aws.Region, profile?: string, parent?: pulumi.ComponentResource, provider?: pulumi.ProviderResource): CreationRoleProvider;
- [ ] function createCore(name: string, args: ClusterOptions, parent: pulumi.ComponentResource, provider?: pulumi.ProviderResource): CoreData;  (Note: not exported from index.ts)


## ./nodegroup

### ManagedNodeGroupOptions
Note: this is declared as `Omit<aws.eks.NodeGroupArgs, "clusterName" | "nodeRoleArn" | "subnetIds" | "scalingConfig"> & { /* and the following props */ }`)
- [ ] cluster: Cluster | CoreData;
- [ ] clusterName?: pulumi.Output<string>;
- [ ] nodeGroupName?: pulumi.Input<string>;
- [ ] nodeRoleArn?: pulumi.Input<string>;
- [ ] nodeRole?: pulumi.Input<aws.iam.Role>;
- [ ] subnetIds?: pulumi.Input<pulumi.Input<string>[]>;
- [ ] scalingConfig?: pulumi.Input<awsInputs.eks.NodeGroupScalingConfig>;

### NodeGroup (ComponentResource)
- [ ] readonly nodeSecurityGroup: aws.ec2.SecurityGroup;
- [ ] readonly extraNodeSecurityGroups: aws.ec2.SecurityGroup[];
- [ ] cfnStack: aws.cloudformation.Stack;
- [ ] autoScalingGroupName: pulumi.Output<string>;
- [ ] constructor(name: string, args: NodeGroupOptions, opts?: pulumi.ComponentResourceOptions);

### NodeGroupOptions
- [ ] cluster: Cluster | CoreData;

### NodeGroupData
(Note: This is an interface that NodeGroup implements)
- [ ] nodeSecurityGroup: aws.ec2.SecurityGroup;
- [ ] cfnStack: aws.cloudformation.Stack;
- [ ] autoScalingGroupName: pulumi.Output<string>;
- [ ] extraNodeSecurityGroups?: aws.ec2.SecurityGroup[];

### NodeGroupBaseOptions
- [ ] nodeSubnetIds?: pulumi.Input<pulumi.Input<string>[]>;
- [ ] instanceType?: pulumi.Input<aws.ec2.InstanceType>;
- [ ] spotPrice?: pulumi.Input<string>;
- [ ] nodeSecurityGroup?: aws.ec2.SecurityGroup;
- [ ] clusterIngressRule?: aws.ec2.SecurityGroupRule;
- [ ] extraNodeSecurityGroups?: aws.ec2.SecurityGroup[];
- [ ] encryptRootBockDevice?: pulumi.Input<boolean>;
- [ ] nodePublicKey?: pulumi.Input<string>;
- [ ] keyName?: pulumi.Input<string>;
- [ ] nodeRootVolumeSize?: pulumi.Input<number>;
- [ ] nodeUserData?: pulumi.Input<string>;
- [ ] nodeUserDataOverride?: pulumi.Input<string>;
- [ ] desiredCapacity?: pulumi.Input<number>;
- [ ] minSize?: pulumi.Input<number>;
- [ ] maxSize?: pulumi.Input<number>;
- [ ] amiId?: pulumi.Input<string>;
- [ ] gpu?: pulumi.Input<boolean>;
- [ ] labels?: { [key: string]: string };
- [ ] taints?: { [key: string]: Taint };
- [ ] kubeletExtraArgs?: string;
- [ ] bootstrapExtraArgs?: string;
- [ ] nodeAssociatePublicIpAddress?: boolean;
- [ ] version?: pulumi.Input<string>;
- [ ] instanceProfile?: aws.iam.InstanceProfile;
- [ ] autoScalingGroupTags?: InputTags;
- [ ] cloudFormationTags?: InputTags;

### Taint
- [ ] value: string;
- [ ] effect: "NoSchedule" | "NoExecute" | "PreferNoSchedule";

### FUNCTIONS
- [ ] function createManagedNodeGroup(name: string, args: ManagedNodeGroupOptions, parent?: pulumi.ComponentResource, provider?: pulumi.ProviderResource): aws.eks.NodeGroup;
- [ ] function createNodeGroup(name: string, args: NodeGroupOptions, parent: pulumi.ComponentResource, provider?: pulumi.ProviderResource): NodeGroupData;
- [ ] function computeWorkerSubnets(parent: pulumi.Resource, subnetIds: string[]): Promise<string[]>;


## ./cni

### VpcCni (Dynamic resource)
- [ ] TODO port to custom resource
- [ ] constructor(name: string, kubeconfig: pulumi.Input<any>, args?: VpcCniOptions, opts?: pulumi.CustomResourceOptions);

### VpcCniOptions
- [x] nodePortSupport?: pulumi.Input<boolean>;
- [x] customNetworkConfig?: pulumi.Input<boolean>;
- [x] externalSnat?: pulumi.Input<boolean>;
- [x] warmEniTarget?: pulumi.Input<number>;
- [x] warmIpTarget?: pulumi.Input<number>;
- [x] logLevel?: pulumi.Input<string>;  (Note: TODO: consider typing this as an enum)
- [x] logFile?: pulumi.Input<string>;
- [x] image?: pulumi.Input<string>;
- [x] vethPrefix?: pulumi.Input<string>;
- [x] eniMtu?: pulumi.Input<number>;
- [x] eniConfigLabelDef?: pulumi.Input<string>;


## ./securitygroup

### NodeGroupSecurityGroupOptions
- [ ] vpcId: pulumi.Input<string>;
- [ ] clusterSecurityGroup: aws.ec2.SecurityGroup;
- [ ] tags?: InputTags;
- [ ] eksCluster: aws.eks.Cluster;

### FUNCTIONS
- [ ] function createNodeGroupSecurityGroup(name: string, args: NodeGroupSecurityGroupOptions, parent: pulumi.ComponentResource, provider?: pulumi.ProviderResource): [aws.ec2.SecurityGroup, aws.ec2.SecurityGroupRule];


## ./storageclass

### StorageClass
- [ ] type: pulumi.Input<EBSVolumeType>;
- [ ] zones?: pulumi.Input<pulumi.Input<string>[]>;
- [ ] iopsPerGb?: pulumi.Input<number>;
- [ ] encrypted?: pulumi.Input<boolean>;
- [ ] kmsKeyId?: pulumi.Input<string>;
- [ ] default?: pulumi.Input<boolean>;
- [ ] allowVolumeExpansion?: pulumi.Input<boolean>;
- [ ] metadata?: pulumi.Input<k8sInputs.meta.v1.ObjectMeta>;
- [ ] mountOptions?: pulumi.Input<string[]>;
- [ ] reclaimPolicy?: pulumi.Input<string>;
- [ ] volumeBindingMode?: pulumi.Input<string>;

### EBSVolumeType
(Note: This is an enum (type alias): "io1" | "gp2" | "sc1" | "st1")
- [x] Currently typed as just `string`

### FUNCTIONS
- [ ] function createStorageClass(name: string, storageClass: StorageClass, opts: pulumi.CustomResourceOptions): k8s.storage.v1.StorageClass;


## ./utils

### InputTags
(Note: This is just a type alias for an input map[string]string that we can project directly)
- [x] DONE

### export declare type UserStorageClasses = pulumi.Output<{ [key: string]: k8s.storage.v1.StorageClass }>;
- [ ] TODO





# These aren't exported from the top-level index.ts. Do we need to expose them in the other languages?

## ./cert-thumprint

### FUNCTIONS
- [ ] function getIssuerCAThumbprint(issuerUrl: pulumi.Input<string>, agent: http.Agent): pulumi.Output<string>;


## ./dashboard

### DashboardOptions  (Note: empty interface)

### FUNCTIONS
- [ ] function createDashboard(name: string, args: DashboardOptions, parent: pulumi.ComponentResource, k8sProvider: k8s.Provider): void;


## ./servicerole

### ServiceRoleArgs
- [ ] readonly service: pulumi.Input<string>;
- [ ] readonly description?: pulumi.Input<string>;
- [ ] readonly managedPolicyArns?: string[];

### ServiceRole (ComponentResource)
- [ ] readonly role: pulumi.Output<aws.iam.Role>;
- [ ] constructor(name: string, args: ServiceRoleArgs, opts?: pulumi.ResourceOptions);


## ./transform (Looks like internal helper)

### FUNCTIONS
- [ ] function transform<T, U>(name: string, input: T, func: (v: T) => U, opts?: pulumi.CustomResourceOptions): pulumi.Output<U>;
