### ISSUE TITLE
Enable nightly cron schedule of GHA

### ISSUE THREAD

**Issue by metral** [pulumi/pulumi-eks#441]
### Problem description

It'd be great to enable the nightly cron schedule on the repo now that CI has moved away from Travis to GHA.

**Comment by stack72** [comment]
Hey @metral 

What kind of time do you want this cron to run at?
Do you want cron failures to write to the builds channel?

P.

**Comment by metral** [comment]
~10pm PDT SGTM.

Yes, lets write failures to Slack please! 😄
