### ISSUE TITLE
Support Service IPv4 range

### ISSUE THREAD

**Issue by jwenz723** [pulumi/pulumi-eks#443]
### Problem description

Add support for the new `Service IPv4 range` feature of EKS clusters: https://aws.amazon.com/about-aws/whats-new/2020/10/amazon-eks-supports-configurable-kubernetes-service-ip-address-range/

### Errors & Logs

N/A

### Affected product version(s)

N/A

### Reproducing the issue

N/A

### Suggestions for a fix

I don't have any suggestions currently. I'm not familiar with the package internals.

**Comment by jwenz723** [comment]
I also captured this feature request [here](https://github.com/pulumi/pulumi-aws/issues/1148)

**Comment by matanbaruch** [comment]
Any update on this?

**Comment by matanbaruch** [comment]
@stack72
