### ISSUE TITLE
encryptRootBockDevice should be Block instead of Bock

### ISSUE THREAD

**Issue by disk-edit** [pulumi/pulumi-eks#446]
File: [docs/reference/pkg/nodejs/pulumi/eks/_index.md](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/eks/)
property encryptRootBockDevice should be Block instead of Bock

**Comment by stack72** [comment]
@metral this is actually a typo in a parameter that the docs are picking up

**Comment by disk-edit** [comment]
Of course. That make sense.

**Comment by metral** [comment]
Thanks for catching this! Substitution + replacements = 🤦 

We'll work on a fix soon.
