### ISSUE TITLE
Test failure: Cluster limit exceeded for account

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-eks#48]
I think we're out of EKS clusters in whatever region we run the tests in:

```
Plan apply failed: error creating EKS Cluster (cluster-eksCluster-e284a91):
ResourceLimitExceededException: Cluster limit exceeded for account.
```

**Comment by lukehoban** [comment]
Deleted unused (leaked) clusters in the testing environment.  We did not hit this issue in https://travis-ci.com/pulumi/pulumi-eks/builds/97972367.
