### ISSUE TITLE
Python: When there are errors from TS, the deployment appears to hang

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi-eks#480]
When running `pulumi up` on a project that uses `python-eks` and there's an error from TS, the deployment just appears to hang. Pressing CTRL+C then cancels the update and shows the errors.

We need to fix this so that when there are any errors from TS, they immediately fail the update and display the error.

**Comment by justinvp** [comment]
This appears to be limited to when errors are thrown inside an `apply`, which happens a fair amount in the EKS library for input validation. For example:

https://github.com/pulumi/pulumi-eks/blob/233819196cf947dae12eb7208e8a5f16c168f682/nodejs/eks/nodegroup.ts#L820-L824

If this was just a regular Node.js program using `@pulumi/eks`, the exception inside the `apply` will be propagated to the `unhandledException`/`unhandledRejection` events, and during the process `exit` event, if there were any uncaught errors, the process exits with an error code, resulting in a failed update.

For multi-language components, similarly, exceptions inside the `apply` are propagated to the `unhandledException`/`unhandledRejection` events, where the errors are logged with `console.error`, and during the process `exit` event, if there were any uncaught errors, the process would exit with an error code... However, the process may not exit, because this is a provider plugin process. The logged errors will quickly fly by the "Info" column during an update, but then the update just sits there, and never results in a failed update.

We'll need to make sure such errors stop processing further resource operations. The likely solution will be to connect to the engine gRPC service and log the errors via that with `LogSeverity.ERROR`, which should end the update.

**Comment by justinvp** [comment]
I thought switching to `log.error` would address this, but it only partially fixes the issue. Now the deployment properly shows that there's an error, but there's still a hang. It turns out that despite our docs, logging an error does not immediately fail the overall deployment.

I wonder if some of Evan's learnings from https://github.com/pulumi/pulumi/issues/6153#issuecomment-767943455 can be used here.

**Comment by justinvp** [comment]
https://github.com/pulumi/pulumi/issues/6090 would also address this, but that is a larger change (and a behavior change). Need to see if https://github.com/pulumi/pulumi/issues/6153#issuecomment-767943455 would address it.

**Comment by justinvp** [comment]
To add a bit more details, I'm wondering if we can address this in https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/provider/server.ts by making a similar change as mentioned in https://github.com/pulumi/pulumi/issues/6153#issuecomment-767943455.

**Comment by t0yv0** [comment]
@justinvp is there an easy to access example of a multi-lang program, I'm wondering how to get started with a repro example here.

**Comment by t0yv0** [comment]
There is good news and bad news. The good news is that I don't seem to be able to repro the hang. The bad news is that pulumi-eks on master has some TypeScript compilation errors and a runtime error on my example, so to repro and run my example I actually have to tweak the source code a little bit. I will put up some PR shortly.

Now for the example itself. I have this Python program:

```
import json
import pulumi
import pulumi_aws as aws
import pulumi_eks as eks

config = pulumi.Config()
instance_type = config.get("instanceType") # as aws.ec2.InstanceType;
desired_capacity = config.get_int("desiredCapacity");
min_size = config.get_int("minSize");
max_size = config.get_int("maxSize");
storage_class = config.get("storageClass") #as eks.EBSVolumeType;

vpc = aws.ec2.Vpc("eksvpc",
                  cidr_block='10.100.0.0/16')

zones = aws.get_availability_zones()
subnet_ids = []

for zone in zones.names:
    vpc_subnet = aws.ec2.Subnet(
        f'vpc-subnet-{zone}',
        assign_ipv6_address_on_creation=False,
        vpc_id=vpc.id,
        map_public_ip_on_launch=True,
        cidr_block=f'10.100.{len(subnet_ids)}.0/24',
        availability_zone=zone,
        tags={
            'Name': f'pulumi-sn-{zone}',
        },
    )
    subnet_ids.append(vpc_subnet.id)

# Create an EKS cluster with the given configuration.
cluster = eks.Cluster("cluster", **{
    'vpc_id': vpc.id,
    'subnet_ids': subnet_ids,
    'instance_type': instance_type,
    'desired_capacity': desired_capacity,
    'min_size': min_size,
    'max_size': max_size,
    'storage_classes': storage_class,
    'provider_credential_opts': {},
    'skip_default_node_group': True,
    'instance_roles': [],
});


eks.ManagedNodeGroup('mng1',
                     cluster=cluster,
                     node_role_arn='this does not exist',
                     cluster_name=cluster.name,
                     subnet_ids=subnet_ids)

# Export the cluster's kubeconfig.
pulumi.export('kubeconfig', cluster.kubeconfig)
```

And when I run `pulumi preview` I get:

```
pulumi preview
Previewing update (dev)

View Live: https://app.pulumi.com/t0yv0/repro-480-pulumi-eks-2/dev/previews/87059cef-2f10-48e1-a851-6fb572d40bca


 +  pulumi:pulumi:Stack repro-480-pulumi-eks-2-dev create 
 +  aws:ec2:Vpc eksvpc create 
 +  aws:ec2:Subnet vpc-subnet-us-east-1a create 
 +  aws:ec2:Subnet vpc-subnet-us-east-1b create 
 +  aws:ec2:Subnet vpc-subnet-us-east-1d create 
 +  aws:ec2:Subnet vpc-subnet-us-east-1e create 
 +  aws:ec2:Subnet vpc-subnet-us-east-1c create 
 +  aws:ec2:Subnet vpc-subnet-us-east-1f create 
 +  eks:index:Cluster cluster create 
 +  eks:index:ServiceRole cluster-eksRole create 
 +  aws:ec2:SecurityGroup cluster-eksClusterSecurityGroup create 
 +  aws:iam:Role cluster-eksRole-role create 
 +  aws:ec2:SecurityGroupRule cluster-eksClusterInternetEgressRule create 
 +  aws:iam:RolePolicyAttachment cluster-eksRole-90eb1c99 create 
 +  aws:iam:RolePolicyAttachment cluster-eksRole-4b490823 create 
 +  aws:eks:Cluster cluster-eksCluster create 
 +  pulumi:providers:kubernetes cluster-eks-k8s create 
 +  pulumi:providers:kubernetes cluster-provider create 
 +  kubernetes:core/v1:ConfigMap cluster-nodeAccess create 
 +  eks:index:VpcCni cluster-vpc-cni create 
 +  aws:ec2:SecurityGroup cluster-nodeSecurityGroup create 
 +  aws:ec2:SecurityGroupRule cluster-eksClusterIngressRule create 
 +  aws:ec2:SecurityGroupRule cluster-eksNodeIngressRule create 
 +  aws:ec2:SecurityGroupRule cluster-eksExtApiServerClusterIngressRule create 
 +  aws:ec2:SecurityGroupRule cluster-eksNodeClusterIngressRule create 
 +  aws:ec2:SecurityGroupRule cluster-eksNodeInternetEgressRule create 
 +  eks:index:ManagedNodeGroup mng1 create 
 +  pulumi:pulumi:Stack repro-480-pulumi-eks-2-dev create error: Error: A managed node group cannot be created without first setting its role in the cluster's instanceRoles
 +  aws:eks:NodeGroup mng1 create 
 +  pulumi:pulumi:Stack repro-480-pulumi-eks-2-dev create 1 error
 
Diagnostics:
  pulumi:pulumi:Stack (repro-480-pulumi-eks-2-dev):
    error: Error: A managed node group cannot be created without first setting its role in the cluster's instanceRoles
        at /Users/anton/pulumi-eks/nodejs/eks/nodegroup.ts:823:19
        at /Users/anton/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/output.js:250:35
        at Generator.next (<anonymous>)
        at /Users/anton/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/output.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (/Users/anton/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/output.js:17:12)
        at applyHelperAsync (/Users/anton/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/output.js:229:12)
        at /Users/anton/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/output.js:183:65
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
 ```

That is, we triggered exactly the pathway of throw from apply, and its' reported okay to the end user.

```
    nodegroupRole.apply(role => {
        if (!role) {
            throw new Error(`A managed node group cannot be created without first setting its role in the cluster's instanceRoles`);
        }
    });
```

**Comment by t0yv0** [comment]
I guess maybe the issue is with deployment more so than just preview, let me try deploying the example.

**Comment by t0yv0** [comment]
No more information here after a lot more tinkering. Normally `preview` gates `up` so error is consistent. I made the error disappear making it conditional on `pulumi.runtime.isDryRun`, the behavior of `up` was reasonable.

I suggest we close as "cannot reproduce" unless anyone has better ideas.

**Comment by justinvp** [comment]
> I suggest we close as "cannot reproduce" unless anyone has better ideas.

Sounds good to me! Thanks!
