### ISSUE TITLE
createManagedNodeGroup disable node group auto naming

### ISSUE THREAD

**Issue by Embraser01** [pulumi/pulumi-eks#491]
### Problem description

A managed node group created throuh `createManagedNodeGroup` will not have an auto generated name on AWS.

The issue is the same as #294 but is caused by 

https://github.com/pulumi/pulumi-eks/blob/4498d12d103a76f7b7cf4bd70bb0a061d005dcd6/nodejs/eks/nodegroup.ts#L850

introduced in #302:

> Refactoring the managed node group API to simplify its use (options in role vs role.ARN, make parent arg optional, **and default node group name**).

It causes the node group to be deleted before being replaced in case the config change (e.g. isntanceType). Is there a reason to not auto name it?

### Reproducing the issue

Creating a node group and changing it's instanceType should reproduce the issue.

### Suggestions for a fix

Removing the fallback to `name` should work.

**Comment by leezen** [comment]
The fix you suggest makes sense and autonaming it here would help with what you're describing. Happy to take a PR here if you'd like to submit one?
