### ISSUE TITLE
Python: Unable to send rolemapping_args to eks module.

### ISSUE THREAD

**Issue by abhilash76760** [pulumi/pulumi-eks#506]
### Problem description

I am facing issue while adding rolemappings for the eks cluster using pulumi-eks module using python.

packages used:

pulumi>=2.0.0,<3.0.0
pulumi-aws==3.19.2
pulumi-eks==0.21.0

My code is listed below:

import pulumi
import yaml
from pulumi_aws import eks, ec2, get_availability_zones, iam
import pulumi_eks as k8s
import json

eks_cluster = k8s.Cluster('eks-cluster',
vpc_id=vpc.id,
public_subnet_ids=subnet_ids,
desired_capacity=2,
public_access_cidrs=['0.0.0.0/0'],
min_size=2,
max_size=2,
instance_type='t3.micro',
instance_profile_name=testProfile,
cluster_security_group=eks_security_group.id,
role_mappings=k8s.RoleMappingArgs(
groups: ['system:masters'],
role_arn: 'arn:aws:iam::xxxxxx:role/aviatrix-role-app',
username: 'pulumi:admin-usr'),
enabled_cluster_log_types=[
"api",
"audit",
"authenticator",
],
)

* I have removed code related to vpc, subnets, IAM as it is not relevant to this.

**Output:**

pulumi:pulumi:Stack (abhi-pulumi-dev):
error: Error: The IAM role mappings provided could not be properly serialized to YAML for the aws-auth ConfigMap

        at /Users/**/.pulumi/plugins/resource-eks-v0.21.0/node_modules/@pulumi/cluster.ts:652:23
        at /Users/**/.pulumi/plugins/resource-eks-v0.21.0/node_modules/@pulumi/pulumi/output.js:249:35
        at Generator.next (<anonymous>)
        at /Users/**/.pulumi/plugins/resource-eks-v0.21.0/node_modules/@pulumi/pulumi/output.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (/Users/**/.pulumi/plugins/resource-eks-v0.21.0/node_modules/@pulumi/pulumi/output.js:17:12)
        at applyHelperAsync (/Users/**/.pulumi/plugins/resource-eks-v0.21.0/node_modules/@pulumi/pulumi/output.js:228:12)
        at /Users/**/.pulumi/plugins/resource-eks-v0.21.0/node_modules/@pulumi/pulumi/output.js:182:65
        at processTicksAndRejections (internal/process/task_queues.js:93:5)

**
I can create a cluster without rolemappings, but I have a requirement to have the rolemappings attached to my eks cluster.

**Comment by abhilash76760** [comment]
CC @justinvp

**Comment by justinvp** [comment]
@abhilash76760, it looks like you're passing a single `RoleMappingArgs` for `role_mappings`, but `role_mappings` is expecting a list.

The following program works for me without error (setting `role_mappings` to a list):

## __main__.py

```python
import pulumi_eks as eks

import iam

role = iam.create_role("example-role")

cluster = eks.Cluster('eks-cluster',
                      role_mappings=[
                          eks.RoleMappingArgs(
                              groups=['system:masters'],
                              role_arn=role.arn,
                              username='pulumi:admin-usr'),
                      ])
```

## iam.py

```python
import json
import pulumi_aws as aws

managed_policy_arns = [
    "arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy",
    "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy",
    "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly",
]

# Creates a role and attaches the EKS worker node IAM managed policies
def create_role(name: str) -> aws.iam.Role:
    role = aws.iam.Role(name, assume_role_policy=json.dumps({
        "Version": "2012-10-17",
        "Statement": [
            {
                "Sid": "AllowAssumeRole",
                "Effect": "Allow",
                "Principal": {
                    "Service": "ec2.amazonaws.com",
                },
                "Action": "sts:AssumeRole"
            }
        ]
    }))

    for i, policy in enumerate(managed_policy_arns):
        # Create RolePolicyAttachment without returning it.
        rpa = aws.iam.RolePolicyAttachment(f"{name}-policy-{i}",
            policy_arn=policy,
            role=role.id)

    return role
```

**Comment by abhilash76760** [comment]
thanks @justinvp , that has solved the problem.
