### ISSUE TITLE
Python: invalid kubeconfig generated

### ISSUE THREAD

**Issue by josh-theorem** [pulumi/pulumi-eks#512]
### Problem description

The kubeconfig produced by the python version isn't valid due to snake casing

### Errors & Logs

When using the emitted config:
```
error: apiVersion must be specified for aws to use exec authentication plugin
```

### Affected product version(s)

Using 2.17.2 python version

### Reproducing the issue

With the following stack:
```py
import pulumi
import pulumi_eks as eks

cluster = eks.Cluster('foo')
pulumi.export('kubeconfig', cluster.kubeconfig)
```
export the config with:

```
$ pulumi export <stackname> kubeconfig > .kubeconfig
$ kubectl --kubeconfig .kubeconfig get nodes
error: apiVersion must be specified for aws to use exec authentication plugin
```

### Suggestions for a fix
This appears to be a result of camelCase -> snake_case conversion going wrong.

Changing `api_version` in the emitted config to `apiVersion` fixes the problem

**Comment by justinvp** [comment]
Sorry for the trouble, @josh-theorem, and thanks for filing the issue. This has been fixed with https://github.com/pulumi/pulumi-eks/pull/502/commits/7eca46deda94b563c5e8d438b431a180d007eabe. An update with the fix will be released soon.
