### ISSUE TITLE
Enable running go acceptance tests in CI

### ISSUE THREAD

**Issue by viveklak** [pulumi/pulumi-eks#521]
We had to disable running the Go acceptance tests in #520 because building the Go examples with the constrained runners is currently problematic. We are expecting to land some improvements to reduce Go build overhead soon at which point we should re-add Go to the test matrix.

This will require:

- [x] Updating pulumi-aws' pulumi/pulumi reference to include https://github.com/pulumi/pulumi/pull/6144
- [x] Ensure pulumi-kubernetes' reference for pulumi/pulumi is updated to include https://github.com/pulumi/pulumi/pull/6144
- [x] pulumi-eks' references for pulumi/pulumi is updated to include https://github.com/pulumi/pulumi/pull/6144

**Comment by universam1** [comment]
might result in #577

**Comment by stack72** [comment]
Closed via #586
