### ISSUE TITLE
Dependencies missing in CONTRIBUTING.md 

### ISSUE THREAD

**Issue by Comradin** [pulumi/pulumi-eks#527]
### Problem description

- I saw an issue in the following documentation: https://github.com/pulumi/pulumi-eks/blob/master/CONTRIBUTING.md

The documentation mentions to run through a list of steps to verify PR before submitting. Which is great. But the Makefile
makes use of the pulumictl binary, which isn't part of the general pulumi distribution and isn't mentioned in the file itself. And it
uses yarn, which may not everybody will have installed.

So, running the mentioned make command will result in two errors for the people like me, unaware of the dependencies.

### Suggestions for a fix

I can provide a PR with an addition to the CONTRIBUTING.md that addresses this.

**Comment by EvanBoyle** [comment]
closed via https://github.com/pulumi/pulumi-eks/pull/528

**Comment by EvanBoyle** [comment]
Thanks for the contribution!
