### ISSUE TITLE
`aws-go-eks-helloworld` example is not working

### ISSUE THREAD

**Issue by kevinawoo** [pulumi/pulumi-eks#545]
On https://github.com/pulumi/pulumi-eks/commit/f3972fd786bff843a69ec2ae4b43f31a862a1680 (master at the time of issue creation), in `./examples/aws-go-eks-helloworld/`

with the yaml
```yaml
# Pulumi.dev.yaml
config:
  aws:region: us-west-2
```

I'm getting an error
```
$ pulumi up
Previewing update (dev)

View Live: https://....

     Type                                   Name                                           Plan       Info
 +   pulumi:pulumi:Stack                    aws-go-eks-helloworld-dev                      create...  error: Error: invocation of aws:ec2/getVpc:getVpc returned an error: invoking aws:ec2/getVpc:getVpc: 1 error occurred:
 +   └─ eks:index:Cluster                   aws-go-eks-helloworld-1                        create
 +      ├─ eks:index:ServiceRole            aws-go-eks-helloworld-1-instanceRole           create
 +      │  ├─ aws:iam:Role                  aws-go-eks-helloworld-1-instanceRole-role      create
 +      │  ├─ aws:iam:RolePolicyAttachment  aws-go-eks-helloworld-1-instanceRole-03516f97  create
 +      │  ├─ aws:iam:RolePolicyAttachment  aws-go-eks-helloworld-1-instanceRole-3eb088f2  create
 +      │  └─ aws:iam:RolePolicyAttachment  aws-go-eks-helloworld-1-instanceRole-e1b295bd  create
 +      ├─ eks:index:ServiceRole            aws-go-eks-helloworld-1-eksRole                create
 +      │  ├─ aws:iam:Role                  aws-go-eks-helloworld-1-eksRole-role           create
 +      │  ├─ aws:iam:RolePolicyAttachment  aws-go-eks-helloworld-1-eksRole-90eb1c99       create
 +      │  └─ aws:iam:RolePolicyAttachment  aws-go-eks-helloworld-1-eksRole-4b490823       create
 +      ├─ eks:index:RandomSuffix           aws-go-eks-helloworld-1-cfnStackName           create
 +      └─ aws:iam:InstanceProfile          aws-go-eks-helloworld-1-instanceProfile        create
```

## Expected behavior
I expect to have a new eks cluster in AWS called `helloworld-dev`

## Current behavior
pulumi isn't able to create any eks clusters because of the error:
```
error: Error: invocation of aws:ec2/getVpc:getVpc returned an error: invoking aws:ec2/getVpc:getVpc: 1 error occurred:
```

## Steps to reproduce
1. clone the project, checkout https://github.com/pulumi/pulumi-eks/commit/f3972fd786bff843a69ec2ae4b43f31a862a1680 (master at the time of issue creation)
2. `cd examples/aws-go-eks-helloworld`
3. create the `Pulumi.dev.yaml`
4. run `pulumi up`

## Context (Environment)
I'm brand new to pulumi, and I'm just trying to get it up and running.
I'm using `go version go1.16 darwin/amd64`

## Affected feature
- language/go
- examples

**Comment by viveklak** [comment]
@kevinawoo hmm I just reran it locally on the same commit with pulumi CLI v2.21.2 and it worked fine. Do you have any more details on the error? The example creates a new EKS cluster using defaults - which essentially results in the nodes being placed in the default VPC. I imagine that is the call that is failing. Any chance you are running with reduced IAM privileges which could hinder that call?

**Comment by kevinawoo** [comment]
I'm using 
```bash
$ pulumi version
v2.22.0
```

My AWS IAM user is `Administrator`, so no problems there

**Comment by kevinawoo** [comment]
@viveklak I'm using:
```bash
$ pulumi version
v2.22.0
```

My AWS IAM user is `Administrator`, so no problems there 🤞 lol.

**Comment by viveklak** [comment]
Specifically the issue was due to no default VPC being available in the account. Generally see issues with actionable error messages - see #546. Closing this in favor of tracking improvements to error messaging there.
