### ISSUE TITLE
Configuration required for v1.7.5 of CNI

### ISSUE THREAD

**Issue by stack72** [pulumi/pulumi-eks#547]
As part of the upgrade to CNI 1.7.5, we set the values for the following to be hard coded:

```
            - name: ENABLE_POD_ENI
              value: 'false'
            - name: AWS_VPC_K8S_CNI_CONFIGURE_RPFILTER
              value: 'false'
            - name: AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG
              value: 'false'
            - name: AWS_VPC_K8S_CNI_EXTERNALSNAT
              value: 'false'
```

We should investigate if these values need to be configurable

**Comment by emiioan** [comment]
Hello,

Thanks for working and having cni 1.7.5 merged into master branch. I tested today and all good on crio runtime but it seems to be a permission issue for workers with docker runtime and selinux enabled. 
I managed to fix the permission issues by adding securitycontext: privileged on true to cni container, as having only the NET_ADMIN capability it's not enough. (https://github.com/aws/amazon-vpc-cni-k8s/issues/1291 ). 
For now we are looking to make some changes to selinux to see if we can make it work without privilege enabled. 

Meanwhile when do you thing we can have this yaml under a tag? Should we expected it to be integrated into v.0.23.0?

Thanks

**Comment by shinebayar-g** [comment]
AFAIK `AWS_VPC_K8S_CNI_EXTERNALSNAT` needs to be `true` when multiple CNIs deployed into cluster.

**Comment by stack72** [comment]
I think after what @shinebayar-g is saying, we need to actually implement these specific configuration options

PR will come shortly

**Comment by emiioan** [comment]
Good, also please check this issue aws/amazon-vpc-cni-k8s#1291, I disabled selinux on ec2 instance node with docker container runtime and I was not able to make it working. As soon as I add privileged: true it works.

**Comment by stack72** [comment]
Hey @emiioan 

so I am not sure from that issue where this needs to go in the yaml - can you give me a hint?

P.

**Comment by stack72** [comment]
ok, I see it - so we should set this as `privileged: false` by default with the ability to override it, right?

**Comment by emiioan** [comment]
Yes, you can add it here https://github.com/pulumi/pulumi-eks/blob/master/nodejs/eks/cni/aws-k8s-cni.yaml#L132  and able to overwrite it will be perfect: 

```
          securityContext:
	    privileged: false
            capabilities:
              add:
                - NET_ADMIN
```

**Comment by stack72** [comment]
Is this false by default or undefined?

**Comment by emiioan** [comment]
hmm, undefined default

**Comment by emiioan** [comment]
We managed to allow through selinux the necessary permissions to allow cni pod to start on docker but it will still be good to add this feature and for sure it will be handy for others out there using docker as runtime. By default security context privilege is not defined in yaml provided by aws, but it will be great if you can add as argument to cluster and pulumi code to compute the yaml at runtime adding "privileged: true" to cni container. Any chances of a new PR and a release in v.0.23.0? :D

**Comment by stack72** [comment]
Hey @emiioan https://github.com/pulumi/pulumi-eks/pull/553

this will go out today :)
