### ISSUE TITLE
Problem running CS sample

### ISSUE THREAD

**Issue by cakriwut** [pulumi/pulumi-eks#550]
I am executing sample, creating default EKS using C#. However, it always failed with following error:

**"providerCredentialOpts and AWS_PROFILE must be set together"**
   error: no resource plugin 'eks-v2.7.8' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource eks v2.7.8`
error: [resource plugin eks-2.7.8] downloading from : 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-eks-v2.7.8-windows-amd64.tar.gz

## Expected behavior

Running> pulumi up  , should create EKS successfully.

## Current behavior

Error.

## Steps to reproduce

1. Install pulumi
2. Set AWS_PROFILE
3. Clone https://github.com/pulumi/pulumi-eks
4. Create new project, and copy the cluster-cs
5. Run pulumi up

## Context (Environment)

1. Running in Windows 10 , with aws-cli/2.0.33 Python/3.7.7 Windows/10 botocore/2.0.0dev37

**Comment by leezen** [comment]
This was fixed in https://github.com/pulumi/pulumi-eks/pull/542 but hasn't been tagged in a release yet. @justinvp Do you mind cutting a release?
