### ISSUE TITLE
AWS EKS with Fargate support ?

### ISSUE THREAD

**Issue by kekhuay** [pulumi/pulumi-eks#556]
I would like to know how to create an AWS EKS with Fargate support for the current release ?.
It's looks like the `fargate: true` in this blog does not work anymore.
https://www.pulumi.com/blog/aws-eks-managed-nodes-fargate/

**Comment by lukehoban** [comment]
This is still supported in the same form described in the blog post and in the example linked above. Closing this out, but feel free to open a new issue with more details if anyone is seeing unexpected behaviour for Fargate support in EKS clusters.
