### ISSUE TITLE
Make available for Python

### ISSUE THREAD

**Issue by pgavlin** [pulumi/pulumi-eks#57]
Just what it says on the tin.

**Comment by lukehoban** [comment]
Current plan is to do this based on the cross-langauge libraries approach in https://github.com/pulumi/pulumi/issues/2430 and https://github.com/pulumi/pulumi/pull/3711.

**Comment by leezen** [comment]
We shipped support for Python in [pulumi-eks](https://pypi.org/project/pulumi-eks/)  and documented in https://www.pulumi.com/docs/reference/pkg/eks/

We need to update the `README` and docs to reflect this.
