### ISSUE TITLE
Typo/Missing word in Error Message

### ISSUE THREAD

**Issue by floknip** [pulumi/pulumi-eks#578]
https://github.com/pulumi/pulumi-eks/blob/4598fed19874f6ce9e44a33b55c87479d2427d7e/nodejs/eks/cluster.ts#L1390

Missing word "in" in the error message

Should it be something like "Please specify the profile in providerCredentialOpts" instead of 
"Please specify this profile providerCredentialOpts."?

**Comment by lblackstone** [comment]
Fixed in #579
