### ISSUE TITLE
Support ARM Instances in default NodeGroup

### ISSUE THREAD

**Issue by pquerna** [pulumi/pulumi-eks#582]
I think this block of code, which is using SSM to fetch the regional AMI ID, needs change to support ARM instances:
https://github.com/pulumi/pulumi-eks/blob/4f4a75b17de98cf2f9c3d34a960b59503cbc4f0a/nodejs/eks/nodegroup.ts#L470-L478

Specifically, if the InstnaceType is set to an ARM type, the `amiType` needs to be `amazon-linux-2-arm64` 

Without this change, the cloudformation get stuck trying to create the node group, which fails because the AMI picked is invalid for ARM instances.

**Comment by lobshunter** [comment]
Met the same issue, hope this will be fixed soon.
