### ISSUE TITLE
EKS Add-on support (coredns, etc)

### ISSUE THREAD

**Issue by almson** [pulumi/pulumi-eks#587]
EKS now supports coredns, kube-proxy, and VPC CNI as managed add-ons. They're exposed through the API. It would be great to be able to declare them and update them using Pulumi.

https://aws.amazon.com/about-aws/whats-new/2021/05/eks-add-ons-now-support-coredns-kube-proxy/

**Comment by lukehoban** [comment]
Great suggestion - would be great to add these to the `@pulumi/eks` API directly.
