### ISSUE TITLE
Destroy fails when AWS resources cannot be found

### ISSUE THREAD

**Issue by metral** [pulumi/pulumi-eks#59]
When destroying a k8s cluster, if for some reason an AWS resource gets removed and Pulumi isn't aware of it, it will ultimately cause the destroy to fail if it cannot find the resource:

```
$ pul destroy
Previewing destroy (eks-demo):

     Type                                  Name                      Plan
 -   pulumi:pulumi:Stack                   eks-hello-world-eks-demo  delete
 -   ├─ eks:index:Cluster                  helloWorld                delete
 -   │  ├─ pulumi-nodejs:dynamic:Resource  helloWorld-cfnStackName   delete
 -   │  ├─ eks:index:ServiceRole           helloWorld-eksRole        delete
 -   │  └─ eks:index:ServiceRole           helloWorld-instanceRole   delete
 -   └─ aws-infra:network:Network          vpc                       delete
 -      ├─ aws:ec2:InternetGateway         vpc                       delete
 -      ├─ aws:ec2:Eip                     vpc-nat-1                 delete
 -      ├─ aws:ec2:Eip                     vpc-nat-0                 delete
 -      └─ aws:ec2:Vpc                     vpc                       delete

Resources:
    - 10 to delete

Do you want to perform this destroy? yes
Destroying (eks-demo):

     Type                        Name                      Status                  Info
     pulumi:pulumi:Stack         eks-hello-world-eks-demo
 -   └─ aws:ec2:InternetGateway  vpc                       **deleting failed**     1 error

Diagnostics:
  aws:ec2:InternetGateway (vpc):
    error: Plan apply failed: deleting urn:pulumi:eks-demo::eks-hello-world::aws-infra:network:Network$aws:ec2/internetGateway:InternetGateway::vpc: Error waiting for internet gateway (igw-0305d3fc89e01176e) to detach: couldn't find resource (31 retries)
```

**Comment by naineel** [comment]
+1 got bitten by this

**Comment by lukehoban** [comment]
Does `pulumi refresh` help in this case?

Is the scenario that the `InternetGateway` (or other resource) is manually deleted from AWS behind the scenes?  If so, curious what is the desired/suggested behaviour in this case?

**Comment by clstokes** [comment]
I got an EKS cluster into a similar start and also hit this that I can't destroy when resources can't be found. A `refresh` also fails.

Full refresh output - https://gist.github.com/clstokes/e7eb00ae363e9a1974ee5be3679b9944

**Comment by lukehoban** [comment]
In @clstokes' repo,  the fact that `pulumi refresh` fails due to the cluster being unavailable seems like a separate bug we should open and track.  Ideally this would not cause a failure - ideally the `refresh` would warn on these instead of failing.

I assume that the original issue here *should* be solved by `pulumi refresh` and that anything that prevents `refresh` from working here is a bug in `refresh`.  With our current model of not running `refresh` implicitly, it will be the case that when resources are deleted manually behind the scenes, it will in general be necessary to run `pulumi refresh` to reconcile those changes into Pulumi.

**Comment by lukehoban** [comment]
I'm going to close this out - as I believe the original issue is expected, and requires that the user do` pulumi refresh` or `pulumi state delete` to reconcile their checkpoint with the cloud provider prior to `pulumi destroy`.  

https://github.com/pulumi/pulumi/issues/2247 is tracking doing a refresh automatically prior to preview/update/destroy.  That would be the only thing that could fundamentally "solve" the original issue here.

The other issues referenced along the way sound like unrelated potential bugs, but there are not details on repro steps for those here.  Let's open new issues on those if needed.
