### ISSUE TITLE
Setting userMappings overwrites roleMappings and deletes instance role mapping

### ISSUE THREAD

**Issue by almson** [pulumi/pulumi-eks#593]
Title pretty much sums it up. The cause is that there isn't any kind of merge [when user mappings are added to `aws-auth`](https://github.com/pulumi/pulumi-eks/blob/bf28499c4eb2a3e5e18ee50a76c591803beeeb93/nodejs/eks/cluster.ts#L668) Workaround is to just put user arns into `roleMappings` as if they're role arns.

**Comment by infin8x** [comment]
Thanks for reporting this @almson. Do you have a repro you could share with us?

**Comment by mikhailshilkov** [comment]
Since we haven't heard back, I'll go ahead and close this issue as stale
