### ISSUE TITLE
Update managed node group version

### ISSUE THREAD

**Issue by michael-barker** [pulumi/pulumi-eks#594]
I'm unable to find a way to update managed node groups after updating the cluster version. I'd like to be able to pass the EKS version to a managed node group. This would allow the cluster to be updated first and then update the managed node group to match the cluster version. The only workaround I currently have is update the managed node group directly in the AWS Console or using eksctl.

https://docs.aws.amazon.com/eks/latest/userguide/update-managed-node-group.html

**Comment by infin8x** [comment]
Thanks @michael-barker for filing this. I've added it to the backlog so we can track and prioritize it.

**Comment by flostadler** [comment]
The [`ManagedNodeGroup`](https://www.pulumi.com/registry/packages/eks/api-docs/managednodegroup/#version_nodejs) has a parameter for setting the cluster version.
I'll create a small example to verify it's working as expected.

**Comment by flostadler** [comment]
Yes, you can use the `version` parameter to update the version of a `ManagedNodeGroup`. In the example below I first created a cluster with kube version `1.29`, then updated that to `1.30` and afterwards updated the node group to `1.30` as well.

```
const cluster = new eks.Cluster("example-managed-nodegroups", {
    skipDefaultNodeGroup: true,
    deployDashboard: false,
    vpcId: vpc.vpcId,
    publicSubnetIds: vpc.publicSubnetIds,
    // Private subnets will be used for cluster nodes
    privateSubnetIds: vpc.privateSubnetIds,
    instanceRoles: [role],
    version: "1.30",
});

const managedNodeGroup1 = eks.createManagedNodeGroup(
    "example-managed-ng1",
    {
        cluster: cluster,
        nodeGroupName: "aws-managed-ng1",
        nodeRoleArn: role.arn,
        version: "1.30", // <-- updated from 1.29
    },
    cluster
);
```
