### ISSUE TITLE
Add support for diskType to NodeGroup and ManagedNodeGroup

### ISSUE THREAD

**Issue by Kurounin** [pulumi/pulumi-eks#597]
## Affected feature

When creating a new `NodeGroup` or `ManagedNodeGroup` using `createManagedNodeGroup` there's no option to set the diskType (as seen here https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest/submodules/node_groups). By adding the option I would like to start using gp3 volumes instead of gp2 for node instances.

**Comment by gcaride** [comment]
Yes! We need this, since we can select the amount of throughput and IOPS

**Comment by tma-unwire** [comment]
This would be really nice as it wil speed up my cluster significantly.

**Comment by roothorp** [comment]
This feature has been present for a while, but the issue wasn't closed. Fixed in #641.
