### ISSUE TITLE
Ability to configure apiVersion in kubeconfig exec in cluster.ts

### ISSUE THREAD

**Issue by TheMasterR** [pulumi/pulumi-eks#599]
It would be useful to be able to **configure** the [apiVersion](https://github.com/pulumi/pulumi-eks/blob/b4bdb26981fe63328b6046d6e0947d99e4a08a67/nodejs/eks/cluster.ts#L225) in kubeconfig for AWS credentials, as amazon changes the [version](https://github.com/aws/aws-cli/commit/b82ba414a848b6d4ff6cc49ccabc76e5d5d24e11) from time to time.

Having mismatch apiVersion will result in an error,
_EG_:
```
kubernetes:apps/v1:Deployment XXX **creating failed** [diff: ~spec]; error: configured Kubernetes cluster is unreachable: unable to load schema information from the API server: Get "https://XXX.eu-central-1.eks.amazonaws.com/openapi/v2?timeout=32s": getting credentials: exec plugin is configured to use API version client.authentication.k8s.io/v1alpha1, plugin returned version client.authentication.k8s.io/v1beta1
```

## Affected feature

EKS Cluster -> kubeconfig -> AWS credentials -> apiVersion

**Comment by bcmyers** [comment]
FWIW, I'm also hitting this problem; so interested in being able to configure API version.

**Comment by lukehoban** [comment]
This is interesting.  It seems like the `aws-cli` change in https://github.com/aws/aws-cli/commit/b82ba414a848b6d4ff6cc49ccabc76e5d5d24e11 is a breaking change in a patch release.  The `aws` tool no longer will work with any existing `kubeconfig` if I understand correctly.  And if the kubeconfig is updated, it will not work with any earlier `kubeconfig`.  

Ah - indeed - see https://github.com/aws/aws-cli/issues/6308.  It looks like another patch release was published to revert the change linked here - which should allow this to continue working.

I see they are looking at adding a flag you can pass to opt in to a version - which we may be able to use when they revisit how to correctly re-introduce this feature.

For now though, I believe we do not want to make any change in `pulumi-eks` here.

**Comment by lukehoban** [comment]
Closing this out as currently by-design.  If there's a scenario for manually controlling this outside of dealing with this breaking chance, definitely interested in the details.  I believe in general it is going to be better for this package to ensure it always generates a kubeconfig that will work correctly - which might not be *just* about this version number.
