### ISSUE TITLE
Add `enablePrefixDelegation` option to `VpcCniOptions`

### ISSUE THREAD

**Issue by davidroth** [pulumi/pulumi-eks#608]
In order to [increase pod-density](https://docs.aws.amazon.com/eks/latest/userguide/cni-increase-ip-addresses.html), I need to set an environment variable for the `aws-node` DaemonSet.

See: https://docs.aws.amazon.com/eks/latest/userguide/cni-increase-ip-addresses.html

Using kubectl, this is a one-liner:

`kubectl set env daemonset aws-node -n kube-system ENABLE_PREFIX_DELEGATION=true`

As I am creating the cluster via pulumi, I am searching for a way to set the environment variable via pulumi.
Is there any way I can set this environment variable using pulumi? Or is there another workaround to integrate this into the pulumi program?

**Comment by lblackstone** [comment]
This looks like another use case for https://github.com/pulumi/pulumi-kubernetes/issues/264

We don't currently have a great way of setting the env var on an unmanaged (i.e., not tracked by Pulumi) k8s resource.

As a current workaround, the EKS package internally uses `kubectl` for a similar case to this: https://github.com/pulumi/pulumi-eks/blob/v0.32.0/nodejs/eks/cmd/provider/cni.ts

**Comment by davidroth** [comment]
@lblackstone After reviewing [cni.ts](https://github.com/pulumi/pulumi-eks/blob/86861e6cb6091e97d08828a444bb70087a8701f3/nodejs/eks/cmd/provider/cni.ts#L47) I think it would make sense to add a `enablePrefixDelegation` property to [VPcCniOptions](https://github.com/pulumi/pulumi-eks/blob/master/nodejs/eks/cni.ts) and render that in [cni.ts](https://github.com/pulumi/pulumi-eks/blob/86861e6cb6091e97d08828a444bb70087a8701f3/nodejs/eks/cmd/provider/cni.ts#L47)

**Comment by davidroth** [comment]
The properties `WARM_PREFIX_TARGET`, `WARM_IP_TARGET` and `MINIMUM_IP_TARGET` should also be added. [See also](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/docs/prefix-and-ip-target.md).

**Comment by davidroth** [comment]
merged some while ago: https://github.com/pulumi/pulumi-eks/pull/618
