### ISSUE TITLE
Use the latest VPC_CNI Version 1.9

### ISSUE THREAD

**Issue by davidroth** [pulumi/pulumi-eks#610]
When creating a new eks cluster via pulumi, the VPC-CNI Version "1.7" is used, although the recommended version is now "1.9".
See the [docs](https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html):

![image](https://user-images.githubusercontent.com/338856/128875364-78279893-98f2-4f0e-8fc0-d9c7584d0b82.png)

This was very confusing for me as I expected the latest version when creating a new eks cluster with the kubernetes version "1.21".

The default VPC-CNI version should be upgraded to "1.9": https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html

**Comment by davidroth** [comment]
@leezen Does not work. It will still use 1.7.x although I set `useDefaultVpcCni` to `true`:

![image](https://user-images.githubusercontent.com/338856/129001985-ac21b724-f250-44b5-8479-33ebc33610f4.png)

**Comment by davidroth** [comment]
Setting `vpcCniOptions.Image` to `602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:v1.9.0` works for the pod container, but not for the init container. The init container stays on 1.7.5.

![image](https://user-images.githubusercontent.com/338856/129002770-2ef8e6ad-8000-41bd-a1d0-b0ffd76e2b0a.png)

![image](https://user-images.githubusercontent.com/338856/129003094-c9e22c89-29ae-4e13-ba1f-6d207731acbd.png)

**Comment by alex-hunt-materialize** [comment]
@davidroth I've filed https://github.com/pulumi/pulumi-eks/issues/619 to track adding support for setting the init container image, and I've opened https://github.com/pulumi/pulumi-eks/pull/617 which provides that support.

**Comment by stack72** [comment]
We are currently on 1.11 of the CNI https://github.com/pulumi/pulumi-eks/commit/c3533505e789742bcf060ba84374eade60b305f3 so I am going to close this out - sorry we didn't report back earlier!
