### ISSUE TITLE
Add `kubeletExtraArgs` to ManagedNodeGroup opts

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-eks#611]
We should add the `kubeletExtraArgs` parameter to the ManagedNodeGroup opts.

--------

> After looking at the code in [nodegroup.ts](https://github.com/pulumi/pulumi-eks/blob/master/nodejs/eks/nodegroup.ts#L199), noticed that `NodeGroup` already supports `kubeletExtraArgs?: string;`.
Exactly what I need for the managed node group api. Unfortunately, [the managed node group api](https://github.com/pulumi/pulumi-eks/blob/master/nodejs/eks/nodegroup.ts#L686) is very limited and has no `kubeletExtraArgs`.

_Originally posted by @davidroth in https://github.com/pulumi/pulumi-eks/issues/609#issuecomment-896070796_

**Comment by bothra90** [comment]
@roothorp / @stack72 : Is there an ETA on this? We need this config to set some "unsafe" sysctls for running some db workloads.

**Comment by gopikrishna2403** [comment]
Any update on this issue? Really looking forward for this enhancement

**Comment by defyjoy** [comment]
Is there any updates to this ?

**Comment by munjalpatel** [comment]
@lblackstone, any updates here? We need to adjust `max-pods` on EKS managed node group.
Are there any workarounds we can use in the meanwhile?

**Comment by lblackstone** [comment]
This feature is on the roadmap for the 1.0 release, but we don't have an ETA at this time. Unfortunately, I don't know of a workaround since the arg you need is not exposed. It's possible that you could add the required key with a [transformation](https://www.pulumi.com/docs/intro/concepts/resources/options/transformations/) on the `ManagedNodeGroup`, but I haven't tried it.

Aside from that, we'd be glad to accept a pull request to add that parameter.
1. Add the parameter to the [ManagedNodeGroupOptions type](https://github.com/pulumi/pulumi-eks/blob/v0.42.7/nodejs/eks/nodegroup.ts#L1096-L1154)
2. Add the parameter to the [schema](https://github.com/pulumi/pulumi-eks/blob/v0.42.7/provider/cmd/pulumi-resource-eks/schema.json#L917-L1012)
3. Regenerate the SDKs with the updated schema

**Comment by munjalpatel** [comment]
@lblackstone I'll submit a PR. How do I regenerate the SDKs?

**Comment by munjalpatel** [comment]
@lblackstone PR #809 submitted.

**Comment by lblackstone** [comment]
Oh, sorry about that, but thanks for jumping in to work on it! It's been awhile since I've looked at this package, and I didn't notice that the NodeGroup was the resource from the aws package rather than the local class.

Unfortunately, it looks like the actual fix would be a more involved change. There's a terraform package that shows how it could be done. 
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v18.30.3/modules/eks-managed-node-group/main.tf#L57
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v18.30.3/modules/_user_data/main.tf

This would require using the `ec2.LaunchTemplate` to configure the userdata appropriately, and then setting the [launchTemplate](https://www.pulumi.com/registry/packages/aws/api-docs/eks/nodegroup/#launchtemplate_nodejs) argument on the NodeGroup creation.

**Comment by defyjoy** [comment]
This should have some traction as lot of reactions on this and is a much awaited issue which is stalling lot of configuration related to kubelet .Specially something like `--max-pods =110` which can easily overcome the issue of tiny pod allocation size per nodes . 


Please do let us know since this is very important to be able to control the kubelets for increasing the pod density across managed node group and we are stuck with Pulumi in spite terraform module already has the solution for this .

**Comment by MikkelVase01** [comment]
> This should have some traction as lot of reactions on this and is a much awaited issue which is stalling lot of configuration related to kubelet .Specially something like `--max-pods =110` which can easily overcome the issue of tiny pod allocation size per nodes .
> 
> Please do let us know since this is very important to be able to control the kubelets for increasing the pod density across managed node group and we are stuck with Pulumi in spite terraform module already has the solution for this .

Exactly

**Comment by defyjoy** [comment]
Is there any traction to this yet ? We are still hanging in between with this one property `kubeletExtraArgs`

**Comment by philprime** [comment]
Is there any update on this?

We are currently using something like this ot increase the max pod limit.

```
import * as eks from '@pulumi/eks';

let cluster: eks.Cluster;
cluster.createNodeGroup(`...`, {
  ...
  kubeletExtraArgs: '--max-pods=110',
  bootstrapExtraArgs: `--use-max-pods false --dns-cluster-ip 10.100.0.10`,
  ...
})
```

Unfortunately this approach does not allow to use the default Pulumi options, like `ignoreChanges`
