### ISSUE TITLE
ManagedNodeGroup Resource properties lacking parity with base AWS EKS NodeGroup Resource properties

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi-eks#612]
There are properties in the base AWS-EKS NodeGroup resource that are not exposed in the Pulumi-EKS ManagedNodeGroup resource (for Python, Go and .NET) but should be.
There are a couple of existing issues to track a couple of these missing properties. 
This issue is meant to collect all the missing properties into a single place.

These missing properties (and existing issues were applicable) are:
- capacity_type (https://github.com/pulumi/pulumi-eks/issues/565)
- node_group_name_prefix
- tags_all
- taints (https://github.com/pulumi/pulumi-eks/issues/583)

Issue https://github.com/pulumi/pulumi-eks/issues/565 provides good background on why the discrepancies exist and how to address them.

**Comment by lukehoban** [comment]
> `tags_all`

Note that this one was not addressed in #614, but also shouldn't actually be there in the first place in `aws.eks.NodeGroup` per https://github.com/pulumi/pulumi-aws/issues/1594.
