### ISSUE TITLE
unknown resource type eks:index:Cluster only in Python

### ISSUE THREAD

**Issue by matt-slalom** [pulumi/pulumi-eks#615]
I'm building an EKS cluster with Windows nodes attached. I've got two versions of the code, one in Python, the other in TypeScript. The TypeScript seems to work fine. The Python code throws an error.

## Steps to reproduce
Gist with both Python and TypeScript versions: https://gist.github.com/matt-slalom/3d81c98e4835064db768f2a4a51a76f3

```
% pulumi version
v3.10.2
```

Run `pulumi up` on the Python version (the TypeScript version produces no errors).

Expected: I expected Pulumi to offer to create the resources
Actual: 
```
      File "/Users/username/directory/pulumi_eks_python/venv/lib/python3.8/site-packages/pulumi/runtime/settings.py", line 254, in handle_grpc_error
        raise grpc_error_to_exception(exn)
    Exception: unknown resource type eks:index:Cluster
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

Full error output is here: https://gist.github.com/matt-slalom/94f72cf1fcf356bbdf00972846f5af17

If I'm doing something really dumb, please let me know!

**Comment by matt-slalom** [comment]
The problem is specific to the NodeGroup. If I comment that out in the Python code, the preview completes without errors.

**Comment by leezen** [comment]
@matt-slalom I think you want to use `cluster.core` per the type definition described in https://www.pulumi.com/docs/reference/pkg/eks/nodegroup/ (see also https://www.pulumi.com/docs/reference/pkg/eks/cluster/#core_python) -- does that work for you if you switch to using that?

**Comment by matt-slalom** [comment]
Hi @leezen. Well, supplying `cluster.core` to the `cluster=` parameter moves me forward a step, but now I'm getting:
`details = "The NodeGroup's nodeSecurityGroup and the cluster option nodeSecurityGroupTags are mutually exclusive. Choose a single approach"`

That error seems related to one reported by someone else here: https://github.com/pulumi/pulumi-eks/issues/585

**Comment by matt-slalom** [comment]
Good news: removing `node_security_group` from NodeGroup seems to work, so it's apparently unrelated to #585.

Thanks @leezen for the pointer on `cluster.core`!
