### ISSUE TITLE
Duplicate externalSnat and cniExternalSnat VpcCniOptions arguments, which fight over setting the same environment variable

### ISSUE THREAD

**Issue by alex-hunt-materialize** [pulumi/pulumi-eks#624]
Both the `externalSnat` and `cniExternalSnat` arguments when configuring the `VpcCniOptions` set the `AWS_VPC_K8S_CNI_EXTERNALSNAT` environment variable in the CNI image. The `externalSnat` does not set a default if it isn't provided, and the `cniExternalSnat` will overwrite that value, even if not provided.

nodejs/eks/cmd/provider/cni.ts
```
    if (args.externalSnat) {
        env.push({name: "AWS_VPC_K8S_CNI_EXTERNALSNAT", value: args.externalSnat ? "true" : "false"});
    }
```
```
    if (args.cniExternalSnat) {
        env.push({name: "AWS_VPC_K8S_CNI_EXTERNALSNAT", value: args.cniExternalSnat ? "true" : "false"});
    } else {
        env.push({name: "AWS_VPC_K8S_CNI_EXTERNALSNAT", value: "false"});
    }
```

We should remove one of these, and ensure that it sets the environment variable to the default if a user doesn't specify the value.

## Steps to reproduce

1. Try to set `externalSnat` to true.
2. Do not set `cniExternalSnat`.

Expected: `AWS_VPC_K8S_CNI_EXTERNALSNAT="true"`
Actual: `AWS_VPC_K8S_CNI_EXTERNALSNAT="false"`

**Comment by shinebayar-g** [comment]
Yep. Just went through the code and found out `cniExternalSnat` & `externalSnat` are setting the same value `AWS_VPC_K8S_CNI_EXTERNALSNAT`
