### ISSUE TITLE
eks namespace with provider in python not working, but eks namespace with provider in typescript works.

### ISSUE THREAD

**Issue by tusharshahrs** [pulumi/pulumi-eks#662]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details
EKS with typescript and having a [namespace](https://github.com/tusharshahrs/pulumi-home/blob/helm/aws-classic-ts-eks/index.ts#L14) works.
EKS with python and having a [namespace](https://github.com/tusharshahrs/pulumi-home/blob/helm/aws-classic-py-eks/__main__.py#L25) configured almost the exact same way, doesn't pass `pulumi preview`.  The following error message is thrown in python:

```
raise ValueError(
    ValueError: Attempted to register resource kubernetes:core/v1:Namespace with a provider for '<pulumi.output.Output object at 0x10c216700>'
```

### Steps to reproduce

1. Validate the eks stack works in typescript  
     `git clone git@github.com:tusharshahrs/pulumi-home.git`
     `cd aws-classic-ts-eks`
1. `pulumi about` in typescript stack
```
 pulumi about
CLI          
Version      3.24.1
Go Version   go1.17.6
Go Compiler  gc

Plugins
NAME        VERSION
aws         4.37.2
eks         0.37.0
kubernetes  3.15.1
nodejs      unknown

Host     
OS       darwin
Version  11.6.3
Arch     x86_64
..
..
Backend  
Name     pulumi.com
URL      https://app.pulumi.com/myuser
User     myuser

NAME                VERSION
@pulumi/eks         0.37.0
@pulumi/kubernetes  3.15.1
@pulumi/pulumi      3.24.1
@types/node         14.18.10

This project is written in nodejs (/usr/local/bin/node v17.4.0)
```
1. Stand up the stack in `typescript`
   `pulumi stack init dev`
   `npm install`
   `pulumi config set aws:region us-east-2`
   `pulumi up -y`
   Wait ~12 minutes and the `namespace` will get created.  The output will show it
1. Everything works in `typescript`. 
1. Try to stand up the eks stack in python
  `git clone git@github.com:tusharshahrs/pulumi-home.git`
  `cd aws-classic-py-eks`
1. `pulumi about` in python stack
```
CLI          
Version      3.24.1
Go Version   go1.17.6
Go Compiler  gc

Plugins
NAME        VERSION
aws         4.37.2
eks         0.37.0
kubernetes  3.15.2
python      unknown

Host     
OS       darwin
Version  11.6.3
Arch     x86_64

This project is written in python (/usr/local/bin/python3 v3.9.10)

Current Stack: dev
Backend  
Name     pulumi.com
URL      https://app.pulumi.com/myuser
User     myuser

NAME        VERSION
pip         22.0.3
pulumi-eks  0.37.0
setuptools  60.8.2
wheel       0.37.1
```
1. Stand up the stack in `python`
   `pulumi stack init dev`
   `python3 -m venv venv`
   `source venv/bin/activate`
    `pip3 install -r requirements.txt`
    `pulumi config set aws:region us-east-2`
1. Uncomment [aws_ns_broken](https://github.com/tusharshahrs/pulumi-home/blob/helm/aws-classic-py-eks/__main__.py#L25)
1. Run `pulumi up` and the `preview` will fail with:
    ```
    raise ValueError(
       ValueError: Attempted to register resource kubernetes:core/v1:Namespace with a provider for '<pulumi.output.Output object at 
    0x10c216700>'
   ```
1. We have a workaround, meaning we can comment OUT the [last line](https://github.com/tusharshahrs/pulumi-home/blob/helm/aws-classic-py-eks/__main__.py#L25).
1. **Question**.  Should a user expect the `python` code for namespace to work similar as typescript or this expected behavior in python?

Expected: 
Eks with namespace in python works the same as eks with namespace in typescript.

Actual: 
Python throws this error on preview:
```
    raise ValueError(
       ValueError: Attempted to register resource kubernetes:core/v1:Namespace with a provider for '<pulumi.output.Output object at 
    0x10c216700>'
 ```

**Comment by justinvp** [comment]
The main problem is that the `ResourceOptions`' `provider` arg doesn't yet accept `Output[ProviderResource]`, which is tracked by https://github.com/pulumi/pulumi/issues/7012.

In the meantime, this can be worked around by creating a new instance of the `pulumi_kubernetes.Provider` using the `Cluster`'s `kubeconfig` output:

```python
import json

from pulumi import ResourceOptions
from pulumi_eks import Cluster
from pulumi_kubernetes import Provider
from pulumi_kubernetes.core.v1 import Namespace

cluster = Cluster("test")

provider = Provider("eks-k8s", kubeconfig=cluster.kubeconfig.apply(lambda k: json.dumps(k)))

namespace = Namespace("test", opts=ResourceOptions(provider=provider))
```

Since the `Cluster.provider` output isn't really usable currently given https://github.com/pulumi/pulumi/issues/7012, we're considering removing it: https://github.com/pulumi/pulumi-eks/issues/602.

**Comment by markfickett** [comment]
Linking to this ticket or stating the workaround in the [docs for the Cluster.provider](https://www.pulumi.com/registry/packages/eks/api-docs/cluster/) attribute (and ideally the Namespace too) would be a great help, as long as this issue remains.

**Comment by danielrbradley** [comment]
The `provider` output property was removed in https://github.com/pulumi/pulumi-eks/pull/746

Closing this issue as complete but have created a new issue to capture adding a helpful example to the docs: https://github.com/pulumi/pulumi-eks/issues/812
