### ISSUE TITLE
ManagedNodeGroup misses capacityRebalance and replacementStrategy

### ISSUE THREAD

**Issue by geNAZt** [pulumi/pulumi-eks#672]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently i try to use a spot managed node group which auto balances itself to the lowest price. This should be possible with https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-fleet-capacity-rebalance.html  / https://docs.aws.amazon.com/autoscaling/ec2/userguide/ec2-auto-scaling-capacity-rebalancing.html . So setting capacityRebalance to lowest-price and replacementStrategy to launch-before-terminate.

Currently both are not settable via ManagedNodeGroup but can be set in AutoscalingGroups.

### Affected area/feature

ManagedNodeGroup

**Comment by better0332** [comment]
I need this.

**Comment by flostadler** [comment]
EKS managed node groups should have capacity rebalance turned on by default.

AWS does not expose `replacementStrategy` for managed node groups as far as I can tell: https://awscli.amazonaws.com/v2/documentation/api/2.0.34/reference/eks/create-nodegroup.html
