### ISSUE TITLE
pulumi-aws 5.1.0 and pulumi-eks==0.37.1 error resolution impossible

### ISSUE THREAD

**Issue by tusharshahrs** [pulumi/pulumi-eks#674]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details
Updating `pulumi-aws` to version `5.1.0` causes a package mismatch with `pulumi-eks`
We get the following error:
```
ERROR: Cannot install pulumi-aws<6.0.0 and >=5.1.0 and pulumi-eks==0.37.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested pulumi-aws<6.0.0 and >=5.1.0
    pulumi-eks 0.37.1 depends on pulumi-aws<5.0.0 and >=4.15.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

### Steps to reproduce

1. `git clone -b eksmismatch https://github.com/tusharshahrs/pulumi-home/tree/eksmismatch`
2. `cd aws-classic-py-eks-spot-mg`
3. `pip3 install -r requirements.txt` -> ERROR will get thrown here

4. Error due to the following code in [requirements.txt ](https://github.com/tusharshahrs/pulumi-home/blob/eksmismatch/aws-classic-py-eks-spot-mg/requirements.txt#L2-L3)

Expected: 
pip3 install work
Actual: 
```
...
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Comment by stack72** [comment]
@tusharshahrs this is closed via v0.39.0 release
