### ISSUE TITLE
Cluster(.node_root_volume_type) not passed launch configuration

### ISSUE THREAD

**Issue by tma-unwire** [pulumi/pulumi-eks#677]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

When creating a new cluster using eks.Cluster(..., node_root_volume_type='gp3', ...) the volume type is not passed to the corresponding AWS Launch configuration.

### Steps to reproduce
Expected: use gp3 as volume type in Launch Configuration
Actual: uses gp2

**Comment by stack72** [comment]
Related to #750

**Comment by markfickett** [comment]
Looks somewhat related to #784 too.

**Comment by rquitales** [comment]
We expect this to be supported once #1183 lands. Note though that we will not have `node_root_volume_type` as a field within the cluster resource. Instead, this can be set within the `cluster.node_group_options.node_root_volume_type` field.
