### ISSUE TITLE
Support for EKS IMDSv2

### ISSUE THREAD

**Issue by NArnott** [pulumi/pulumi-eks#682]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

AWS announced in 2020 support for EKS Node Groups to disable IMDSv1 (allowing only IMDSv2). I don't current see any support for that in Pulumi's EKS managed node group.

AWS Annoucement: https://aws.amazon.com/about-aws/whats-new/2020/08/amazon-eks-supports-ec2-instance-metadata-service-v2/

### Affected area/feature

Pulumi.Aws.Eks.**NodeGroup**

**Comment by shed909** [comment]
I'd love to see this implemented. It's the only thing it doesn't do that I require for compliance, and it would be great to not have to try and replicate what `pulumi-eks` is doing with `pulumi-aws`.

**Comment by igordrnobrega** [comment]
Updates on this?
