### ISSUE TITLE
Allow creating IPV6 clusters

### ISSUE THREAD

**Issue by davidroth** [pulumi/pulumi-eks#684]
The underlying package already added support for IPV6 via: https://www.pulumi.com/registry/packages/aws/api-docs/eks/cluster/#clusterkubernetesnetworkconfig

It would be greate if pulumi-eks would allow creating clusters with IPV6 enabled.
See also: https://aws.amazon.com/blogs/containers/amazon-eks-launches-ipv6-support/

In order to support IPv6 clusters the following are required:

- [ ] Add support for enableIpv6 in CNI config [see change in 695](https://github.com/pulumi/pulumi-eks/pull/695)
- [ ] https://github.com/pulumi/pulumi-eks/pull/675
- [ ] https://github.com/pulumi/pulumi-eks/issues/698

**Comment by yandooo** [comment]
@davidroth wondering whether you had a chance to evaluate the scope of work required here? I see you're working on CNI [ipv6 support](https://github.com/pulumi/pulumi-eks/pull/683).

**Comment by davidroth** [comment]
@DCAL12 Unfortunately it is not. I dont know why this issue has been closed. See also the following issue which tracks the ipFamily support: https://github.com/pulumi/pulumi-eks/issues/698

See also [this MR](https://github.com/pulumi/pulumi-eks/pull/700) which was closed without being merged. 😕

**Comment by rquitales** [comment]
Support for this feature should now be enabled in v2.3.0 of the EKS provider!
