### ISSUE TITLE
Latest release doesn’t seem to be usable in Go

### ISSUE THREAD

**Issue by yann-soubeyrand** [pulumi/pulumi-eks#703]
### What happened?

Executing `go get github.com/pulumi/pulumi-eks/sdk/go/eks` gets v0.37.1 whereas the latest release at that time is v0.39.0.
Executing `go get github.com/pulumi/pulumi-eks/sdk/go/eks@v0.39.0` gives this error
```
go: module github.com/pulumi/pulumi-eks@v0.39.0 found, but does not contain package github.com/pulumi/pulumi-eks/sdk/go/eks
```
It seems that the tag sdk/v0.39.0 is missing.

### Steps to reproduce

Executing `go get github.com/pulumi/pulumi-eks/sdk/go/eks` gets v0.37.1 whereas the latest release at that time is v0.39.0.
Executing `go get github.com/pulumi/pulumi-eks/sdk/go/eks@v0.39.0` gives this error
```
go: module github.com/pulumi/pulumi-eks@v0.39.0 found, but does not contain package github.com/pulumi/pulumi-eks/sdk/go/eks
```

### Expected Behavior

`go get github.com/pulumi/pulumi-eks/sdk/go/eks` should get the latest release.

### Actual Behavior

`go get github.com/pulumi/pulumi-eks/sdk/go/eks` gets an old release.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jkisk** [comment]
Thank you, we will get this corrected soon.

**Comment by viveklak** [comment]
Apologies we missed the sdk tag. This should be fixed now.
