### ISSUE TITLE
Unable to pip install pulumi-eks

### ISSUE THREAD

**Issue by SoumayaMauthoorMOJ** [pulumi/pulumi-eks#704]
### What happened?

I tried to pip install pulumi-eks but get the following error:
 ```
Running setup.py install for pulumi-eks ... error
ERROR: Command errored out with exit status 1: 
[...]
[resource plugin eks-0.39.0] installing
    
Downloading plugin: 0 B / 682.52 KiB [---------------------------------]   0.00%
Downloading plugin: 682.52 KiB / 682.52 KiB [=======================] 100.00% 0s
env: node: No such file or directory
error: installing [resource plugin eks-0.39.0] from : installing plugin dependencies: exit status 127
```

I tried with the following python versions: 3.7.13, 3.8.12, 3.9.10 and get the same error. I have uploaded the verbose output. I can pip install pulumi-aws and pulumi-kubernetes without any problems.

[output.txt](https://github.com/pulumi/pulumi-eks/files/8689389/output.txt)

### Steps to reproduce

python -m venv venv   
. venv/bin/activate  
pip install --verbose pulumi-eks                        

### Expected Behavior

That I would be able to install pulumi-eks

### Actual Behavior

As described above

### Versions used

```
CLI          
Version      3.32.1
Go Version   go1.18.1
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.4.0
kubernetes  3.19.1
python      unknown

Host     
OS       darwin
Version  11.6.2
Arch     arm64

This project is written in python (/Users/<>/venv/bin/python3 v3.9.10)
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by viveklak** [comment]
Sounds like you don't have node installed? Could you try with node 14 or higher installed?

**Comment by viveklak** [comment]
To elaborate, the pulumi-eks component plugin is written in typescript and needs node (even if you are planning to consume the SDK in python).

**Comment by SoumayaMauthoorMOJ** [comment]
All working now after I installed node thanks! And I can see that you added to requirements :-)
