### ISSUE TITLE
ignore_changes not working with scalingConfig

### ISSUE THREAD

**Issue by joffreychambrin** [pulumi/pulumi-eks#709]
### What happened?

The ignore_changes doesn't work with the scalingConfig of eks.ManagedNodeGroup

### Steps to reproduce

Create a basic cluster with the following python code : 

```python
"""An AWS Python Pulumi program"""

import pulumi
import pulumi_aws as aws
import pulumi_eks as eks
import roles

role = roles.create_role(f"eks-test-role")

cluster = eks.Cluster(
    "test-cluster",
    version="1.21",
    skip_default_node_group=True,
    use_default_vpc_cni=True,
    instance_role=role,
)

node_group = eks.ManagedNodeGroup(
    "test-node_group",
    cluster=cluster.core,
    node_role_arn=role.arn,
    scaling_config={"desired_size": 1, "min_size": 1, "max_size": 3},
    opts=pulumi.ResourceOptions(ignore_changes=["scalingConfig.desiredSize"]),
)

```

Then, go to AWS console and update the desired size in the autoscaling group to 2. And launch a pulumi refresh with. `pulumi refresh`

### Expected Behavior

After the pulumi refresh, if we launch a `pulumi up`, it should only display unchanged resources

### Actual Behavior

Instead, here is the result of a `pulumi preview --diff`
```
[...]
~ scalingConfig: {
              ~ desiredSize: 2 => 1
            }
Resources:
    ~ 1 to update
    23 unchanged
```

### Versions used

```
CLI
Version      3.32.0
Go Version   go1.18.1
Go Compiler  gc

Host
OS       darwin
Version  12.3.1
Arch     arm64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
Hi and apologies for the wait!

Thank you for reporting this bug. I'm looking into a repro to find out more.

**Comment by guineveresaenger** [comment]
Hi @joffreychambrin - 

after chatting with my colleagues about this feature, it appears as though it is not currently implemented on component resources, such as `ManagedNodeGroup` (or any resources in pulumi/eks packacke). 

We sincerely apologize for the confusion.

**Comment by michael-barker** [comment]
What is the recommended way to handle this? According to Pulumi 4.0 change tracking, this won't be supported in 4.0 either. Using any form of cluster auto scaler will require that you always update your desired size for a managed node group before performing an update or you could risk terminating instances equal to the difference between the current desired and what's defined in the Pulumi program.
