### ISSUE TITLE
Surfacing EKS created Cluster Security Group on the cluster instance

### ISSUE THREAD

**Issue by mohitreddy1996** [pulumi/pulumi-eks#716]
## Issue details
We need EKS created Cluster Security Group for adding it as inbound rules to few other security groups. This information does not seem to be available on the [Cluster instance](https://www.pulumi.com/registry/packages/eks/api-docs/cluster/).

We are currently working around it by using the AWS package.

```
const ekscluster = cluster.core.cluster.name.apply(async (name) => {
    return await aws.eks.getCluster({
        name: name,
    }, { provider: awsProvider })
});
const clusterSg = ekscluster.vpcConfig.clusterSecurityGroupId;
```

To avoid additional dependencies, it would be nice to have this property on cluster instance in the EKS package.

**Comment by viveklak** [comment]
Thanks for the ER! Don't you have access to the the entire cluster resource under `cluster.eksCluster`?

**Comment by mohitreddy1996** [comment]
Aah, yes, just tried that it works :)

Will close this PR. But as a small feedback, it would be amazing if `eksCluster` here: https://www.pulumi.com/registry/packages/eks/api-docs/cluster/#outputs was hyperlinked to the EksCluster instances AWS package. I think we just searched for `clusterSecurityGroupId` in the package and gave up.
