### ISSUE TITLE
TS: Creating default cluster causing unexpected json error

### ISSUE THREAD

**Issue by Jaskerv** [pulumi/pulumi-eks#736]
### What happened?

Creating a default cluster throws `failed with an unhandled exception:
    SyntaxError: Unexpected end of JSON input`

### Steps to reproduce

Run pulumi up 

```
import { Cluster } from '@pulumi/eks';

  // Create an EKS cluster.
  const cluster = new Cluster('cluster');
```

### Expected Behavior

Creates eks cluster.

### Actual Behavior

Fails an throws the following error:
`failed with an unhandled exception:
    SyntaxError: Unexpected end of JSON input`

### Versions used

Pulumi
```
CLI          
Version      3.35.3
Go Version   go1.17.11
Go Compiler  gc

Host     
OS       darwin
Version  11.6.3
Arch     x86_64
```

TS
```
"@pulumi/eks": "^0.41.0",
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by roothorp** [comment]
Hi @Jaskerv, I've just successfully created a default cluster (using your code sample above) and found no issues creating the cluster. Please could you let me know which version of the aws provider you are using in this project? Could you also confirm which resouce is throwing the error, and if there are any stack traces available? Thanks!

**Comment by Jaskerv** [comment]
Providers:
```
        "@pulumi/aws": "^5.10.0",
        "@pulumi/awsx": "^0.40.0",
        "@pulumi/eks": "^0.41.0",
        "@pulumi/kubernetes": "^3.0.0",
        "@pulumi/kubernetesx": "^0.1.5",
        "@pulumi/pulumi": "^3.0.0"
```

Running with verbose logging:

```
An error occurred: flag needs an argument: 'v' in -v
❯ pulumi up -v 9
Previewing update (dev)

View Live: xxxx

     Type                  Name                 Plan       Info
 +   pulumi:pulumi:Stack   dev  create     1 error
 +   └─ eks:index:Cluster  cluster              create     
 
Diagnostics:
  pulumi:pulumi:Stack (dev):
    error: Running program 'xxxx' failed with an unhandled exception:
    SyntaxError: Unexpected end of JSON input
```

**Comment by Jaskerv** [comment]
I've also updated everything. Same issue :(

**Comment by danielrbradley** [comment]
Thanks for the stack trace - that's super helpful. It looks like the command `kubectl version --output=json` is returning something that is not JSON. Executing that command on your machine will likely highlight what the issue is.

**Comment by roothorp** [comment]
I'll keep this open until we can determine what's causing the parse to fail.

**Comment by Nicarod** [comment]
I just had the same issue.
What solved it for me was to select a context for kubectl (I had no selected context the when the error accoured).
Maybe this will help :)

**Comment by cdibble** [comment]
Yeah this happened to me as well because of a bad `~/.kube/config` even though the associated file was nothing to do with my pulumi stack. Removing that file fixed it.
