### ISSUE TITLE
Support tagging of instances, ASGs, launch config, etc.

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-eks#74]
We should expose options for adding custom tags to these (and any other) resources, and may want to automatically at least add `Name` tags as a default.

**Comment by metral** [comment]
community slack ref: https://pulumi-community.slack.com/archives/C84L4E3N1/p1551396052025800

**Comment by naineel** [comment]
This is super important for us. Billing is a big use case which we need to enable

**Comment by joeduffy** [comment]
Note that the EKS cluster resource in AWS itself doesn't appear to support tagging, at least based on the AWS API (https://docs.aws.amazon.com/sdk-for-go/api/service/eks/#CreateClusterInput) and AWS CloudFormation (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-cluster.html) documentation.

It probably makes sense to

1. Expose a `tags` option that auto-tags all resources it can possibly tag (like the instances, security groups, etc)
2. Expose a single `xTags` option, for each resource, `x`, that supports tagging, in case you want more fine grained control (e.g., `instanceTags`, `securityGroupTags`, etc)

I assume AWS will add tagging support to EKS sometime soon, in which case (1) would just start applying them auto-magically on upgrade, and (2) would lead to a separate `clusterTags` option.

**Comment by Lavender-Ding** [comment]
Adding custom tags on Node Group created by EKS is needed to enable Cluster Autoscaler on our side, before this is resolved, is there any way to work around it? Something like get the existing nodegroup and add tags to it.

**Comment by lukehoban** [comment]
> Adding custom tags on Node Group created by EKS is needed to enable Cluster Autoscaler on our side

I believe in this particular case you need to add tags to the `AutoScalingGroup`.  In particular these two tags:

```
k8s.io/cluster-autoscaler/enabled
k8s.io/cluster-autoscaler/<ClusterName>
```

Currently I don't believe there is anyway to do that yourself.  But a PR to this package to enable that should be fairly straightforward, so if you want to contribute it we'd be happy to review and  merge a PR.  Else this is something we'll be looking into very soon ourselves.
