### ISSUE TITLE
Option to skip creating node and cluster security groups

### ISSUE THREAD

**Issue by vinay-kosaraju** [pulumi/pulumi-eks#747]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently, it looks like [node security group](https://github.com/pulumi/pulumi-eks/blob/v0.41.2/nodejs/eks/cluster.ts#L1437) and [cluster security group](https://www.pulumi.com/registry/packages/eks/api-docs/cluster/#clustersecuritygroup_go) with default ingress and egress rules are created if they are not specified in the cluster args. 

Could we please get an option to skip creation of the security groups and let EKS create the security group with default rules? (https://docs.aws.amazon.com/eks/latest/userguide/sec-group-reqs.html)

**Comment by viveklak** [comment]
@roothorp could you take a look and prioritize accordingly?

**Comment by t0yv0** [comment]
NOTE: skipDefaultNodeGroup should be implied by skipping security group.

**Comment by t0yv0** [comment]
Quick update, apologies for the further delay but we decided to defer this item until the upcoming major release of the provider. It appears that the current signature implies that the eks.Cluster resource must return non-optional Node Security Group and Cluster Ingress rule. Making these optional is a technically breaking change, and we considered sending some sentinel values but decided against it for the moment.

IN the upcoming major release the default NodeGroup is going to be removed; the default behavior will use a ManagedNodeGroup but there will be a way to opt out of it. We will need to revisit these settings in the new context, likely will be either removed or moved optional for special cases and not used by default. 

We will track this item and follow up as part of the major release work.

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/home/issues/3558

**Comment by flostadler** [comment]
We've addressed this as part of https://github.com/pulumi/pulumi-eks/pull/1416. This will be released with EKS v3
