### ISSUE TITLE
Expand docs to include examples for Java and YAML

### ISSUE THREAD

**Issue by roothorp** [pulumi/pulumi-eks#749]
Currently [the docs](https://www.pulumi.com/docs/guides/crosswalk/aws/eks/) include examples for other languages - we should translate them to Java and YAML for good docs coverage. Additionaly, relevant info for setup in Java/YAML should be added to the README.

**Comment by ericrudder** [comment]
Fixed

**Comment by ericrudder** [comment]
(Still) fixed
