### ISSUE TITLE
Pulumi EKS Version 0.41.2 adds npm as a dependency

### ISSUE THREAD

**Issue by pmantica3** [pulumi/pulumi-eks#756]
### What happened?

Got
```
Error: installing [resource plugin eks-0.41.2] from : installing plugin dependencies: could not find npm on the $PATH; npm is installed with Node.js available at https://nodejs.org/: exec: "npm": executable file not found in $PATH
```

So I think that v0.41.2 might have introduced npm as a dependency. It wasn't a dependency before. Is this intentional?

### Steps to reproduce

Install EKS version 0.41.2 in Ubuntu

### Expected Behavior

Install failed

### Actual Behavior

Install succeeded

### Versions used

```
ubuntu@ip-172-31-88-46:~/theia$ pulumi about
CLI          
Version      3.36.0
Go Version   go1.17.12
Go Compiler  gc

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/pmantica1
User           pmantica1
Organizations  pmantica1, theia
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by stack72** [comment]
Hi @pmantica3 

What version of pulumi-eks were you on before and how have you installed it? There were no dependency changes between v0.41.0 and v0.41.2 that introduced npm as a dependency - https://github.com/pulumi/pulumi-eks/compare/v0.41.0...v0.41.2 - so we'd need to know the version of what you are upgrading from if this is showing as a new dependency for you.

We do list that nodejs is a dependency for this library - https://github.com/pulumi/pulumi-eks#pre-requisites

Paul

**Comment by pmantica3** [comment]
Hi Paul,

I apologize, but I cannot recreate the issue. Anyways, thanks a lot for the help! I also really appreciate the expediency.

**Comment by stack72** [comment]
Hi @pmantica3 

Thanks for getting back to me so fast :)

Paul
