### ISSUE TITLE
Reduce resources created by managed node group

### ISSUE THREAD

**Issue by vinay-kosaraju** [pulumi/pulumi-eks#759]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

`pulumi.eks.ManagedNodeGroup` creates 2 resources for managing a node group, a `ComponentResource` and a `CustomResource`. The same resource when created with `pulumi.aws.eks.NodeGroup` just creates the `CustomResource`.

Example:
```
+   eks:index:ManagedNodeGroup               default-group-node-group           created
+   aws:eks:NodeGroup                        default-group-node-group           created
```

With `pulumi.eks.ManagedNodeGroup`, is it possible to just create the `CustomResource` without creating the `ComponentResource`? This would enable us to migrate from `pulumi.aws.eks` to `pulumi.eks` and keep the resource count in check

**Comment by stack72** [comment]
Hi @vinay-kosaraju 

I believe someone has already spoken to you about this. I am going to close this out as the creation of a Component Resource is the design of how Pulumi Components work. To remove this would mean that the package is no longer a component and it can't be achieved. I can suggest using the raw Pulumi AWS provider and the eks cluster within that as an alternative

Paul
