### ISSUE TITLE
Incorrect recommendation on use of nodeAssignPublicIpAddress

### ISSUE THREAD

**Issue by scottslowe** [pulumi/pulumi-eks#774]
### What happened?

I was reviewing the API docs on the Registry for the EKS Cluster object (found at https://www.pulumi.com/registry/packages/eks/api-docs/cluster/) and came across this statement:

> Also consider setting `nodeAssociatePublicIpAddress: true` for fully private workers.

This seems incorrect. Intuitively, I would think `nodeAssociatePublicIpAddress` needs to be set to `false` so that it does _not_ associate a public IP address.
If that is _not_ how `nodeAssociatePublicIpAddress` works, then I'd say it's a bug because the vast majority of users will believe that's how it works.

### Steps to reproduce

Review the API docs for an EKS Cluster (found at https://www.pulumi.com/registry/packages/eks/api-docs/cluster/). Scroll down to "Cluster Resource Properties", then to "Inputs", then to "privateSubnetIds", and review the text in the right-hand column.

### Expected Behavior

I would have expected the docs to recommend using `nodeAssociatePublicIpAddress: false` in order to get fully private workers.

### Actual Behavior

The docs recommend using `true` with `nodeAssociatePublicIpAddress` to get fully private workers.

### Output of `pulumi about`

N/A

### Additional context

No

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by stack72** [comment]
Sorry @scottslowe - we will get this updated in our drive toward 1.0 :)
