### ISSUE TITLE
Pulumi preview/up fails when using package-generated "provider"

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi-eks#780]
### What happened?

Using eks package to create an EKS cluster and then using the cluster's generated provider property to deploy a namespace onto the EKS cluster throws this error:
```
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/Users/mitch/Downloads/vtex-demo/pulumi-work/py-aws-eks-helm-argo/./__main__.py", line 34, in <module>
        my_namespace = k8s.core.v1.Namespace("my-namespace",
      File "/Users/mitch/Downloads/vtex-demo/pulumi-work/py-aws-eks-helm-argo/venv/lib/python3.9/site-packages/pulumi_kubernetes/core/v1/Namespace.py", line 128, in __init__
        __self__._internal_init(resource_name, *args, **kwargs)
      File "/Users/mitch/Downloads/vtex-demo/pulumi-work/py-aws-eks-helm-argo/venv/lib/python3.9/site-packages/pulumi_kubernetes/core/v1/Namespace.py", line 151, in _internal_init
        super(Namespace, __self__).__init__(
      File "/Users/mitch/Downloads/vtex-demo/pulumi-work/py-aws-eks-helm-argo/venv/lib/python3.9/site-packages/pulumi/resource.py", line 1081, in __init__
        Resource.__init__(self, t, name, True, props, opts, False, dependency)
      File "/Users/mitch/Downloads/vtex-demo/pulumi-work/py-aws-eks-helm-argo/venv/lib/python3.9/site-packages/pulumi/resource.py", line 922, in __init__
        raise ValueError(
    ValueError: Attempted to register resource kubernetes:core/v1:Namespace with a provider for 'Calling __str__ on an Output[T] is not supported.
    
    To get the value of an Output[T] as an Output[str] consider:
    1. o.apply(lambda v: f"prefix{v}suffix")
    
    See https://pulumi.io/help/outputs for more details.
    This function may throw in a future version of Pulumi.'
```

If I instead use the generated `kubeconfig` to then instantiate a K8s provider, this works fine.

### Steps to reproduce

This code will reproduce the error:
```
### create an EKS cluster
cluster = Cluster(basename, ClusterArgs(
    vpc_id=vpc.id,
    max_size=4,
))
k8s_provider = cluster.provider
# k8s_provider = k8s.Provider('k8s-provider', kubeconfig=cluster.kubeconfig, delete_unreachable=True)

my_namespace = k8s.core.v1.Namespace("my-namespace",
    metadata=k8s.meta.v1.ObjectMetaArgs(
        name="my-namespace"
    ),
    opts=ResourceOptions(provider=k8s_provider))
```

1. `pulumi up` will throw the error above.

Note: If you comment/uncomment the `k8s_provider=` lines so that k8s_provider is set to the explicitly created provider instead of using the `provider` property from the cluster, and do a `puluimi up` things will work fine.

### Expected Behavior

The `cluster.provider` should work.

### Actual Behavior

Need to instantiate the provider explicitly instead of being able to use the generated provider.

### Output of `pulumi about`

```
CLI          
Version      3.40.0
Go Version   go1.19
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.14.0
eks         0.41.2
kubernetes  3.21.2
python      unknown

Host     
OS       darwin
Version  12.5.1
Arch     x86_64

Current Stack: dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com

Dependencies:
NAME        VERSION
pip         21.1.3
pulumi-eks  0.41.2
setuptools  56.0.0
```

### Additional context

I do use AWS SSO login. So maybe that's the root cause.
if so, if there is anyway for the error message to be more clear about that, or at least provide a suggestion to use an explicit provider, that would be good.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by roothorp** [comment]
Hi Mitch; this has been addressed (removed) in https://github.com/pulumi/pulumi-eks/pull/746 - using cluster.provider outisde of Typescript never really worked, and will be removed with the next release. It is my understanding that creating your own provider using the Kubeconfig (as you have in your commented line) is the way to go.

**Comment by danielrbradley** [comment]
@MitchellGerdisch you happy if we close this given we're going to be removing this functionality? Is the discoverability of using the `kubeconfig` directly something we could improve here to send people down the right path (e.g. make sure we've got an example in the docs)?

**Comment by MitchellGerdisch** [comment]
Yes, this can be closed. I assume there's an upcoming release planned to include this change?
And, an example is always good. But, maybe in the API documentation for the  `kubeconfig` output add some reference on  using it to instantiate a provider?
