### ISSUE TITLE
ClusterNodeGroupOptions should support all node_root_volume_* options

### ISSUE THREAD

**Issue by betamike** [pulumi/pulumi-eks#784]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

`Cluster` supports configuring the root volume of nodes via a set of `node_root_volume_*` parameters in its initializer.  

The node group can also be configured by passing the `node_group_options` parameter. `ClusterNodeGroupOptions` only supports one (`node_root_volume_size`) and not the other five options.

Providing `node_group_options` is mutually exclusive with setting node group options on `Cluster`, making it impossible to use these options if `node_group_options` is already being used. This can be problematic if you need to set one of the parameters on `ClusterNodeGroupOptions` that don't appear on `Cluster`; `auto_scaling_group_tags` for example.

Overall it might be useful to understand why some of the options are duplicated; perhaps ease of use? It probably makes sense to commit to either keeping both sites in sync, or deprecate setting the node options on `Cluster` in favor of `node_group_options`.

**Comment by markfickett** [comment]
> It probably makes sense to [...] deprecate setting the node options on Cluster in favor of node_group_options.
I got tripped up by this duplication, and would find it clearer to only have the `node_group_options`. I'd rather it be a little less convenient but have less opportunity for errors about mutually exclusive options or having multiple ways to do the same thing.
