### ISSUE TITLE
v0.42.0 SDK tag missing

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-eks#786]
### What happened?

no sdk tag for the go sdk for 

### Steps to reproduce

use the go sdk with v0.42.0

### Expected Behavior

it doesn't work

### Actual Behavior

it works

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lblackstone** [comment]
v0.42.0 release process failed before completing. Kicked off [v0.42.1](https://github.com/pulumi/pulumi-eks/actions/runs/3185345571) to resolve this.
