### ISSUE TITLE
NodeGroupV2 discards NodeUserDataOverride field

### ISSUE THREAD

**Issue by vboulineau** [pulumi/pulumi-eks#792]
### What happened?

The field `NodeUserDataOverride` is not taken into account when creating NodeGroupV2 resources.
It breaks the ability to deploy Windows node groups.

### Steps to reproduce

Create a NodeGroupV2 with `NodeUserDataOverride` field set:

```
	return eks.NewNodeGroupV2(ctx, name, &eks.NodeGroupV2Args{
		NodeUserDataOverride: userData,
		Cluster:              cluster.Core,
		DesiredCapacity:      pulumi.Int(1),
		AmiId:                        ami,
		InstanceType:                 instanceType,
		NodeRootVolumeSize:           pulumi.Int(80),
		NodeAssociatePublicIpAddress: pulumi.BoolPtr(false),
		InstanceProfile:              instanceProfile,
	})
```

User data is:
```
<powershell>
[string]$EKSBootstrapScriptFile = "$env:ProgramFiles\Amazon\EKS\Start-EKSBootstrap.ps1"
& $EKSBootstrapScriptFile -EKSClusterName %s 3>&1 4>&1 5>&1 6>&1
</powershell>
```

### Expected Behavior

The launch template contains the custom UserData.

### Actual Behavior

The create launch template contains the default EKS Linux data:
```
#!/bin/bash

/etc/eks/bootstrap.sh --apiserver-endpoint "https://<endpoint>.us-east-1.eks.amazonaws.com" --b64-cluster-ca "<somecontent>" "vboulineau-eks-test"
```

### Output of `pulumi about`

```
CLI
Version      3.42.0
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.7.2
awsx        1.0.0-beta.11
docker      3.2.0
eks         0.42.3
go          unknown
kubernetes  3.21.4

Host
OS       darwin
Version  12.6
Arch     x86_64

This project is written in go: executable='/usr/local/bin/go' version='go version go1.19.1 darwin/amd64'

Backend
Name           laptop
URL            gs://vboulineau-pulumi-test
User           vincent.boulineau
Organizations

Dependencies:
NAME                                        VERSION
github.com/pulumi/pulumi-aws/sdk/v5         5.7.2
github.com/pulumi/pulumi-awsx/sdk           1.0.0-beta.11
github.com/pulumi/pulumi-eks/sdk            0.42.3
github.com/pulumi/pulumi-kubernetes/sdk/v3  3.21.4
github.com/pulumi/pulumi/sdk/v3             3.40.1
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by viveklak** [comment]
Thanks for filing the issue. It does appear the field is not appropriately wired. nodeUserData is wired in but there is a different bug I think that prevents it [from being used](https://github.com/pulumi/pulumi-eks/blob/1d2e96067c38d6a195037b5ac382d232885729ad/nodejs/eks/nodegroup.ts#L841-L848). I have added this issue to our prioritized backlog for this project.
