### ISSUE TITLE
Empty list of arguments 

### ISSUE THREAD

**Issue by podshivalovdv** [pulumi/pulumi-eks#806]
Hi,
The list in here: [ProviderArgs](https://www.pulumi.com/registry/packages/eks/api-docs/provider/#inputs) is empty. 
File: [themes/default/content/registry/packages/eks/api-docs/provider/_index.md](https://www.pulumi.com/registry/packages/eks/api-docs/provider/)

**Comment by viveklak** [comment]
Thanks for opening the issue. This is a bug in our doc generator. `pulumi-eks` package publishes [component resources](https://www.pulumi.com/docs/intro/concepts/resources/components/) so there isn't an explicit provider created directly. Indeed the schema of pulumi-eks doesn't include any details about the provider: https://github.com/pulumi/pulumi-eks/blob/master/provider/cmd/pulumi-resource-eks/schema.json#L553. You can influence the underlying providers (aws or kubernetes) by specifying the providers component resource option: https://www.pulumi.com/docs/intro/concepts/resources/components/#inheriting-resource-providers

**Comment by viveklak** [comment]
Opened https://github.com/pulumi/pulumi/issues/11217 to track the docs generation issue.

**Comment by podshivalovdv** [comment]
Great, thanks a lot!
