### ISSUE TITLE
Add LaunchTemplateTagSpecifications to NodeGroupV2

### ISSUE THREAD

**Issue by MMartyn** [pulumi/pulumi-eks#808]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
My company has strict tagging policies for resources that we launch in AWS to track cost centers. Without the ability to add tags to the launch templates I am unable to create auto scaling groups or launch instances.

### Affected area/feature
NodeGroupV2

**Comment by MMartyn** [comment]
I'll have a PR for this shortly.

**Comment by lblackstone** [comment]
I responded on your PR. Thanks for the contribution!
