### ISSUE TITLE
aws-go-eks-helloworld example is broken because it uses the provider property which was removed

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi-eks#814]
I noticed the [aws-go-eks-helloworld](https://github.com/pulumi/pulumi-eks/tree/master/examples/aws-go-eks-helloworld) example does not compile since we removed the `provider` property in #746.

https://github.com/pulumi/pulumi-eks/blob/28745d145d53a918c681ee3ae233e67a84a287b8/examples/aws-go-eks-helloworld/main.go#L23-L32

We need to fix this up to create an instance of the provider from the kubeconfig per #812 and add this example to the set of tests to ensure it continues working in the future (and for additional coverage).

**Comment by blampe** [comment]
Fixed in https://github.com/pulumi/pulumi-eks/pull/910.
