### ISSUE TITLE
Change nodeUserDataOverride option when creating node groups to a function accepting cloud formation stack name as an input

### ISSUE THREAD

**Issue by gunniwho** [pulumi/pulumi-eks#826]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

The bootstrapping script is required to call `cfn-signal`, passing the CloudFormation stack name as an argument. The cfn stack however, is created inside the `createNodeGroup` function so we can't know it when specifying this option. So I actually believe this option is completely useless. If it were a function that would get the stack name as an input I believe it could be used, even to create windows node groups.

### Affected area/feature

pulumi-eks, specifically `NodeGroup` class

**Comment by danielrbradley** [comment]
Hi @gunniwho I'm afraid I don't think I quite follow what you're proposing. Would you be able to provide an example of how you'd use the resource options as-is and what you'd imagine a possible fix to look like?

Thanks!

**Comment by gunniwho** [comment]
Sure thing @danielrbradley ! In its current form, I would like use it like this:
```
{
  nodeUserDataOverride: `
      <powershell>
      [string]$EKSBinDir = "$env:ProgramFiles\\Amazon\\EKS"
      [string]$EKSBootstrapScriptName = 'Start-EKSBootstrap.ps1'
      [string]$EKSBootstrapScriptFile = "$EKSBinDir\\$EKSBootstrapScriptName"
      [string]$cfn_signal = "$env:ProgramFiles\\Amazon\\cfn-bootstrap\\cfn-signal.exe"
      & $EKSBootstrapScriptFile -EKSClusterName ${clusterName} --register-with-taints os=Windows:NoSchedule 3>&1 4>&1 5>&1 6>&1
      $LastError = if ($?) { 0 } else { $Error[0].Exception.HResult }
      & $cfn_signal --exit-code=$LastError \`
        --stack="${stackName}" \`
        --resource="NodeGroup" \`
        --region=${regionName}
      </powershell>
`
}
```

but the problem is where I'm referencing the `stackName` value. This is generated by the pulumi code, and thus I can't know it here. So my proposal is that instead of making `nodeUserDataOverride` a string value, make it a function from `stackName` to string:

```
{
  nodeUserDataOverride: stackName => `
      <powershell>
      [string]$EKSBinDir = "$env:ProgramFiles\\Amazon\\EKS"
      [string]$EKSBootstrapScriptName = 'Start-EKSBootstrap.ps1'
      [string]$EKSBootstrapScriptFile = "$EKSBinDir\\$EKSBootstrapScriptName"
      [string]$cfn_signal = "$env:ProgramFiles\\Amazon\\cfn-bootstrap\\cfn-signal.exe"
      & $EKSBootstrapScriptFile -EKSClusterName ${clusterName} --register-with-taints os=Windows:NoSchedule 3>&1 4>&1 5>&1 6>&1
      $LastError = if ($?) { 0 } else { $Error[0].Exception.HResult }
      & $cfn_signal --exit-code=$LastError \`
        --stack="${stackName}" \`
        --resource="NodeGroup" \`
        --region=${regionName}
      </powershell>
`
}
```

**Comment by danielrbradley** [comment]
Hi again @gunniwho just coming back to this. Would this not work just passing in the current stack into the string template? e.g. using [`pulumi.getStack()`](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/pulumi/#getStack) in nodejs.

```typescript
{
  nodeUserDataOverride: `
      <powershell>
      [string]$EKSBinDir = "$env:ProgramFiles\\Amazon\\EKS"
      [string]$EKSBootstrapScriptName = 'Start-EKSBootstrap.ps1'
      [string]$EKSBootstrapScriptFile = "$EKSBinDir\\$EKSBootstrapScriptName"
      [string]$cfn_signal = "$env:ProgramFiles\\Amazon\\cfn-bootstrap\\cfn-signal.exe"
      & $EKSBootstrapScriptFile -EKSClusterName ${clusterName} --register-with-taints os=Windows:NoSchedule 3>&1 4>&1 5>&1 6>&1
      $LastError = if ($?) { 0 } else { $Error[0].Exception.HResult }
      & $cfn_signal --exit-code=$LastError \`
        --stack="${pulumi.getStack()}" \`
        --resource="NodeGroup" \`
        --region=${regionName}
      </powershell>
`
}
```

**Comment by gunniwho** [comment]
Hi @danielrbradley, no I don't think you can do that because this is not the pulumi stack, but the cloud formation stack that is needed there.

**Comment by mikhailshilkov** [comment]
@gunniwho Are you still looking for this feature? Could you provide a repro program, as @danielrbradley requested above? Thank you!

**Comment by gunniwho** [comment]
@mikhailshilkov I no longer need windows nodes and unfortunately I don't currently have time to look into this. Sorry...

**Comment by mjeffryes** [comment]
closing as stale
