### ISSUE TITLE
cluster instanceRole does not contain an aws.iam.role object but just a string

### ISSUE THREAD

**Issue by naineel** [pulumi/pulumi-eks#83]
The eks cluster creation exposes an instance role which is the default cluster.instanceRole.

When I do 
```
cluster.instanceRole(role => console.log(role.arn));
```
I expect the role arn to be displayed but it shows up as not defined. 

I go a step further and try:
```
cluster.instanceRole.apply(role => console.log("arn: " + role.arn + " name: " + role.name + " role: " + role));

Output:
arn: undefined name: undefined role: xxx-eks-cluster-instanceRole-role-e3b9ec3
```
I think it's bug and needs to be fixed.

**Comment by naineel** [comment]
@lukehoban

**Comment by lukehoban** [comment]
I suspect this may be related to https://github.com/pulumi/pulumi-terraform/issues/9.  We should really be projecting `InstanceProfile#role` as a `string | Role` on the input side and `string` on the output side.  

This is only an issue with the TypeScrip type, so can easily be worked around by casting to `any` like this:

```
cluster.instanceRole((role: any) => console.log(role));
```

to fix this - we should fix the following two locations:
* https://github.com/pulumi/pulumi-aws/blob/master/resources.go#L1087
* https://github.com/pulumi/pulumi-aws/blob/master/resources.go#L1119

Which should instead look like this:
* https://github.com/pulumi/pulumi-aws/blob/master/resources.go#L1132-L1135

Doing so will be a breaking change in the TypeScript typing, but will make the TypeScript types correct wrt the actual values produced from the API.
