### ISSUE TITLE
Latest EKS AMI will get a windows image.

### ISSUE THREAD

**Issue by timmyers** [pulumi/pulumi-eks#84]
https://github.com/pulumi/pulumi-eks/blob/976c33bb385d5ac1d2447fcf2c3d9e48d7eeca23/nodejs/eks/nodegroup.ts#L315

This will as of sometime recently result in a Windows AMI, likely unexpectedly.

This should theoretically be fixable by filtering for `platform` as `blank`, according to https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-images.html, however it does not seem there is a way to do that in code and get any results.

**Comment by lukehoban** [comment]
Note that a workaround is to set the `nodeAmiId` parameter to the desired EKS Node AMI from https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html explicitly.
