### ISSUE TITLE
TypeError: Invalid Version: null when following https://www.pulumi.com/templates/kubernetes/aws/

### ISSUE THREAD

**Issue by jwmatthews** [pulumi/pulumi-eks#869]
### What happened?

I ran into a similar issue to https://github.com/pulumi/pulumi-eks/issues/768

Received` TypeError: Invalid Version: null` when following https://www.pulumi.com/templates/kubernetes/aws/
(I am a new user, this is my first install/attempt of using pulumi, this was seen on a new project)

My steps:

1. `pulumi new kubernetes-aws-typescript`
2. `pulumi up`

```

Diagnostics:
  pulumi:pulumi:Stack (my-k8s-cluster-jmatthewsMarch28_2023):
    error: Running program '/Users/jmatthews/git/jwmatthews/tinkering/pulumi/my-k8s-cluster/' failed with an unhandled exception:
    TypeError: Invalid Version: null
        at new SemVer (/Users/jmatthews/git/jwmatthews/tinkering/pulumi/my-k8s-cluster/node_modules/@pulumi/eks/node_modules/semver/classes/semver.js:19:13)
        at compare (/Users/jmatthews/git/jwmatthews/tinkering/pulumi/my-k8s-cluster/node_modules/@pulumi/eks/node_modules/semver/functions/compare.js:3:3)
        at Object.lt (/Users/jmatthews/git/jwmatthews/tinkering/pulumi/my-k8s-cluster/node_modules/@pulumi/eks/node_modules/semver/functions/lt.js:2:29)
        at Object.assertCompatibleKubectlVersionExists (/Users/jmatthews/git/jwmatthews/tinkering/pulumi/my-k8s-cluster/node_modules/@pulumi/dependencies.ts:62:16)
        at createCore (/Users/jmatthews/git/jwmatthews/tinkering/pulumi/my-k8s-cluster/node_modules/@pulumi/cluster.ts:401:5)
        at createCluster (/Users/jmatthews/git/jwmatthews/tinkering/pulumi/my-k8s-cluster/node_modules/@pulumi/cluster.ts:1728:18)
        at new Cluster (/Users/jmatthews/git/jwmatthews/tinkering/pulumi/my-k8s-cluster/node_modules/@pulumi/cluster.ts:1615:25)
        at Object.<anonymous> (/Users/jmatthews/git/jwmatthews/tinkering/pulumi/my-k8s-cluster/index.ts:20:20)
        at Module._compile (node:internal/modules/cjs/loader:1254:14)
        at Module.m._compile (/Users/jmatthews/git/jwmatthews/tinkering/pulumi/my-k8s-cluster/node_modules/ts-node/src/index.ts:439:23)

```

### Expected Behavior

Expecting to see an EKS cluster provisioned

### Steps to reproduce

1. `pulumi new kubernetes-aws-typescript`
2. `pulumi up`

### Output of `pulumi about`

```
$ pulumi about
CLI          
Version      3.60.0
Go Version   go1.20.2
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.33.0
aws         5.16.2
awsx        1.0.2
docker      3.6.1
eks         1.0.1
kubernetes  3.24.2
nodejs      unknown

Host     
OS       darwin
Version  13.2.1
Arch     arm64

This project is written in nodejs: executable='/Users/jmatthews/.nvm/versions/node/v18.15.0/bin/node' version='v18.15.0'

Current Stack: jwmatthews/my-k8s-cluster/jmatthewsMarch28_2023

Found no resources associated with jmatthewsMarch28_2023

Found no pending operations associated with jmatthewsMarch28_2023


Dependencies:
NAME            VERSION
@pulumi/awsx    1.0.2
@pulumi/eks     1.0.1
@pulumi/pulumi  3.60.0
@types/node     16.18.21
typescript      4.9.5

```

### Additional context

After reading https://github.com/pulumi/pulumi-eks/issues/768 I saw the issue could be related to an older awscli so I ensured I was running latest, but still seeing the error.

```
$ aws --version
aws-cli/2.11.6 Python/3.11.2 Darwin/22.3.0 source/arm64 prompt/off
```

I also upgraded node to v18, as I was running v17 and wasn't sure if that could be related, but still seeing this.

I've attempted this also with:
- pulumi new kubernetes-aws-python
- pulumi new aws-go

Seeing same problem in all of my attempts

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment]
@jwmatthews Thanks for reporting this issue and the detailed steps to reproduce along with testing other languages!

Unfortunately, I'm unable to replicate this on my end. I've tried it within my local Macbook, and a containerized environment as well.

Looking at the error message you provided, it looks like it might be due to a kubectl issue as I'm seeing the `assertCompatibleKubectlVersionExists ` function failing. Can you provide what kubectl version you're using? And whether it's been built locally?

Thanks

**Comment by jwmatthews** [comment]
@rquitales thank you, my issue is resolved!

You hit the problem, I had an older kubectl which I built locally

```
$ kubectl version
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%H$", GitCommit:"$Format:%H$", GitTreeState:"", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"darwin/arm64"}
```

I upgraded to an official released 'kubectl' and I'm working now :)

```
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:40:17Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
```


Much appreciation for the help, pulumi looks like some fun to play with.
