### ISSUE TITLE
Unable to create iam role using oidc provider arn

### ISSUE THREAD

**Issue by sreecodeslayer** [pulumi/pulumi-eks#871]
### What happened?

I am trying to use AWS secret manager with EKS. For this, we first need to enable an oidc provider for the cluster, and then add IAM federated role policy.

ref: https://docs.aws.amazon.com/eks/latest/userguide/associate-service-account-role.html

However, this fails with an error when doing using Pulumi:
```
* creating IAM Role (foo-service-account-role-b45f829): MalformedPolicyDocument: Federated principals must be valid domain names or SAML metadata ARNs
    	status code: 400, request id: 52ed0817-7417-44aa-a9f6-137e755d4961
```

### Expected Behavior

Able to create iam role using pulumi for eks oidc provider arn

### Steps to reproduce

Here are the code snippets, where I believe the issue happens:

```ts
import * as eks from "@pulumi/eks"
import * as aws from "@pulumi/aws"

const cluster = new eks.Cluster("foo", {createOidcProvider: true})

const oidcArn = cluster.core.oidcProvider?.arn
const oidcId = cluster.core.oidcProvider?.id?.apply(v => v.split("oidc-provider/").pop())

const iamServiceAccountRole = new aws.iam.Role(`foo-service-account-role`, {
  assumeRolePolicy: JSON.stringify({
    Statement: [{
      Action: "sts:AssumeRoleWithWebIdentity",
      Condition: {
        StringEquals: {
          [`${oidcId}:sub`]: "system:serviceaccount:default:core-service-account",
          [`${oidcId}:aud`]: "sts.amazonaws.com"
        }
      },
      Effect: "Allow",
      Principal: {
        Federated: oidcArn,
      },
    }],
    Version: "2012-10-17",
  })
})
```

I do see id and arn in pulumi outputs, but the script never succeeds

```
  + default : {
      + oidcArn: "arn:aws:iam::xxxx:oidc-provider/oidc.eks.us-west-1.amazonaws.com/id/xxxx"
      + oidcId : "oidc.eks.us-west-1.amazonaws.com/id/xxxx"
    }
```

### Output of `pulumi about`

```
CLI
Version      3.62.0
Go Version   go1.20.2
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.32.0
aws         5.16.2
awsx        1.0.2
docker      3.6.1
eks         1.0.1
kubernetes  3.24.2
nodejs      unknown

Host
OS       darwin
Version  13.1
Arch     arm64

This project is written in nodejs: executable='/Users/sreenadh/.asdf/shims/node' version='v19.4.0'
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by kpitzen** [comment]
Hi @sreecodeslayer - thank you for this detailed report! I was able to reproduce the issue given the code you provided, and unfortunately this comes down to how `pulumi.Output` functions inside `JSON.stringify`.  We should likely enhance our eslint plugin [here](https://github.com/pulumi/eslint-plugin-pulumi) and recommend its usage with sensible defaults to catch cases like this. The actual resolution is to create the iam policy document separately inside an apply, and then pass that document down to the resource (in this case Role) that you're trying to create.

Here's a working example of the above which I'm hopeful you'll be able to use as well.

Let me know if there's anything else we can help with!


```typescript
import * as eks from "@pulumi/eks";
import * as aws from "@pulumi/aws";
import * as pulumi from "@pulumi/pulumi";

const cluster = new eks.Cluster("foo", { createOidcProvider: true });

export const oidcArn = cluster.core.oidcProvider!.arn;
export const oidcId = cluster.core.oidcProvider!.id.apply(
  (v) => v.split("oidc-provider/").pop() || ""
);

const iamDocument = oidcArn.apply((arn) => {
  const oidcSub = `${arn}:sub`;
  const oidcAud = `${arn}:aud`;
  return JSON.stringify({
    Statement: [
      {
        Action: "sts:AssumeRoleWithWebIdentity",
        Condition: {
          StringEquals: {
            [oidcSub]: "system:serviceaccount:default:core-service-account",
            [oidcAud]: "sts.amazonaws.com",
          },
        },
        Effect: "Allow",
        Principal: {
          Federated: arn,
        },
      },
    ],
    Version: "2012-10-17",
  });
});

const iamServiceAccountRole = new aws.iam.Role(
  `foo-service-account-role`,
  {
    assumeRolePolicy: iamDocument,
  },
  { dependsOn: cluster.core.oidcProvider }
);

export const iamServiceArn = iamServiceAccountRole.arn;
```

**Comment by sreecodeslayer** [comment]
hey @kpitzen , thanks for checking it out. the suggested code change fixes the problem! 🎉

**Comment by kpitzen** [comment]
That's great @sreecodeslayer ! Thank you for your input - if anything else comes up please feel free to reach out. All the best!
