### ISSUE TITLE
Cluster.user_mappings changes cause node group replacement

### ISSUE THREAD

**Issue by markfickett** [pulumi/pulumi-eks#877]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I am adding a user to the `user_mappings` of my `eks.Cluster`, and when I run `pulumi up` it reports

```
     ├─ eks:index:Cluster                my-eks-cluster
 +-  │  └─ kubernetes:core/v1:ConfigMap  my-eks-cluster-nodeAccess          replace     [diff: ~data]
     └─ eks:index:ManagedNodeGroup       my-eks-cluster-managed-node-group
 +-     └─ aws:eks:NodeGroup             my-eks-cluster-managed-node-group  replace
```
I was surprised that the `user_mappings` change triggered replacing the `NodeGroup`. If this is working as intended, it would be great to add a note about it on the `user_mappings` [field in the eks.Cluster Pulumi docs](https://www.pulumi.com/registry/packages/eks/api-docs/cluster/#user_mappings_python).

I'm using Pulumi in Python, `pulumi-eks==0.42.7`.

**Comment by thomas11** [comment]
Hi @markfickett! I'm checking with my colleagues on whether that's expected.

I also noticed that you're on major version 0. Version 1 is out now and contains a number of improvements. It might be worth trying to upgrade.

**Comment by thomas11** [comment]
We believe that a change to `user_mappings` should in fact not trigger a node group replacement. I looked around in the code a bit but couldn't spot the issue quickly. 

Processing of the user-provided mappings happens [here](https://github.com/pulumi/pulumi-eks/blob/563970bf5d5ef8749f4e56007961fa49fa04ac4c/nodejs/eks/cluster.ts#L842). They are then used in the `data` field of a [ConfigMap](https://www.pulumi.com/registry/packages/kubernetes/api-docs/core/v1/configmap/#inputs).

**Comment by markfickett** [comment]
Thanks for checking it out. I'll see if I can upgrade my `pulumi-eks` and then double check what happens if I try a `user_mappings` update again.

**Comment by rquitales** [comment]
NB: It looks like this is somewhat similar to #772.

**Comment by markfickett** [comment]
Confirmed that after updating to `pulumi-eks==1.0.2` when I add a user I only see a `ConfigMap` change planned:

```
Previewing update (aws-prod):
     Type                                Name                              Plan        Info
     pulumi:pulumi:Stack                 my-stack-prod
 +   ├─ aws:iam:UserGroupMembership      newuser-in-group-membership   create
     └─ eks:index:Cluster                tech-data-eks-cluster
 +-     └─ kubernetes:core/v1:ConfigMap  tech-data-eks-cluster-nodeAccess  replace     [diff: ~data]
```

Thanks for your help, and patience with an old version!

**Comment by thomas11** [comment]
Thanks for reporting back to us, @markfickett!
