### ISSUE TITLE
Documentation appears to be missing supported inputs

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi-eks#895]
### What happened?

Docs page, for say, Nodegroup:
https://www.pulumi.com/registry/packages/eks/api-docs/managednodegroup/#inputs
does not show any setting related to, say, node group storage class (e.g. "gp2" or "gp3", etc).

But digging around the source code, one finds evidence of these inputs:
https://github.com/pulumi/pulumi-eks/blob/72e6429bb5494e80d62228de1d3f489593b19ad6/provider/cmd/pulumi-gen-eks/main.go#L442
https://github.com/pulumi/pulumi-eks/blob/72e6429bb5494e80d62228de1d3f489593b19ad6/nodejs/eks/nodegroup.ts#L148C1-L148C77

So, it seems like not everything is being presented in the docs and/or being exposed by the package.

### Expected Behavior

Docs should present supported inputs.

### Steps to reproduce

See notes above.

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment]
Thanks for reporting the lapse in our docs! @mnlumi I believe you've seen similar issues with incomplete doc generation. Do you have nay ideas what might be happening here. Iirc we had issues with nested fields in the past.

**Comment by mnlumi** [comment]
@rquitales I'm not sure the exact cause, but there is this comment in [another pulumi-eks ticket related to nested properties MLC](https://github.com/pulumi/pulumi-eks/issues/626#issuecomment-1199446543): 
> This is a general bug from an MLC AFAICT that needs to be fixed as this also presents itself on AWSX.

There are also pages outside of pulumi-eks with missing content or blank fields like:
- https://www.pulumi.com/registry/packages/aws/api-docs/ec2/getami/ [Related issue](https://github.com/pulumi/pulumi-aws/issues/2437)
- https://www.pulumi.com/registry/packages/gcp/api-docs/serviceaccount/getaccount/#result
- https://www.pulumi.com/registry/packages/gcp/api-docs/iam/getworkloadidentitypool/
- https://www.pulumi.com/registry/packages/gcp/api-docs/artifactregistry/repositoryiambinding/
- https://www.pulumi.com/registry/packages/azapi/api-docs/getresourceaction/
- https://www.pulumi.com/registry/packages/azapi/api-docs/provider/

^to list a few.

**Comment by mnlumi** [comment]
Another: https://github.com/pulumi/pulumi-gcp/issues/386

**Comment by flostadler** [comment]
I had a look at this just now and those parameters are missing from the schema. That's why it's not present in docs and the generated SDKs
