### ISSUE TITLE
NodeGroupV2 not encrypting block storage

### ISSUE THREAD

**Issue by CyberArkCH3** [pulumi/pulumi-eks#926]
### What happened?

When disabling the default NodeGroup in eks.Cluster and enabling `encryptRootBlockDevice: true` for eks.NodeGroupV2, the launch template in use by the Autoscaling group is not setting the storage to be encrypted.

### Example

```typescript
export const eksCluster = new eks.Cluster(resourcePrefix + "eks-clstr", {
  name: resourcePrefix + "eks-clstr",
  vpcId: vpcId,
  clusterSecurityGroup: sgEks,
  privateSubnetIds: eksSubnetsIds,
  nodeAssociatePublicIpAddress: false,
  instanceType: cfgEks.require("node-size"),
  version: cfgEks.require("version"),
  nodeAmiId: eksAmiId,
  desiredCapacity: cfgEks.requireNumber("node-count"),
  minSize: 4,
  maxSize: 9,
  skipDefaultNodeGroup: true,
  serviceRole: eksSvcRole,
  instanceRole: eksNodeRole,
  encryptRootBlockDevice: true,
  endpointPublicAccess: false,
  endpointPrivateAccess: true,
  createOidcProvider: true,
  tags: {
    Name: resourcePrefix + "eks-clstr",
  },
});

new eks.NodeGroupV2(resourcePrefix + "NodeGroup", {
  cluster: eksCluster,
  instanceType: cfgEks.require("node-size"),
  desiredCapacity: cfgEks.requireNumber("node-count"),
  amiId: eksAmiId,
  nodeSubnetIds: eksCluster.core.subnetIds,
  extraNodeSecurityGroups: [sgEks],
  nodeAssociatePublicIpAddress: false,
  minSize: 4,
  maxSize: 9,
  encryptRootBlockDevice: true,
  instanceProfile: eksInstanceProfile,
});
```

### Output of `pulumi about`

❯ pulumi about
CLI          
Version      3.88.1
Go Version   go1.21.1
Go Compiler  gc

Plugins
NAME                  VERSION
aws                   5.41.0
aws                   5.31.0
eks                   1.0.2
kubernetes            3.29.0
nodejs                unknown
random                4.13.2
tls                   4.10.0
tls-self-signed-cert  0.1.3

Host     
OS       darwin
Version  13.5.1
Arch     x86_64

This project is written in nodejs: executable='/Users/username/brew/bin/node' version='v20.8.1'

Dependencies:
NAME                          VERSION
@types/node                   16.18.34
typescript                    5.1.3
@pulumi/aws                   5.41.0
@pulumi/eks                   1.0.2
@pulumi/pulumi                3.78.1
@pulumi/random                4.13.2
@pulumi/tls-self-signed-cert  0.1.3
@pulumi/tls                   4.10.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by MitchellGerdisch** [comment]
In testing some code, I noticed that when hovering over the `encryptRootBlockDevice` property in my code, I saw this:
```
(property) NodeGroupBaseOptions.encryptRootBlockDevice?: Input<boolean> | undefined
Encrypt the root block device of the nodes in the node group.

@deprecated
This option has been deprecated for parameter naming coherence. Use the nodeRootVolumeEncrypted option instead.
```
Using the (undocumented) `nodeRootVolumeEncrypted` property set to true worked.

**Comment by CyberArkCH3** [comment]
Looks good! Thanks for taking a look at this. I'll close it in favor of your issue.
