### ISSUE TITLE
Out of date examples

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-eks#928]
### What happened?

Looks like some examples reference ancient versions of dependencies that no longer work standalone. They work in CI by substituting in ambient provider build.

### Example

cd examples/cluster-go && pulumi preview

# will fail

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
Looks like this might be solved already in https://github.com/pulumi/pulumi-eks/pull/910/ - excellent.

**Comment by thomas11** [comment]
Fixed by #910.

**Comment by t0yv0** [comment]
Whoops this did not close because no assignee. Assigning you Thomas, thanks a ton!
