### ISSUE TITLE
NodeGroupV2 always generates updates on aws:ec2/launchTemplate:LaunchTemplate and aws:autoscaling/group:Group

### ISSUE THREAD

**Issue by bluegumcity** [pulumi/pulumi-eks#980]
### What happened?

Everytime I run `pulumi up`, it shows a diff on the aws:ec2/launchTemplate:LaunchTemplate and aws:autoscaling/group:Group.
![image](https://github.com/pulumi/pulumi-eks/assets/142639670/2fcdcfc4-d0d4-41b6-8543-83aa50c3b3f1)
I've tried to add ignorechanges['*'] but that doesn't do anything.

If I add transformations, it will no longer show a diff on aws:autoscaling/group:Group.

This is what `pulumi up --diff` shows:
```
Previewing update (test):
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:test::clusters::pulumi:pulumi:Stack::clusters-test]
        ~ aws:ec2/launchTemplate:LaunchTemplate: (update)
            [id=lt-000000000000000000]
            [urn=urn:pulumi:test::clusters::eks:index:NodeGroupV2$aws:ec2/launchTemplate:LaunchTemplate::test-eks-cluster-nodegroup-system-launchTemplate]
            [provider=urn:pulumi:test::clusters::pulumi:providers:aws::default_6_9_0::c5a67e74-723e-4ffb-ac97-7389ea842852]
            blockDeviceMappings  : [
                [0]: {
                    deviceName: "/dev/xvda"
                    ebs       : {
                        deleteOnTermination: "true"
                        encrypted          : "true"
                        volumeSize         : 50
                        volumeType         : "gp2"
                    }
                }
            ]
            iamInstanceProfile   : {
                arn       : "arn:aws:iam::000000000000:instance-profile/test-eks-cluster-nodegroup-iam-instance-profile"
            }
            imageId              : "ami-0e53e599c9fd9484e"
            instanceMarketOptions: {
            }
            instanceType         : "t3.medium"
            keyName              : "keyname"
            name                 : "test-eks-cluster-nodegroup-system-launchTemplate"
            networkInterfaces    : [
                [0]: {
                    associatePublicIpAddress: "true"
                    securityGroups          : [
                        [0]: "sg-00000000000000000"
                    ]
                }
            ]
            userData             : "xxx"
        ~ aws:autoscaling/group:Group: (update)
            [id=test-eks-cluster-nodegroup-system]
            [urn=urn:pulumi:test::clusters::eks:index:NodeGroupV2$aws:autoscaling/group:Group::test-eks-cluster-nodegroup-system]
            [provider=urn:pulumi:test::clusters::pulumi:providers:aws::default_6_9_0::c5a67e74-723e-4ffb-ac97-7389ea842852]
          ~ launchTemplate: {
              ~ version: "16" => output<string>
            }
```

### Example

I'm using eks.NodeGroupV2

### Output of `pulumi about`

```
CLI          
Version      3.94.2
Go Version   go1.21.4
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       fedora
Version  39
Arch     x86_64

This project is written in nodejs: executable='/nix/store/rzi8a9f7m16n674hvdp6vcmhs19yfzjp-nodejs-20.5.0/bin/node' version='v20.5.0'
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mjeffryes** [comment]
Reproduced this by extracting from one of our exakmples here: [Reproduced · mjeffryes/nodejs-repros@19d9d9d](https://github.com/mjeffryes/nodejs-repros/commit/19d9d9dd54afd388578c76bc0658c2ca016110ee)

**Comment by bradyburke** [comment]
Experiencing the same issue

**Comment by htgarym** [comment]
I'm also seeing this.  Is there a possible work around available?  I've seen that when using NodeGroupV2 this template version change causes the underlying EC2 Instances to be terminated in a rolling manner, which isn't the end of the world, but an unexpected side-effect.

**Comment by bluegumcity** [comment]
@mjeffryes This is a bit more than a usability issue. It is basically enforcing _chaosmonkey_ everytime we do an update in the cluster as it replaces all the nodes.

We moved to `NodeGroup` for a little while but then we run in to other pulumi bugs.

If there are any workaround/fixed or a chance to up the severity of this but it'd be great.

**Comment by rquitales** [comment]
This should be resolved with https://github.com/pulumi/pulumi-eks/pull/1095 being merged. We're looking at cutting a minor release near the end of this week which should bring in these changes.

Note that in my testing, multiple spurious diff bugs had also occurred with older versions of the pulumi-aws provider. Please ensure that your Pulumi program installs an updated version of the AWS provider sdk as well.
